### ISSUE TITLE
Opam switches not showing up in extension

### ISSUE THREAD

**Issue by bella-tassone** [ocamllabs/vscode-ocaml-platform#1016]
Despite having installed all the necessary dependencies and creating a switch, I'm unable to select the switch from the given sandbox options on the extension, as shown.

<img width="1191" alt="Screen Shot 2022-09-11 at 4 46 56 PM" src="https://user-images.githubusercontent.com/54873610/189548223-231cd86e-b95e-46fa-8e86-c02f33f6ea10.png">

I'd appreciate any help, I have no clue why it isn't working.

I definitely have the switch created, as you can see from my terminal.

<img width="390" alt="Screen Shot 2022-09-11 at 4 47 56 PM" src="https://user-images.githubusercontent.com/54873610/189548263-8a8b99fe-b36a-49a5-8f3a-3139470d539c.png">

**Comment by ethanuppal** [comment]
How did you resolve this?
