### ISSUE TITLE
Restarting server fails: "key already exists"

### ISSUE THREAD

**Issue by cemerick** [ocamllabs/vscode-ocaml-platform#1022]
I started having issues with the extension connecting to and/or maintaining the underlying lsp server this morning, without (AFAICT) any changes in relevant configuration or system state. I've restarted vscode, reverted my sources to when tooling was working as expected, cleaned all build artifacts, etc., all with no effect. It may be that doing something more drastic (like rebuilding a new switch or something?) would shake things loose, but it seems worthwhile to at least present the problem/symptoms in case there is an underlying issue that's worth identifying.

In short, I see this error in the vscode OCaml lsp output when the extension attempts to start/reconnect to an lsp server:

```
[Info  - 1:29:42 PM] Connection to server got closed. Server will restart.
[Error - 1:29:42 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:29:42 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:29:42 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/-----------------------------------------------------------------------
| Internal error: Uncaught exception.
| ("Map.add_exn: key already exists",
| { key = "/home/chas/dev/PROJECT" })
| Raised at Stdune__Code_error.raise in file "otherlibs/stdune/code_error.ml", line 11, characters 30-62
| Called from Stdlib__Map.Make.update in file "map.ml", line 283, characters 18-28
| Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
| Called from Ocaml_lsp_server__Dune.poll in file "ocaml-lsp-server/src/dune.ml", line 529, characters 6-298
| Called from Fiber__Core.apply2 in file "src/fiber/core.ml", line 96, characters 6-11
| Re-raised at Stdune__Exn.raise_with_backtrace in file "otherlibs/stdune/exn.ml" (inlined), line 36, characters 27-56
| Called from Stdune__Exn_with_backtrace.reraise in file "otherlibs/stdune/exn_with_backtrace.ml", line 18, characters 33-71
| Called from Fiber__Scheduler.advance.(fun) in file "src/fiber/scheduler.ml", line 191, characters 2-58
| Called from Fiber.run.loop in file "src/fiber/fiber.ml", line 15, characters 30-61
| Called from Stdune__Exn_with_backtrace.try_with in file "otherlibs/stdune/exn_with_backtrace.ml", line 9, characters 8-12
\-----------------------------------------------------------------------
```

My usual workflow is to run one of a number of dune aliases in watch mode, which keeps the lsp config current and keeps tabs on any test failures, etc., e.g. `dune build @rundev -w`. This now produces the above failure, but _removing the watch option restores expected LSP functionality_.

Any thoughts?

**Comment by rgrinberg** [comment]
The simplest workaround is to upgrade to the latest version of ocamllsp.

Closing because this is an ocamllsp issue.

**Comment by cemerick** [comment]
Yeah, @beajeanm pointed me towards https://github.com/ocaml/ocaml-lsp/issues/693 just a minute ago. Cheers :+1:
