### ISSUE TITLE
Add ocamlformat to the fmt script

### ISSUE THREAD

**Issue by rgrinberg** [ocamllabs/vscode-ocaml-platform#103]
~~We'd also like an ocamlformat config.~~ We have, it's just not in use.

**Comment by imbsky** [comment]
It seems like we have that now. But, I would like to use package.json only for things related to Node.js. For that reason, I open a PR to add a Makefile as #135, what do you think?
https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/package.json#L314

**Comment by rgrinberg** [comment]
@imbsky can this be closed?

**Comment by imbsky** [comment]
@rgrinberg Yes!
