### ISSUE TITLE
Improve dune highlighting

### ISSUE THREAD

**Issue by mnxn** [ocamllabs/vscode-ocaml-platform#106]
The syntax for dune files is missing highlighting for certain keywords and other parts of the file format (operators, variables, etc): 
![image](https://user-images.githubusercontent.com/25037249/78419709-5d41f200-75fd-11ea-87a8-acedf976dd10.png)

**Comment by rgrinberg** [comment]
Another nice thing to have would be proper syntax highlighting for dune files that use OCaml syntax. In other words, files that have the following first line: `(* -*- tuareg -*- *)`

**Comment by SaySayo** [comment]
Can i work on this issue?

**Comment by SaySayo** [comment]
Thank you! I have a basic understanding of RegEx and I'd appreciate if you recommend more resources on it.

**Comment by tmattio** [comment]
https://www.sitepoint.com/learn-regex/ also seems like a great tutorial, and I'd recommend using https://regex101.com/ as a playground to test different RegEx while learning about them.

**Comment by mnxn** [comment]
To be clear, the improvements I had in mind are to rewrite [dune.json](https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/syntaxes/dune.json) in a similar fashion to the [dune-project.json](https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/syntaxes/dune-project.json) and [dune-workspace.json](https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/syntaxes/dune-workspace.json) syntaxes.

That is, only valid stanzas should be highlighted in the appropriate contexts. The `dune-project` and `dune-workspace` syntax highlighting already does this (although it may be slightly outdated, I'm not sure). This requires heavily referencing https://dune.readthedocs.io/en/stable/dune-files.html.

It's a lot of tedious work (the `dune` format is much larger than both `dune-project` and `dune-workspace`), so I'm not sure this issue is viable as a "good first issue".

**Comment by tmattio** [comment]
Closed by #742
