### ISSUE TITLE
"Host Extension Quit Unexpectedly"

### ISSUE THREAD

**Issue by Marc-9** [ocamllabs/vscode-ocaml-platform#1073]
The Ocaml Platform VScode extension is continuously quitting unexpectedly (as reported by Vscode) taking down the source control with it. Vscode will restart it but after this occurs 3 times in 5 minutes it does not restart the extension and I can no longer use source control with VScode.

On launch of VScode the extension informs me
"There is a newer version of ocaml-lsp-server available. Consider upgrading from 1.14.2 to 1.15.0-4.14. Hint: $ opam install ocaml-lsp-server=1.15.0-4.14 and restart the lsp server"

Attempting to run this command results in 
`[ERROR] Package ocaml-lsp-server has no version 1.15.0-4.14.`

Running `opam upgrade ocaml-lsp-server` results in
```
[ERROR] Package conflict!
  * No agreement on the version of ocaml-base-compiler:
    - (invariant) → ocaml-base-compiler = 4.14.0
    - ocaml-lsp-server >= 1.15.0~5.0preview1 → ocaml >= 5.0 → ocaml-base-compiler >= 5.0.0~
    You can temporarily relax the switch invariant with `--update-invariant'
  * Incompatible packages:
    - (invariant) → ocaml-system = 4.14.0
    - ocaml-lsp-server >= 1.15.0~5.0preview1 → ocaml >= 5.0 → ocaml-base-compiler
  * Missing dependency:
    - ocaml-lsp-server >= 1.15.0~5.0preview1 → ocaml >= 5.0 → ocaml-variants → ocaml-beta
    unmet availability conditions: 'enable-ocaml-beta-repository'
```

Here is a screenshot of VScode developer tools indicating the error that is causing Ocaml Platforms to fail
![CleanShot 2023-01-15 at 17 59 02](https://user-images.githubusercontent.com/37602279/212583207-4ee916b0-28a5-4402-a4b0-4a2cf0710dfa.png)

Other informarion
The OCaml toplevel, version 4.14.0
Macbook M2 2022

**Comment by ulugbekna** [comment]
Hi @Marc-9 ,
1. Did you run an opam update before upgrading ocaml-lsp-server?
2. Could you show a video screenshot of what’s happening? 
3. You can expand the error in the dev tools to show us the stack trace

**Comment by Marc-9** [comment]
1.
`<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] Could not update repository "default": OpamDownload.Download_fail(_,
        "Download command failed: \"/usr/local/bin/wget --content-disposition
        -t 3 -O
        /private/var/folders/pc/2ts8cnpd48g6ns02238yd0qh0000gp/T/opam-98032-8d134e/index.tar.gz.part
        -U opam/2.1.4 -- https://opam.ocaml.org/index.tar.gz\" exited with code
        256")`
2.

https://user-images.githubusercontent.com/37602279/212600154-1f1118a6-560c-4517-b704-3032949ecb26.mov

3.
![CleanShot 2023-01-15 at 20 40 40](https://user-images.githubusercontent.com/37602279/212600202-63a10c3d-7794-4aef-a26a-1297b76a94d2.png)

**Comment by ulugbekna** [comment]
opam update failing is rare, I would investigate it if I were you 

the extension host quitting should be unrelated, but tbh I’m not sure how to investigate this

**Comment by Marc-9** [comment]
I fixed spam update by doing 
 brew upgrade wget

So I no longer get an out of date LSP server warning on launch, but the extension still fails over and over again

Let me know if I can provide any additional debugging information

**Comment by Marc-9** [comment]
Here is the buffer error expanded
<img width="606" alt="CleanShot 2023-01-16 at 12 52 07@2x" src="https://user-images.githubusercontent.com/37602279/212763948-7a5d7fdf-91f3-48fd-bbb0-a2f8881c3d47.png">

**Comment by ulugbekna** [comment]
1. Please provide your vs code version and the ocaml-platform extension version. 
2. Can you reproduce with all extensions except ours disabled? (it was previously the case, in which gitlens extension caused a very similar, if not the same, issue) 
3. There's a extension bisecting feature in vscode that may help - https://stackoverflow.com/a/70132866/5281528. Not sure how it works but maybe it helps if the problem is in (2)

**Comment by Marc-9** [comment]
VSCode Version
Version: 1.74.3

Ocaml-platform
v1.12.1

No error when extension is disables, errors when the extension is enabled

Ive turned on Ocaml Trace Server verbose and invoked the command
OCaml: Show OCaml Language Server Output

Nothing appears in the console, but when the error appears this console is cleared (since the extension fails and quits)

I either need to code without this extension (meaning no syntax highlighting) or attempt to re-install all my packages which I don't feel comfortable doing

**Comment by ulugbekna** [comment]
Try disabling all extensions except the ocaml platform extension - this will likely help.

**Comment by Trebor-Huang** [comment]
I seem to see a similar behaviour. Only the OCaml platform extension is enabled. It produces the same error message (except the path is different).

**Comment by Trebor-Huang** [comment]
A few observations:
- This path doesn't exist unless I start dune in watch mode, e.g. ocaml/ocaml-lsp#802
- It still crashes even if the file exists. So perhaps that is not the relevant error. The new output is:
```
[Info  - 6:56:25 PM] Connected to dune [path] ([path]/_build/.rpc/dune)
[Info  - 6:56:25 PM] client 0: connecting...
[Info  - 6:56:25 PM] client 0: connected to dune at unix:///[path]/_build/.rpc/dune
```
Where `[path]` is the path of my project.

**Comment by Trebor-Huang** [comment]
Also all the issues (this one and #1018 #849) seems to be on OS X.

**Comment by Trebor-Huang** [comment]
I found that in my case it is the builtin Git functionality triggering the crash. So whenever there is something non-trivial happening in git the plugin will crash, with no other extensions installed.

**Comment by rgrinberg** [comment]
Please re-open if you can reproduce in 1.13.1
