### ISSUE TITLE
Syntax highlighting in large files

### ISSUE THREAD

**Issue by jboillot** [ocamllabs/vscode-ocaml-platform#1081]
Hello,
I am experiencing syntax highlighting issues in large OCaml files that do not appear in the Tokens and Scopes Inspector. I have checked that all characters of `Integer` have the same properties.
![Screenshot from 2023-02-09 16-41-38](https://user-images.githubusercontent.com/52931370/217863843-e2cefc44-b6f1-4dfd-9022-7404c6499af6.png)
![Screenshot from 2023-02-09 17-34-41](https://user-images.githubusercontent.com/52931370/217878466-8821198a-e3b7-43db-93f1-f0c75c8b63b2.png)
![Screenshot from 2023-02-09 17-36-46](https://user-images.githubusercontent.com/52931370/217878482-01eff4c3-4649-46db-92a0-0f1fcb7b1b60.png)

While reading the ocaml-lsp-server logs I spotted the following errors: 
```
[Trace - 4:38:50 PM] Received response 'textDocument/documentHighlight - (132)' in 1511ms. Request failed: cancelled (-32800).
...
[Trace - 4:38:50 PM] Received response 'textDocument/semanticTokens/full - (133)' in 1760ms. Request failed: uncaught exception (-32603).
Error data: {
    "exn": "Invalid_argument(\"String.sub / Bytes.sub\")",
    "backtrace": "Raised at Stdlib.invalid_arg in file \"stdlib.ml\", line 30, characters 20-45\nCalled from Stdlib__String.sub in file \"string.ml\", line 50, characters 2-23\nCalled from Ocaml_lsp_server__Semantic_highlighting.Parsetree_fold.source_excerpt in file \"ocaml-lsp-server/src/semantic_highlighting.ml\", line 344, characters 4-74\nCalled from Ocaml_lsp_server__Semantic_highlighting.Parsetree_fold.pat in file \"ocaml-lsp-server/src/semantic_highlighting.ml\", line 726, characters 10-44\nCalled from Ocaml_lsp_server__Semantic_highlighting.Parsetree_fold.expr in file \"ocaml-lsp-server/src/semantic_highlighting.ml\", line 604, characters 18-35\nCalled from Ocaml_lsp_server__Semantic_highlighting.Parsetree_fold.value_binding in file \"ocaml-lsp-server/src/semantic_highlighting.ml\", line 485, characters 10-33\nCalled from Stdlib__List.iter in file \"list.ml\", line 110, characters 12-15\nCalled from Stdlib__List.iter in file \"list.ml\", line 110, characters 12-15\nCalled from Ocaml_lsp_server__Semantic_highlighting.Parsetree_fold.module_expr in file \"ocaml-lsp-server/src/semantic_highlighting.ml\", line 787, characters 10-34\nCalled from Ocaml_lsp_server__Semantic_highlighting.Parsetree_fold.module_expr in file \"ocaml-lsp-server/src/semantic_highlighting.ml\", line 782, characters 8-32\nCalled from Ocaml_lsp_server__Semantic_highlighting.Parsetree_fold.module_expr in file \"ocaml-lsp-server/src/semantic_highlighting.ml\", line 782, characters 8-32\nCalled from Ocaml_lsp_server__Semantic_highlighting.Parsetree_fold.module_expr in file \"ocaml-lsp-server/src/semantic_highlighting.ml\", line 782, characters 8-32\nCalled from Ocaml_lsp_server__Semantic_highlighting.Parsetree_fold.module_binding in file \"ocaml-lsp-server/src/semantic_highlighting.ml\", line 412, characters 4-34\nCalled from Stdlib__List.iter in file \"list.ml\", line 110, characters 12-15\nCalled from Ocaml_lsp_server__Semantic_highlighting.Parsetree_fold.apply in file \"ocaml-lsp-server/src/semantic_highlighting.ml\", line 890, characters 35-72\nCalled from Fiber__Core.O.(>>|).(fun) in file \"src/fiber/core.ml\", line 250, characters 36-41\nCalled from Fiber__Scheduler.exec in file \"src/fiber/scheduler.ml\", line 73, characters 8-11\nRe-raised at Stdune__Exn.raise_with_backtrace in file \"otherlibs/stdune/exn.ml\" (inlined), line 36, characters 27-56\nCalled from Stdune__Exn_with_backtrace.reraise in file \"otherlibs/stdune/exn_with_backtrace.ml\", line 18, characters 33-71\nCalled from Fiber__Scheduler.exec in file \"src/fiber/scheduler.ml\", line 73, characters 8-11\n"
}
```
~So, I guess this is related with this line of ocaml-lsp-server: https://github.com/ocaml/ocaml-lsp/blob/1dc8c324aa5aae2f94f6c92e238966312e45e039/ocaml-lsp-server/src/semantic_highlighting.ml#L285. I don't know if I should report this issue to them because I don't know how the two projects are interfaced. But please tell me if it would fit better elsewhere.~

Edit: I changed my mind, I don't think anymore it's related with this ocaml-lsp-server error. Indeed, I've modified the source of ocaml-lsp-server to print the string and the offsets when an error occur. But I discovered I can get wrong syntax highlightings in vscode while having no ocaml-lsp-server errors. So I guess those errors are unrelated.

I'm running the extension on Ubuntu, VS Code 1.75.0, Ocaml Platform 1.12.2, ocaml-lsp `1.14.2-26-g6dbaeca-dirty`. I have tried removing all other extension (particularly the theme one) except Ocaml Platform, but I still get wrong syntax highlightings.

Thank you for reading, if I can provide you more information don't hesitate to ask!

Have a good end of week.

**Comment by ulugbekna** [comment]
Hi!

The syntax highlighting problem may or may not be because of the ocaml-lsp problem. I believe I saw cases when ocaml-lsp was sending correct data, but vscode theme did not color everything correctly. 

Regardless, it would be good to fix the problem that causes the exception you put above. Could you share the file for which this error happens? Does the error occur for the file as is or when you're editing it?

**Comment by jboillot** [comment]
Hello!
Thanks for your answer. Unfortunately, I can't share the file for which this error happens, but I can tell you it occurs for the file as is.
I can't re-trigger the error I was talking about, but I have isolated a file that, opened alone, is badly highlighted while not raising any error in ocaml-lsp. It is ~1400 lines long.
The only "weird" response I see in the logs is the response to a `textDocument/semanticTokens/full` request that is ~23k lines long (~23k tokens I guess). Here is an extract:
```
[Trace - 4:13:10 PM] Received response 'textDocument/semanticTokens/full - (4)' in 1576ms.
Result: {
    "data": [
        2,
        0,
        3,
        0,
        0,
...
        8,
        0,
        0
    ],
    "resultId": "0"
}
```

If I can try other things that may be useful, even log variables from ocaml-lsp don't hesitate to ask, I can do it if you tell what could be interesting to investigate on!

**Comment by jboillot** [comment]
Ok, now I have something different in the Tokens and Scopes inspector depending on where I click in the keyword “open” :
![Screenshot from 2023-02-10 16-41-56](https://user-images.githubusercontent.com/52931370/218133757-7f088fd4-2b05-4649-95b2-5fae6d242e6d.png)
![Screenshot from 2023-02-10 16-42-07](https://user-images.githubusercontent.com/52931370/218133768-f60ddbb7-365c-4819-81ea-a7b4ca0844a0.png)

It seems the beginning is recognized as a Java keyword? I don't know at all how syntax highlighting in VSCode works, so I apologize in advance if it makes no sense.

**Comment by jboillot** [comment]
Hello!

I finally got why I had those errors : it's not because of file length, but because the project is using [cppo](https://github.com/ocaml-community/cppo) preprocessor syntax.
Thus, first of all this would be an ocaml-lsp issue, and secondly it is a compatibility issue.

Thanks for your help, I'm closing the issue :)
