### ISSUE TITLE
Color highlighting is broken

### ISSUE THREAD

**Issue by fedodd** [ocamllabs/vscode-ocaml-platform#1087]
Code highlight is broken for me.
Version: v1.12.2

here few examples:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/20857575/223408731-91321fc6-0ead-4437-b97e-969641be61e2.png">
```
  <g
    onClick={_ => {isClickable ? onClickHandler(~label=name) : ()}}
    className={Css.itemIsClickable->Cn.ifTrue(isClickable)}>
    <rect
      x={x->Int.toString}
      y={y->Int.toString}
      width={width->Int.toString}
      height={height->Int.toString}
      fill={bgColor->Emotion.colorToString}
      fillOpacity={opacity->Float.toString}
      stroke={StyleVars.Color.Background.box->Emotion.colorToString}
    />
    {let {x, y, width, height} = textCords;
     depth === 1
       ? <foreignObject className=Css.textWrapper x y width height>
           <span className={Css.itemText(textColor)}> name->RR.s </span>
         </foreignObject>
       : RR.null}
  </g>;
```

<img width="838" alt="Screenshot 2023-03-07 at 17 25 32" src="https://user-images.githubusercontent.com/20857575/223409094-2042b227-246c-4a90-aa46-fa60641ce8fb.png">

```
[@react.component]
let make = (~text, ~onChange, ~onSubmit) => {
  let plan = KePlanStore.useSelector(KePlanStore.planSelector);
  <KeEntryTextarea text limit={plan.limits.batchKeywords} onChange onSubmit minHeight=170 />;
};

```

<img width="758" alt="image" src="https://user-images.githubusercontent.com/20857575/223409360-7a839c53-47ed-4262-9d87-c88f68c2d367.png">

```
<Row gap=`px6>
        <Input.Int
          domRef=inputRef
          placeholder=[%intl.s {msg: {js|Up to|js}, desc: "Up to some raiting"}]
          value=inputValue
          onChange={value => {
            let ratingOpt =
              switch (value) {
              | Some(value) when value < minRating => Some(minRating)
              | Some(value) when value > maxRating => Some(maxRating)
              | value => value
              };
            dispatch @@ RatingUpdated(ratingOpt);
          }}
        />
      </Row>
```

**Comment by smorimoto** [comment]
If I understand you correctly, this is a problem with ReasonML, right?

**Comment by fedodd** [comment]
Yes, with ReasonML.

Regards, Fedor

**Comment by johnhaley81** [comment]
I also see this often. Another example:

<img width="902" alt="image" src="https://github.com/ocamllabs/vscode-ocaml-platform/assets/867780/e22356c8-369a-4851-83f1-ab3571d459c5">

**Comment by jchavarri** [comment]
For the record, I am investigating this issue and it seems to only occur when the file is opened in vscode through ssh connection, but not locally. I am trying to find any other existing issues for other syntax highlighting extensions in other languages or a way to debug how vscode processes the string to highlight it, but no luck yet.
