### ISSUE TITLE
ocamlformat-rpc no longer required?

### ISSUE THREAD

**Issue by ssfrr** [ocamllabs/vscode-ocaml-platform#1094]
According to [these release notes](https://github.com/ocaml/opam-repository/commit/38a21e89ad0501fd814bc9f3ce308c02447d8021) `ocamlformat-rpc` is now distributed as part of the `ocamlformat` package as of version 0.22.4.

The vscode-ocaml-platform setup guide says to install `ocamlformat-rpc`. The latest version of that package doesn't seem to be compatible with ocaml v5, so it forces opam to downgrade.

Can the instruction to install `ocamlfomat-rpc` be removed?

**Comment by ssfrr** [comment]
Also the instructions here should be updated: https://github.com/ocamllabs/vscode-ocaml-platform/blob/f85536ccf9ae8999f6118fd460631111af6a57f2/README.md?plain=1#L47

**Comment by mnxn** [comment]
The references to `ocamlformat-rpc` were removed in #1105.
