### ISSUE TITLE
Sometimes the wrong documentation is displayed

### ISSUE THREAD

**Issue by yminsky** [ocamllabs/vscode-ocaml-platform#111]
I noticed this when playing around with some test code.  Here's the code on it's own:

![DeepinScreenshot_select-area_20200404143223](https://user-images.githubusercontent.com/715302/78458693-3927f480-7681-11ea-84e0-c26d4aac5236.png)

And here's what I get when I hover over "names".  Note that the documentation is for the In_channel module, but the type is from names.

![DeepinScreenshot_select-area_20200404143208](https://user-images.githubusercontent.com/715302/78458675-2ad9d880-7681-11ea-9657-cf0f4c61ef1a.png)

**Comment by yminsky** [comment]
I just checked with the latest vscode and latest lsp plugin, and the problem is still replicable.

**Comment by ulugbekna** [comment]
This should be fixed on ocaml-lsp's master.
