### ISSUE TITLE
Problems when non-ASCII characters in folder name

### ISSUE THREAD

**Issue by yannl35133** [ocamllabs/vscode-ocaml-platform#117]
When I have the file structure ("""file contents""") :
```
New
├── dune-project            """(lang dune 2.4)"""
├── lib
│   ├── dune                """(library    (name lib))"""
│   └── lib.ml              """type t"""
└── lib2
    ├── dune                """(library    (name lib2)    (libraries lib))"""
    └── lib2.ml             """type t = Lib.t"""
```
everything works as intended, but when I change `New` to `Néw`, type `Lib.t` becomes unbound in `lib2.ml`. 
When I build with Dune, it compiles fine (as there is no problem)

**Comment by imbsky** [comment]
@rgrinberg Could you check this?

**Comment by giltho** [comment]
it looks like an ocaml-lsp issue and my guess would be that it comes from this issue https://github.com/ocaml/ocaml-lsp/issues/95

**Comment by rgrinberg** [comment]
Indeed, this is an ocaml-lsp issue.

**Comment by yannl35133** [comment]
Problem reappeared, I won't reopen here since it's not the right repository. See above
