### ISSUE TITLE
rename on extensible variant causes uncaught exception

### ISSUE THREAD

**Issue by pe200012** [ocamllabs/vscode-ocaml-platform#1185]
minimal code to reproduce:
```ocaml
type t = ..
type t += A

let foo (x : t) = match x with
| A -> 1
| _ -> 0
```
result:
![image](https://github.com/ocamllabs/vscode-ocaml-platform/assets/13463539/59af6809-c716-40bc-92b3-029e50d04ef8)

info:
OCaml Platform v1.13.0
```
> ocamlc --version; ocamllsp --version; dune --version
4.14.1
1.15.1-4.14
3.7.1
```

**Comment by rgrinberg** [comment]
cc @voodoos

**Comment by voodoos** [comment]
Thanks for the report, I proposed a fix: https://github.com/ocaml/merlin/pull/1662

**Comment by rgrinberg** [comment]
Thanks for the report @pe200012  and thanks for the quick fix @voodoos
