### ISSUE TITLE
restart every startup

### ISSUE THREAD

**Issue by axplus** [ocamllabs/vscode-ocaml-platform#1186]
Type: <b>Bug</b>

Extension host terminated unexpectedly 3 times within the last 5 minutes.

Extension version: 1.13.0
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:58.115Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|--crash-reporter-id 924721b6-5f82-411c-ac63-5e226384253e --inspect-extensions=64896 --crash-reporter-id 924721b6-5f82-411c-ac63-5e226384253e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30795824
dsvsc013:30795093

```

</details>

**Comment by Hirrolot** [comment]
This is also the case for me.

**Comment by rgrinberg** [comment]
@axplus @Hirrolot do you have github copilot installed?

**Comment by toku-sa-n** [comment]
I had the same experience and resolved it by updating Copilot to v1.104.341.

**Comment by axplus** [comment]
no, I donot installed copilot. I tested with all plugins uninstalled, but it still crashes.

**Comment by axplus** [comment]
like this:

<img width="1039" alt="image" src="https://github.com/ocamllabs/vscode-ocaml-platform/assets/1296434/207c3f26-92f1-414c-98e3-0851e2d0a4a1">

**Comment by axplus** [comment]
like this

<img width="1177" alt="image" src="https://github.com/ocamllabs/vscode-ocaml-platform/assets/1296434/b19615bc-26df-47d1-8295-4390714ab312">

**Comment by Hirrolot** [comment]
@rgrinberg, nope, OCaml Platform still crashes with all other extensions disabled. I've resolved this issue by downgrading OCaml Platform to `v1.12.2`. I use GitHub Copilot now and everything works well.

**Comment by axplus** [comment]
@Hirrolot Thanks, but

<img width="1351" alt="image" src="https://github.com/ocamllabs/vscode-ocaml-platform/assets/1296434/44a1077e-bbe9-44b1-a6f3-e4d1badbc0b3">

**Comment by Trebor-Huang** [comment]
Is this related to #1077 ?

**Comment by rgrinberg** [comment]
Please re-open if you can reproduce in 1.13.1
