### ISSUE TITLE
Add ml/mli switching

### ISSUE THREAD

**Issue by rgrinberg** [ocamllabs/vscode-ocaml-platform#119]
Ideally, this should be implemented on the LSP side. However, it's quiet useful to also have it when there's no LSP server installed.

**Comment by rgrinberg** [comment]
I've done further investigation on this. In particular, the cpp extension has similar keybindings:

```
    "keybindings": [
      {
        "command": "C_Cpp.SwitchHeaderSource",
        "key": "Alt+O",
        "when": "editorTextFocus && editorLangId == 'cpp'"
      },
      {
        "command": "C_Cpp.SwitchHeaderSource",
        "key": "Alt+O",
        "when": "editorTextFocus && editorLangId == 'c'"
      }
    ],
```

So from here, we already know that we should reuse the `Alt+O` binding for this. Then, the [source](https://github.com/microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/extension.ts) for the command above is:

```typescript
    clients.ActiveClient.requestSwitchHeaderSource(rootPath, fileName).then((targetFileName: string) => {
        vscode.workspace.openTextDocument(targetFileName).then((document: vscode.TextDocument) => {
            let foundEditor: boolean = false;
            // If the document is already visible in another column, open it there.
            vscode.window.visibleTextEditors.forEach((editor, index, array) => {
                if (editor.document === document && !foundEditor) {
                    foundEditor = true;
                    vscode.window.showTextDocument(document, editor.viewColumn);
                }
            });
            // TODO: Handle non-visibleTextEditor...not sure how yet.
            if (!foundEditor) {
                if (vscode.window.activeTextEditor !== undefined) {
                    // TODO: Change to show it in a different column?
                    vscode.window.showTextDocument(document, vscode.window.activeTextEditor.viewColumn);
                } else {
                    vscode.window.showTextDocument(document);
                }
            }
        });
    });
```

So we all need to do is:

1) Add the keybinding configuration and port the code above to OCaml
2) Implement `requestSwitchHeaderSource` on the lsp side

@mnxn shall we split 1) and 2) between us? (I can tackle 2).

**Comment by mnxn** [comment]
Sure. I will be free to work on this tomorrow.

**Comment by rgrinberg** [comment]
By the way, the above was learned from the C++ plugin. If someone is familiar with other plugins for languages with interface/header files, it would be interesting to compare the approach.

**Comment by mnxn** [comment]
The interaction between .ml and .mli files seems to be much simpler to me than C++ source and headers.

If we can assume that .ml and .mli files for a module are in the same directory, the extension can check for the opposite file and switch to it if present. Maybe it's just convention, but I've never encountered a situation where .ml and .mli files for the same module were in different directories.

Of course, if we can't make that assumption, the switching will require integration with the language server.

**Comment by rgrinberg** [comment]
If you’d like, you can implement this as a fallback mechanism for older servers or when the server isn’t running. Seems like it would be useful to have.

Just keep in mind the following:

* mll and mly files may have mli files as well
* the mli file for implementations of virtual libraries may be implemented elsewhere.

This is why I want to make sure that all this logic is shared between editors.
