### ISSUE TITLE
Unable to find ocamlformat binary

### ISSUE THREAD

**Issue by zwx1127** [ocamllabs/vscode-ocaml-platform#120]
Message: Unable to find ocamlformat binary
  Code: -32600 
[Error - 10:18:33 AM] [lsp] Unable to find ocamlformat binary

I have installed ocamlformat, path: ./_opam/bin/ocamlformat.

**Comment by imbsky** [comment]
Is ocamlformat in PATH?

**Comment by rgrinberg** [comment]
In the upcoming version of extension, you will be able to set the toolchain explicitly. This should be enough to point at the right ocamlformat.

**Comment by imbsky** [comment]
I don't think this is a problem with this extension, so I will close this.
