### ISSUE TITLE
variant pattern snippet is not working

### ISSUE THREAD

**Issue by naosense** [ocamllabs/vscode-ocaml-platform#1229]
when press `|` , variant pattern snippet is not working
<img width="337" alt="image" src="https://github.com/ocamllabs/vscode-ocaml-platform/assets/2225426/0d2e83a7-4a92-4942-a89b-8261b02a64ad">

**Comment by smorimoto** [comment]
It's just a snippet and I don't know what the problem is. If you are sure this is a issue, please provide more context.
