### ISSUE TITLE
v1.13.2 breaks ocamllsp 

### ISSUE THREAD

**Issue by GargSar** [ocamllabs/vscode-ocaml-platform#1250]
V1.13.2 of the extension breaks ocaml intellisense. 

There is no more `Go to definition/declaration/references` options upon right-click, no more type annotations, pretty much none of the intellisense works. The error we've seen is `ocamllsp is not running`.

Upon reverting to C1.13.1 everything starts working as expected immediately.

**Comment by GargSar** [comment]
User Error: **OCaml Language Server Output:** `The language client requires VS Code version ^1.82.0 but received version 1.79.2`

**Comment by smorimoto** [comment]
`vscode-languageclient` added that constraint: https://github.com/ocamllabs/vscode-ocaml-platform/pull/1220
I'm going to publish the next point release with updated version lower bounds on the extension side as well to make that clearer.
