### ISSUE TITLE
Is the font for inferred types configurable?

### ISSUE THREAD

**Issue by unfode** [ocamllabs/vscode-ocaml-platform#1314]
![image](https://github.com/ocamllabs/vscode-ocaml-platform/assets/95689995/9783a7ef-48b6-4d7b-a9c7-130ed87e39d6)

**Comment by mnxn** [comment]
You can change it with the VS Code `editor.codeLensFontFamily` setting. Either through `settings.json` or in the settings UI:
![image](https://github.com/ocamllabs/vscode-ocaml-platform/assets/25037249/6d57a1e1-d965-4830-bd09-612393eb4244)

**Comment by unfode** [comment]
Thank you!!
