### ISSUE TITLE
Incorrect syntax highlighting for "Special Identity External"

### ISSUE THREAD

**Issue by imbsky** [ocamllabs/vscode-ocaml-platform#133]
https://bucklescript.github.io/docs/en/intro-to-external#special-identity-external

|                                                    Current                                                     |                                                    Expected                                                    |
| :------------------------------------------------------------------------------------------------------------: | :------------------------------------------------------------------------------------------------------------: |
| ![image](https://user-images.githubusercontent.com/38746192/79119603-b7943d00-7dcb-11ea-8aa3-007481a19935.png) | ![image](https://user-images.githubusercontent.com/38746192/79119702-f629f780-7dcb-11ea-9439-697ed7560828.png) |

**Comment by imbsky** [comment]
CC: @mnxn

**Comment by mnxn** [comment]
I can't reproduce: 
![image](https://user-images.githubusercontent.com/25037249/79133346-bc6fd700-7d60-11ea-9cc3-dc28524cc03c.png)

I thought I fixed this in #115. Are you running the extension built from master? Or is that string showing up in a non-external declaration?

**Comment by imbsky** [comment]
Oh, it seems that my extension was replaced with release version for some reason...
