### ISSUE TITLE
`make deps` raises an error about yarn

### ISSUE THREAD

**Issue by aqjune** [ocamllabs/vscode-ocaml-platform#1358]
When I am running `make deps`, I am seeing this error:
```
~/vscode-ocaml-platform$ make deps
make yarn-deps
make[1]: Entering directory '/home/aqjune/vscode-ocaml-platform'
yarn --immutable
Usage: yarn [options]

yarn: error: no such option: --immutable
make[1]: *** [Makefile:9: yarn-deps] Error 2
make[1]: Leaving directory '/home/aqjune/vscode-ocaml-platform'
make: *** [Makefile:13: deps] Error 2
```
OS is Ubuntu. Which package should I apt install?
I am following https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/CONTRIBUTING.md but at the document does not tell how to install preprequired `yarn`.

---

Okay, I could install yarn using `npm install -g yarn@latest`! However I met 
```
$ make deps
make yarn-deps
make[1]: Entering directory '/home/aqjune/vscode-ocaml-platform'
yarn --immutable
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0014: │ astexplorer@file:/home/aqjune/vscode-ocaml-platform/astexplorer: Only some patterns can be imported from legacy lockfiles (not "file:astexplorer")
➤ YN0085: │ + @biomejs/biome@npm:1.5.2, @swc-node/register@npm:1.6.8, @swc/core@npm:1.3.104, @tsconfig/node20@npm:20.1.2, @tsconfig/strictest@npm:2.0.2, @types/fs-extra@npm:11.0.4, and 596 more.
➤ YN0000: └ Completed in 3m 29s
➤ YN0000: ┌ Post-resolution validation
➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
➤ YN0000: └ Completed
➤ YN0000: · Failed with errors in 3m 29s
make[1]: *** [Makefile:9: yarn-deps] Error 1
make[1]: Leaving directory '/home/aqjune/vscode-ocaml-platform'
make: *** [Makefile:13: deps] Error 2
```

Do you have any idea about this issue? I am using ECMAScript 21 (`nvm install 21`).

**Comment by aqjune** [comment]
Before running this, I did `npm install` and it successfully installed all relevant node.js dependencies.
Also `make switch` was okay before this same yarn part.

**Comment by aqjune** [comment]
Running `yarn install` resolved this issue..! :)

**Comment by smorimoto** [comment]
You need to use a newer version of yarn, probably because the yarn in your environment is outdated. yarn v1 is already deprecated and it's recommended to switch to yarn v4.

**Comment by smorimoto** [comment]
The lockfile error is weird, but immutable flag is not required 🙂
