### ISSUE TITLE
[0.5.0] Unwanted error alert

### ISSUE THREAD

**Issue by rusty-key** [ocamllabs/vscode-ocaml-platform#143]
In any unconfigured project as soon as I open it, I get "Toolchain initialization fails: ..." alert. But at the same time extension recognizes that no toolchain is attached to the project yet.
![Screen%20Shot%202020-04-16%20at%2012 55 21%20PM](https://user-images.githubusercontent.com/1197026/79444072-58107a00-7fe3-11ea-8542-8fe0d3fc4ae5.png)

In BSB project one initialization starts as soon as I load the project, so I can end up in this situation:
![Screen%20Shot%202020-04-16%20at%2012 57 52%20PM](https://user-images.githubusercontent.com/1197026/79445015-a5411b80-7fe4-11ea-960b-e0d5c95bb896.png)

Looks like extension tries to initialize too early

**Comment by rusty-key** [comment]
Looks like we immediately falling back to `Global` without waiting for what user chooses:
https://github.com/ocamllabs/vscode-ocaml-platform/blob/a375e62bc2695f97e1aa96c59975f192791885d4/src/Extension.ml#L79-L82

@rgrinberg, is it something intentional? If we want to fall back to global in that way, I think we should scan for `ocamllsp` and report back if doesn't exist or compiled for the wrong version.

**Comment by rgrinberg** [comment]
@rusty-key I think you've fixed this issue in master?
