### ISSUE TITLE
Broken link to Dune docs in README

### ISSUE THREAD

**Issue by ahelwer** [ocamllabs/vscode-ocaml-platform#1545]
>If you use dune language version 3.0+ to build your project, switch to 3.7+ and make sure that you add:
>`(map_workspace_root false)`
>to your dune-project file. More info on this [here](https://dune.readthedocs.io/en/stable/dune-files.html#map-workspace-root).

The Dune documentation entry for `map_workspace_root` no longer exists, so it is unclear what this step does or whether it is still necessary.

**Comment by smorimoto** [comment]
CC: @rgrinberg
