### ISSUE TITLE
Issue when trying to install v0.5.0

### ISSUE THREAD

**Issue by thatportugueseguy** [ocamllabs/vscode-ocaml-platform#158]
I'm trying to run this extension from vsix on version 0.5.0 from master.  I'm trying to install on a reason project, not an ocaml one.

I deleted all existing `esy` folders, and keep getting the following issue:
<img width="551" alt="Screenshot 2020-04-30 at 17 08 37" src="https://user-images.githubusercontent.com/8755205/80735407-8d02ed80-8b08-11ea-80c0-2306ecce1b46.png">

Output when ran in terminal, using esy v.0.6.4: 
```
$ esy --version
0.6.4
$ /usr/local/bin/esy -P /Users/ze/Projects/ahrefs/frontend/packages/keywords-explorer/.vscode/esy ocamllsp --help=plain
error: no manifests found at /Users/ze/Projects/ahrefs/frontend/packages/keywords-explorer/.vscode/esy

esy: exiting due to errors above
```

Not sure if i'm missing anything or if there is anything else i need to do for the setup?

**Comment by rusty-key** [comment]
The check I added is faulty. `esy` fails if its root doesn't exist

**Comment by rusty-key** [comment]
Here's the problem: 
https://github.com/ocamllabs/vscode-ocaml-platform/blob/18a0b4b786f47798e3483b869103284a541585f3/src/esy.ml#L127-L129

**Comment by mnxn** [comment]
This should no longer be a problem with the latest release since the extension no longer tries to setup the Esy toolchain by itself.
