### ISSUE TITLE
Merging vscode-merlin and vscode-ocaml-platform

### ISSUE THREAD

**Issue by prometheansacrifice** [ocamllabs/vscode-ocaml-platform#16]
Hi everyone,

For sometime now, we have been working on (and using) [vscode-merlin](https://github.com/arrowresearch/vscode-merlin) - a vscode
extension that talks to a language server based on
merlin. This has been in the works since merlin lsp was still hosted
at the merlin repo 🙂 We think a lot of our goals overlap with yours.

### `vscode-merlin`'s goals
The goal is to provide a single plugin supporting `opam`, `esy` and `npm/bsb`
workflow. We hope to address some of the concerns regarding the
divide in the ecosystems. Hopefully, this extension brings both the
npm/bucklescript community and Reason/OCaml community that compiles
natively together.

This extension intends to provide first class support for all major
native development tools and relevant file extensions - including and
not limited to syntactic support for dune files, opam files, *.mly,
*.mll. It intends to leverage all features opam and esy that can
assist the respective workflows.

### Bucklescript support
We started working on this extension to gain benefits of
recoverable/incremental parsing that merlin provides for bucklescript
projects. After the merger, we intend to continue to involving
ourselves in this regard. Quick overview of how we setup merlin for
bucklescript.

Providing merlin support for bucklescript projects (supporting both
Reason and OCaml syntaxes) can get tricky - users have unpredictable
environment state and equally unpredictable tools available on their
path. We find that `esy` provides a convenient way out - it provides a
sandbox that ensures the correct version of merlin (compiled with
4.06) is used and that it can find the corresponding ocamlmerlin-reason
binary on it’s path in silo. So we turn every bucklescript projects into
a hidden esy project by dropping a `esy.json` in the `.vscode/` folder
(the UX around this is up for suggestions and feedback). We take certain
[heuristics/practices](https://github.com/arrowresearch/vscode-merlin/blob/master/src/ProjectType.re#L45-L67) into consideration before we do this - currently this is an automatic
setup behind the scenes. We can provide a more manual/intervening
workflow with ideas like a project status view that vscode provides. 

An important concern this raised is the time to get started - the
toolchain (compiler+merlin+refmt+ocamlformat) needs to be compiled
from source and this can take a while. Particularly on Windows. To
address this, we build the toolchain for the three platforms on the
CI once. Since esy's artifacts are relocatable - we download the cache
(about 130mb) and warm up the local cache. This has worked very well
for us. A preliminary setup (with manual intervention) has been tested
(did so myself) on a Windows machine too.

This makes two things necessary for the plugin

1. It relies on esy and will prompt the user to install esy. This can
   be avoided for pure opam workflows of course.
2. It needs Azure Pipelines since it provides a convenient way to
   publish and restore relocatable assets.
   
   
This has worked very well for us so far and hope the community - both
OCaml and Reason using either opam/esy/npm workflows - likes it.

One last thing left would be Windows support for Opam - we're open for
support this workflow too.

### Closing comments
As I understand, merging the projects would
affect the e2e tests - at vscode-merlin we have run e2e tests on all
three platform to ensure the extensions operations and caching
mechanism work on all three OSes. This will affect @imbsky 's re-write
of tests to TS. We'll have to use Azure Pipelines for CI - the setup
at vscode-merlin sees about 20 mins of well cached runs and a tried and
tested relocatable artifacts creation for all three platforms.

As always, I would love your thoughts :)

**Comment by rgrinberg** [comment]
> It relies on esy and will prompt the user to install esy. This can
be avoided for pure opam workflows of course.

That's fine. Let's make sure that this only pops up when esy projects are discovered. For bucklescript, I have no opinion as well and you're free to handle it however you see fit.

> It needs Azure Pipelines since it provides a convenient way to
publish and restore relocatable assets.

I'm OK with this but we'd also like the CI to work in other environments.

**Comment by prometheansacrifice** [comment]
> Let's make sure that this only pops up when esy projects are discovered

I understand and agree.

> I'm OK with this but we'd also like the CI to work in other environments.

Other environments as in other CI services/hosted setups? Sure. It would need some tweaking and testing, but doable. Right now, this setup is more or less identical to what other esy based projects are currently using (and what has worked for them)

**Comment by rgrinberg** [comment]
> Other environments as in other CI services/hosted setups? Sure. It would need some tweaking and testing, but doable.

Yup.
