### ISSUE TITLE
Update v1.21.0 broke

### ISSUE THREAD

**Issue by jonahbeckford** [ocamllabs/vscode-ocaml-platform#1647]
Getting the error message:

```
An error occurred starting the language server `ocamllsp`. Sandbox initialization failed: `ocaml-lsp-server` is not installed in the current sandbox.
```

I downgraded to `v1.20.0` and it works again. I am changing _nothing_ about my opam switch ... the only thing changing is the version of the vscode extension.

(Thought: Is there a new max timeout when waiting for `ocamllsp --version` to respond? On my machine it takes about two seconds)

### Logs for v1.21.0 (broken)

```

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe var --global root

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe var --global root
Y:\user\beckf\packages\opam

Y:\user\beckf\packages\opam

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe --version
2.2.0

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe var --global root
Y:\user\beckf\packages\opam

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe switch show --root Y:\user\beckf\packages\opam

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe switch list -s --root Y:\user\beckf\packages\opam
Y:\source\MlFront_Archive
Y:\source\capnp-ocaml
Y:\source\codept
Y:\source\dkml-component-opam
Y:\source\dkml-dune-dsl
Y:\source\dkml-install-api
Y:\source\dkml-workflows
Y:\source\dksdk-coder\ext\MlFront
Y:\source\dksdk-ffi-ocaml
Y:\source\dune
Y:\source\ocaml-ctypes
Y:\source\ocaml-tar
Y:\source\ocurl
Y:\source\tsdl
Y:\source\uuseg
playground

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe --version
2.2.0

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe var --global root
Y:\user\beckf\packages\opam

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe switch show --root Y:\user\beckf\packages\opam

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe exec --switch=Y:\source\capnp-ocaml --set-switch --root Y:\user\beckf\packages\opam -- ocamlc --version
4.14.2

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe exec --switch=Y:\source\capnp-ocaml --set-switch --root Y:\user\beckf\packages\opam -- ocamllsp --version
```

Notice that we see no response for `ocamllsp --version`

### Logs for v1.20.0 (good)

```
$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe --version
$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe --version
2.2.0

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe var --global root
2.2.0
Y:\user\beckf\packages\opam


$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe var --global root
Y:\user\beckf\packages\opam

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe switch list -s --root Y:\user\beckf\packages\opam
Y:\source\MlFront_Archive
Y:\source\capnp-ocaml
Y:\source\codept
Y:\source\dkml-component-opam
Y:\source\dkml-dune-dsl
Y:\source\dkml-install-api
Y:\source\dkml-workflows
Y:\source\dksdk-coder\ext\MlFront
Y:\source\dksdk-ffi-ocaml
Y:\source\dune
Y:\source\ocaml-ctypes
Y:\source\ocaml-tar
Y:\source\ocurl
Y:\source\tsdl
Y:\source\uuseg
playground

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe exec --switch=y:\source\capnp-ocaml --set-switch --root Y:\user\beckf\packages\opam -- ocamlc --version
4.14.2

$ C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\bin\opam.exe exec --switch=y:\source\capnp-ocaml --set-switch --root Y:\user\beckf\packages\opam -- ocamllsp --version
1.17.0
```

**Comment by gridbugs** [comment]
I just tried setting up vscode on a fresh install of ubuntu, using opam to install ocaml-lsp-server, and the default configuration of vscode-ocaml-platform 1.21.0 worked as expected. Next I'll try to reproduce this on windows.

**Comment by gridbugs** [comment]
Ok I've set up vscode and opam on a windows machine and I can reproduce this error.

**Comment by gridbugs** [comment]
When the plugin initializes ocamllsp it runs `ocamllsp --version`. One of the changes between 1.20.0 and 1.21.0 is that `ocamllsp --version` is run from the project's directory rather than the user's home directory. For some reason on windows, the `ocamllsp` executable can't be found when the command is run from the project's directory.

**Comment by gridbugs** [comment]
[Here](https://github.com/ocamllabs/vscode-ocaml-platform/blob/7df6bb8ce35447da67de585054a6e69aa5a6fe06/src/extension_instance.ml#L146)'s where we get the path to the current project. On windows this results in `cwd` being set to something like `/c:/Users/path/to/project` which looks different from other paths I see printed in the logs on windows (they all look like `C:\\path\\to\\project`). So I'm guessing that we need to windowsify the cwd on windows. This is what I'll try next.

**Comment by nojb** [comment]
https://github.com/ocamllabs/vscode-ocaml-platform/blob/7df6bb8ce35447da67de585054a6e69aa5a6fe06/src/extension_instance.ml#L146

Shouldn't `Uri.fsPath` be used instead of `Uri.path`?

**Comment by gridbugs** [comment]
Yep that fixed it. Fix is here: https://github.com/ocamllabs/vscode-ocaml-platform/pull/1650

**Comment by smorimoto** [comment]
https://github.com/ocamllabs/vscode-ocaml-platform/releases/tag/1.22.0
