### ISSUE TITLE
Problems in a file are not removed when the file is deleted/renamed 

### ISSUE THREAD

**Issue by yannl35133** [ocamllabs/vscode-ocaml-platform#166]
When you have a file containing problems, and rename it (or move, delete it), VSCode still shows its problems.

How to reproduce :
- Create a .ml file containing an error (e.g. 
```
a
```
as `a` won't be defined)
- Rename the file
- See how the problem is still here

In the mean time, reloading VSCode solves this, so this is no big issue.

**Comment by rgrinberg** [comment]
Try updating to the latest ocamllsp. @ulugbekna fixed this.

**Comment by yannl35133** [comment]
Solved indeed. I should maybe go back on my bug reports and check them again
