### ISSUE TITLE
OCaml keywords are not suggested

### ISSUE THREAD

**Issue by yannl35133** [ocamllabs/vscode-ocaml-platform#183]
I suggest OCaml keywords be included in suggestions.
This is mostly an issue when you type `in` and hit Return, as most of the time another value beginning by `in` will be inserted instead, and this is annoying

**Comment by mnxn** [comment]
I've noticed this too. 

However, I believe this should be handled by https://github.com/ocaml/ocaml-lsp as the language server protocol allows keywords in completion entries. That way, keyword completion will be present in other editors that use ocaml-lsp too.

**Comment by rgrinberg** [comment]
@yannl35133 try pinning ocamllsp. I've added experimental support for keyword completion.

**Comment by ian-barnes** [comment]
I find this annoying too, happens every single time I type `let foo = ... in`. It happens with the (Merlin-based?) OCaml and Reason IDE extension also. Part of why I switched was I hoped it wouldn't happen here.

@rgrinberg Can you be a little more specific with your instructions there? `opam pin add ocaml-lsp ...?` Sorry, I'm not yet an Opam wizard.

**Comment by ulugbekna** [comment]
@ian-barnes The new ocaml-lsp v1.2.0 is published already with keyword completion. `opam update && opam upgrade ocaml-lsp-server` (Didn't work for me somehow though)

You can pin ocaml-lsp package by doing `opam pin add ocaml-lsp-server https://GitHub.com/OCaml/ocaml-lsp.git#master`.

**Comment by ian-barnes** [comment]
Cool, thanks!

**Comment by rgrinberg** [comment]
> and same with pinning to master. That's weird. Does 1.2.0 depend on Ocaml 4.11 or something?

It does not.

If there are installation problems with ocamllsp, please ask on discuss. 1.2.0 was merged to opam quite recently so you might need to do `$ opam update` again and confirm that it's there with `$ opam info ocaml-lsp-server`.
