### ISSUE TITLE
Use reason-node instead

### ISSUE THREAD

**Issue by smorimoto** [ocamllabs/vscode-ocaml-platform#195]
What do you think of using a community project like this instead of writing our own bindings?
https://github.com/sikanhe/reason-node

**Comment by rgrinberg** [comment]
It looks like a nice project. If writing our own bindings will start to become burdensome, it would definitely be worth checking out. In the longer term, I think we'll benefit by switching to jsoo so using bucklescript specific bindings is problematic as well.

**Comment by smorimoto** [comment]
We are considering switching to jsoo now, so close it once.
