### ISSUE TITLE
Syntax highlighting for cppo directives

### ISSUE THREAD

**Issue by rgrinberg** [ocamllabs/vscode-ocaml-platform#199]
Such directives should be recognized in `.cppo.ml{,i}` files.

**Comment by mnxn** [comment]
From the [Cppo project page](https://github.com/ocaml-community/cppo), my understanding is that directives can appear in `.ml`/`.mli` files without the `.cppo`. Shouldn't this just be implemented as an update to the normal OCaml syntax?

**Comment by rgrinberg** [comment]
That's true. However, by convention, users should use a `.cppo.{ml,mli}` suffix. Unfortunately, in the wild, this convention isn't widely enforced.
