### ISSUE TITLE
config ocamllsp in Windows WSL

### ISSUE THREAD

**Issue by arbipher** [ocamllabs/vscode-ocaml-platform#201]
I cannot specify `ocaml.lsp.path` in WSL
```
"ocaml.lsp.path": "wsl -d Ubuntu-20.04 bash -c ocamllsp"
```
I am not sure whether I don't figure out how to do it or currently it's not supported

For comparasion, I could use OCaml tools inside WSL for the another vscode extention OCaml and Reason IDE
```
"reason.path.ocamlfind": "bash -ic ocamlfind",
"reason.path.ocamlmerlin": "bash -ic ocamlmerlin",
```

**Comment by rgrinberg** [comment]
Support for this option was removed. It's now possible to set the toolchain to an opam/esy sandbox. Is this not enough for WSL?

**Comment by arbipher** [comment]
I don't know..

maybe I haven't figure out how to set the sandbox correctly, like

```
"ocaml.sandbox": {
        "root": "wsl -d Ubuntu-20.04 bash -ic",
        "kind": "opam"
    }
```

Is there any sample for `opam` like [this](https://github.com/ocamllabs/vscode-ocaml-platform/blob/2524257cc6414de1fa96e3537ee810042e943be1/fixtures/sample-esy/.vscode/settings.json) for esy?

**Comment by mnxn** [comment]
Isn't [Remote WSL](https://code.visualstudio.com/docs/remote/wsl) the intended way to use WSL in vscode? Then you can use the normal opam commands.

**Comment by arbipher** [comment]
@mnxn I don't think so.
(I also tested your extension with Remote WSL and it works, but Remote WSL bring other problems not related here so I don't want to use it)

I hope it could work transparently as if it doesn't matter whether it's installed inside WSL. OCaml and Reason IDE support this as mentioned in my issue post.

**Comment by mnxn** [comment]
Perhaps we could add a feature for configuring a custom toolchain/sandbox. 

My workflow is currently launching vscode from cygwin in order to use the global toolchain. A custom toolchain configuration could allow using `ocaml-env` outside of cygwin to start ocaml-lsp. 

It would also allow you to use WSL like you tried in your original issue.

**Comment by rgrinberg** [comment]
@mnxn that sounds like a reasonable proposal.
