### ISSUE TITLE
Display sandbox for current project

### ISSUE THREAD

**Issue by Khady** [ocamllabs/vscode-ocaml-platform#216]
Sometimes the extension is working when I open a project but I don't know why and which sandbox it is currently using. It happened to me on a project without any .vscode/settings.json file. It would be convenient to either see in the status bar which sandbox is currently used or have a command to get this information.

**Comment by rgrinberg** [comment]
Sounds like a good idea. The [status bar API](https://code.visualstudio.com/api/references/vscode-api#StatusBarItem) is pretty straightforward so this shouldn't pose much problems. @mnxn do you want to take this on?

**Comment by mnxn** [comment]
Sure. I can work on it tomorrow.
