### ISSUE TITLE
Launch terminal in a toolchain

### ISSUE THREAD

**Issue by rgrinberg** [ocamllabs/vscode-ocaml-platform#219]
vscode has a nice API for creating terminals. It would be nice to introduce a command that lunches a terminal in a toolchain. See this page https://code.visualstudio.com/api/references/vscode-api#Terminal search for the `createTerminal` function

**Comment by rgrinberg** [comment]
@mnxn want to tackle this one as well?

**Comment by mnxn** [comment]
Sure.
