### ISSUE TITLE
Using local ocamlformat with esy

### ISSUE THREAD

**Issue by amiralies** [ocamllabs/vscode-ocaml-platform#222]
Is this possible to use locally installed ocamlformat using esy?

**Comment by rgrinberg** [comment]
It should be. Are you using the selecting the sandbox where ocamlformat is installed?

**Comment by amiralies** [comment]
Ok it works now, didn't recognized sanbox automatically though.
I'm closing this.
thank you.

**Comment by rgrinberg** [comment]
Did you have an esy.json in your project? @rusty-key I'm wondering if we should suggest esy a little more aggressively in such cases.

**Comment by amiralies** [comment]
No I'm using package json

**Comment by rgrinberg** [comment]
Is there anything in that package.json that could be used to hint us that it can be used with esy?

**Comment by amiralies** [comment]
`esy` field?
