### ISSUE TITLE
Files are formatted despite being in .ocamlformat-ignore

### ISSUE THREAD

**Issue by Khady** [ocamllabs/vscode-ocaml-platform#223]
It is not clear if the problem is because of the extension or ocamllsp. But I don't have way to trigger the lsp server without using vscode. And I don't know how to make ocamllsp log the commands it is running.

I have a file e.ml that is in a .ocamlformat-ignore. When I go to the folder where the file is and run ocamlformat by hand, the file is left untouched. When I edit the same file and ask vscode to format the file, the file is not left untouched.

I've created a repository to reproduce the issue https://github.com/Khady/vscode-ocamlplatform-ocamlformat-bug

To reproduce, open the repository with vscode and the latest published version of the extension. Then open e.ml. And use ctrl+shift+i to format the file.

version of the extension: 0.6.1
version of ocamllsp: c4e668dd

Let me know if I should move the issue to the ocaml-lsp repo instead.

**Comment by mnxn** [comment]
Strangely, I can't get `.ocamlformat-ignore` to work (on Windows) in any scenario: command line or through vscode. This might be a problem with ocamlformat itself, but I need to investigate more before making that conclusion. 

> When I go to the folder where the file is and run ocamlformat by hand, the file is left untouched.

What command are you using to run ocamlformat?

**Comment by mnxn** [comment]
I see from the linked repo that you're using `ocamlformat e.ml` to format the file. 

The reason the file is untouched is because the default behavior of ocamlformat is to print the formatted code to stdout, not because of the `.ocamlformat-ignore` file. ocamlformat will only overwrite the file if you use the `--inplace` flag 

It looks like ocamlformat isn't respecting `.ocamlformat-ignore` in any case, so this is likely a bug with ocamlformat, not ocaml-lsp or this extension. It would be great if somebody else could verify this, especially on a non-windows OS.

**Comment by Khady** [comment]
I'm running vscode and ocamlformat on linux.

> The reason the file is untouched is because the default behavior of ocamlformat is to print the formatted code to stdout, not because of the .ocamlformat-ignore file. ocamlformat will only overwrite the file if you use the --inplace flag

What I meant by untouched is that the output is the same as the input. If I remove the .ocamlformat-ignore file this isn't the case.

```
$ rm .ocamlformat-ignore
$ ocamlformat e.ml 
let () = print_endline "hello world"
$ cat e.ml
let () = 
  print_endline "hello world"
```

So ocamlformat is respecting the ocamlformat-ignore file. And dune is able to call ocamlformat the proper way. But I think that ocamllsp doesn't do it the proper way.

**Comment by mnxn** [comment]
Ok I believe I understand now. Windows might have some other problems that prevent me from testing properly.

What is the output when you do `cat e.ml | ocamlformat --impl -` when the `.ocamlformat-ignore` is present?

**Comment by Khady** [comment]
```
$ cat e.ml 
let () = 
  print_endline "hello world"
$ cat e.ml | ocamlformat --impl -
let () = print_endline "hello world"
$ cat e.ml | ocamlformat --impl --name=e.ml -
let () = 
  print_endline "hello world"
```

**Comment by Khady** [comment]
https://github.com/ocaml/ocaml-lsp/blob/23bcd4fb65666be2b9ded59b2166b1daf09a9ab0/ocaml-lsp-server/src/fmt.ml#L61

And ocaml-lsp seems to be passing the `--name` parameter, so I don't have a quick guess of what could be wrong.

**Comment by mnxn** [comment]
Thank you for providing the information. Unfortunately it seems that my debugging capabilities for this issue are limited.

@rgrinberg: when you have the chance, can you take a look at this please?

**Comment by Khady** [comment]
I tried to use different versions of ocamlformat and ocamllsp and now I can't reproduce the problem anymore. So I guess I had a stuck version of ocamllsp somewhere and opam [didn't reported the right hash version](https://github.com/ocaml/opam/issues/3567). Sorry for the noise.
