### ISSUE TITLE
v0.7.0 tag not present in this repo but release present on VStudio Marketplace

### ISSUE THREAD

**Issue by sidkshatriya** [ocamllabs/vscode-ocaml-platform#250]
When I go to https://marketplace.visualstudio.com/items?itemName=ocamllabs.ocaml-platform I can see that the latest available version of the ocaml plugin is 0.7.0 . It is also listed as such in the changelog.

However, interestingly on this git repo there is no v0.7.0 tag or release. I only see v0.6.1 as the latest one. How come this is the case? How can I see what commit 0.7.0 corresponds to?

(Thanks for this great plugin BTW!)

**Comment by mnxn** [comment]
Thank you for notifying us. I pushed the tag and made a Github release: https://github.com/ocamllabs/vscode-ocaml-platform/releases/tag/v0.7.0
