### ISSUE TITLE
How to use the global sandbox?

### ISSUE THREAD

**Issue by TyOverby** [ocamllabs/vscode-ocaml-platform#251]
I have `{ "kind": "global" }` as the configuration for this plugin, but this appears to break ocamllsp.  I'm in a workspace that is not managed by opam or by esy, and although I have all the `.cmi`, and `.merlin` files built and on-disk, the errors reported by ocamllsp are all things like `cannot find library Core_kernel`.

Am I using "global" incorrectly?

**Comment by rgrinberg** [comment]
Seems like you're using it correctly. You'll have to give us a little more information about your setup. 

* How do you open vscode? Are you using `code .` inside your environment?
* Is vscode using the correct ocamllsp binary? You can find that out by doing `$ which ocamllsp` in a terminal in vscode.

**Comment by tmattio** [comment]
I don't think we can do much without more information.
Closing this for now, but feel free to re-open with more details.
