### ISSUE TITLE
Support for autocompleting record fields when the source of the record is in a different module

### ISSUE THREAD

**Issue by jfrolich** [ocamllabs/vscode-ocaml-platform#256]
This works in OCaml, but it doesn't work in Reason. I think it, therefore, has to do with the reason syntax JSON file.

See: https://github.com/ocaml/merlin/issues/1140#issuecomment-643771605

@imbsky @rgrinberg

**Comment by mnxn** [comment]
The JSON syntax files in this repository are only used for syntax highlighting so they are unlikely to be the culprit. 

I believe this is a problem in either [ocaml/merlin](https://github.com/ocaml/merlin) or [ocaml/ocaml-lsp](https://github.com/ocaml/ocaml-lsp/).

**Comment by jfrolich** [comment]
On discord @rgrinberg expressed that his guess is, the problem is in https://github.com/let-def/merlin-extend.

**Comment by rgrinberg** [comment]
Actually, it's more likely that the issue is with `merlin-extend` reason plugin itself. That resides somewhere in the reason repository I think.

**Comment by jfrolich** [comment]
https://github.com/facebook/reason/blob/master/src/reason-merlin/ocamlmerlin_reason.cppo.ml << this file?

**Comment by imbsky** [comment]
I think this issue has no relation with this repository.

**Comment by jfrolich** [comment]
I opened an issue on the Reason repo. Can we leave this open until we know for sure it's related to `reason-merlin`?

**Comment by imbsky** [comment]
Sure.

**Comment by jfrolich** [comment]
This started to work for me again (or I might have completely missed it before). The problem is that the field suggestions are all the way at the very bottom of the list (after all possible types and modules in the project etc.). I guess that is something that can be fixed in the plugin?

**Comment by jfrolich** [comment]
Actually it still doesn't work in most cases.

**Comment by rgrinberg** [comment]
Is this still a problem? It seems to be a problem only with the reason frontend, which isn't maintained in this repository.

**Comment by jfrolich** [comment]
Yes. I seems to be a problem in `reason-merlin`. You can close this.
