### ISSUE TITLE
Add debounce config option

### ISSUE THREAD

**Issue by rgrinberg** [ocamllabs/vscode-ocaml-platform#273]
https://github.com/ocaml/ocaml-lsp/pull/181/ adds debouncing support. The next step is to make this support configurable. We should add a float valued option `ocaml.server.debounce` to do this.

**Comment by mnxn** [comment]
Does this need any logic behind it, or is it the same situation as `ocaml.trace.server`?

**Comment by rgrinberg** [comment]
I’m not entirely sure. The server should be able to ask the client for this value. However, the server doesn’t know if the user changed the value on the client side.

Perhaps we just bounce the server if the user changes the value on the client side?

**Comment by rgrinberg** [comment]
Let's postpone this until someone is unhappy with the current debounce config.

**Comment by mnxn** [comment]
> Let's postpone this until someone is unhappy with the current debounce config.

Should this issue and the associated PR be closed until then?

**Comment by rgrinberg** [comment]
No harm in keeping it open I think. Maybe someone else will be interested in working on it?

**Comment by tmattio** [comment]
It doesn't seem like there's much interest in this, so I think we can close it until someone manifests an interest in having it.
