### ISSUE TITLE
Add support for ".res" and ".resi"

### ISSUE THREAD

**Issue by smorimoto** [ocamllabs/vscode-ocaml-platform#275]
https://reasonml.org/blog/bucklescript-8-1-new-syntax

**Comment by mnxn** [comment]
The syntax highlighting should probably wait until there is language server support for those files.
When that does happen, I expect that the existing Reason grammar can be partially reused.

**Comment by TheSpyder** [comment]
They're calling it "bucklescript" grammar, at least for now, [in reason-language-server](https://github.com/jaredly/reason-language-server/commit/5999a71e1b4ef7dd704c4714d72f5a72e3267b04)

**Comment by jfrolich** [comment]
Highlighting grammar is already in RLS so this can probably be reused?

**Comment by rgrinberg** [comment]
@jfrolich could you send a PR for this please?

**Comment by yawaramin** [comment]
Maybe worth holding off for a bit? There is discussion about adding enhanced support into [RLS](https://marketplace.visualstudio.com/items?itemName=jaredly.reason-vscode) for BuckleScript New Syntax and off-loading that maintenance burden from OLS: https://reasonml.chat/t/bucklescript-8-1-new-syntax-new-blog-post-about-bucklescripts-new-syntax-and-its-future-support-commitments/2414/8?u=yawaramin

**Comment by jfrolich** [comment]
Yes the tricky part is supporting merlin.

**Comment by smorimoto** [comment]
It seems that they are going to create their own extension.
https://github.com/rescript-lang/rescript-vscode

**Comment by mnxn** [comment]
ReScript editor support falls outside of the "OCaml Platform" scope at this time.

**Comment by smorimoto** [comment]
Please be careful not to misunderstand. We do not plan to drop BuckleScript and Reason support entirely immediately, but (as @mnxn said) it has Tier 1 support for OCaml, and BuckleScript is Tier 2.

**Comment by smorimoto** [comment]
FYI: @chenglou

**Comment by chenglou** [comment]
Sounds good, thanks for the notice! =)
