### ISSUE TITLE
automatic install of ocaml-lsp

### ISSUE THREAD

**Issue by giltho** [ocamllabs/vscode-ocaml-platform#294]
See https://github.com/ocaml/ocaml-lsp/issues/227, it would be great if the extension could install ocaml-lsp automatically.
Since the extension already detects the type of sandbox, it would be very simple to install the server using either `opam install` or `esy add`.

**Comment by rgrinberg** [comment]
On the opam side, we should consider using https://github.com/avsm/opam-tools. This is supposed to simplify fetching things like lsp, ocamlformat, etc.

**Comment by mnxn** [comment]
I'm unfortunately busier than I expected at the moment, so I will not be able to work on this right now.

Anybody else is free to take over if they wish.
