### ISSUE TITLE
auto-detect switch; support relative path

### ISSUE THREAD

**Issue by vogler** [ocamllabs/vscode-ocaml-platform#296]
Is there something speaking against automatically selecting the opam switch by default?
Taking the result of `opam switch show` for the currently opened vscode workspace should be the right choice 99% of the time and if it's not, it's shown in the status bar and easy to change.

Another issue: I wanted to share my `.vscode/settings.json` but `ocaml.sandbox.switch` does not seem to support relative paths.

**Comment by mnxn** [comment]
Using `opam switch show` for toolchain selection can certainly be implemented. 

I think that the sandbox configuration should be revisited to make it easier to share. That would include relative paths and possibly a separate file like how `c_cpp_properties.json` is used by the C/C++ extension .

**Comment by mnxn** [comment]
Regarding your second point, configuration files have been made a bit more portable with #424. The extension will now use workspace folder placeholder variables by default.
