### ISSUE TITLE
feature request: show the generated code from PPX

### ISSUE THREAD

**Issue by EduardoRFS** [ocamllabs/vscode-ocaml-platform#300]
This is the only feature that I miss from RLS, where by calling "show the fully ppexed version" it opens a new tab showing the Reason / OCaml code. Not sure how they implemented but probably just calling `refmt --parse=binary` on `X.re.pp.ml`.

**Comment by Khady** [comment]
https://gist.github.com/Khady/e7b197e60a5065651815bc7b19c07a24

there's a command in merlin to do that. It's just a matter of exposing it through the lsp interface (adding a custom command?)

Actually it's possible to do something slightly better, to hide the [@merlin] annotations. But I would say that it is not critical.

**Comment by tmattio** [comment]
This has been implemented in 37493b82ba9eea77abc0ee2c9c25df9eee6ab75f

**Comment by EduardoRFS** [comment]
@tmattio THANK YOU SO MUCH.
