### ISSUE TITLE
Feature request: show type annotations on the same line

### ISSUE THREAD

**Issue by ducaale** [ocamllabs/vscode-ocaml-platform#313]
Ionide-vscode for fsharp can show the types annotations on the same line as a comment. I would love to have the same when editing ocaml code.

### ionide-vscode-fsharp
<img width="589" alt="Annotation 2020-08-08 233440" src="https://user-images.githubusercontent.com/16341131/89720992-28d9aa80-d9d0-11ea-8477-537aa07e2088.png">

### vscode-ocaml-platform
<img width="410" alt="Annotation 2020-08-08 234232" src="https://user-images.githubusercontent.com/16341131/89721063-e5cc0700-d9d0-11ea-851a-858915df5cb6.png">

**Comment by lindig** [comment]
I am not sure it is related: but is there a way to capture (copy) the inferred type such that I could use it to enlarge an already existing signature?

**Comment by lindig** [comment]
Ignore my comment. The feature is already somewhat supported but it's not obvious: when viewing the MLI file the light bulb icon offers to insert the inferred signature. The downside is that this inserts much more than typically asked for but at least it offers a way to enlarge an existing interface.

**Comment by basus** [comment]
Is there some way to turn off the type annotations? I find them visually cluttering and would rather see the types on hovering over identifiers.

**Comment by mnxn** [comment]
> Is there some way to turn off the type annotations? I find them visually cluttering and would rather see the types on hovering over identifiers.

Take a look at https://github.com/ocamllabs/vscode-ocaml-platform/issues/614#issuecomment-837485091

**Comment by smorimoto** [comment]
This will disable that only for OCaml files.

```json
{
  "[ocaml]": {
    "editor.codeLens": false
  }
}
```

**Comment by tmattio** [comment]
I'm not sure what's the difference between having the type annotations on the same line or at the top of the expression. It seems to be a personal preference, with which other users might not agree with, so without more arguments in favor of it, I'll close this for now.
