### ISSUE TITLE
Auto-selecting opam switch doesn't work with opam switch link

### ISSUE THREAD

**Issue by hcarty** [ocamllabs/vscode-ocaml-platform#321]
When I'm in a directory with a local opam switch, vscode + vscode-ocaml-platform detects it automatically.  However, if I `opam switch link path/to/directory/with/local/switch/` in another path the switch is not detected automatically.

I can manually select the intended local switch but it would be nice if this could be detected automatically, using the information `opam switch link` leaves behind.

**Comment by rgrinberg** [comment]
> When I'm in a directory with a local opam switch, vscode + vscode-ocaml-platform detects it automatically

As far as I know, there's no such functionality. However, we've discussed adding it.

**Comment by hcarty** [comment]
Ah, I may just be seeing something cached/saved locally then?

**Comment by rgrinberg** [comment]
Currently, the only way to save the current switch configuration is to save in the vscode workspace. See if you've configurated the toolchain variable in that file.

**Comment by mnxn** [comment]
If I understand this correctly, implementing "auto-detect switch" from #296 will address this if the linked switch appears in `opam switch show`.
