### ISSUE TITLE
hide dune prefix in type annotations

### ISSUE THREAD

**Issue by etanter** [ocamllabs/vscode-ocaml-platform#341]
Hi,
I'm 100% new to VSCode (let alone VSCode-OCaml), so sorry if that's trivial. 
For some reason, all the type annotations that are inferred have some dune-related prefix:
![image](https://user-images.githubusercontent.com/1315554/91608506-b101fe80-e943-11ea-819e-c0998a00c766.png)
At some point, I had the same problem in the hover type info, but after a server restart, it disappeared and looks fine:
<img width="206" alt="Screen Shot 2020-08-28 at 3 34 22 PM" src="https://user-images.githubusercontent.com/1315554/91608656-f4f50380-e943-11ea-937c-eadfcb1609be.png">

How can I hide the dune-related prefixes in the inferred type annotations?

thanks!

**Comment by rgrinberg** [comment]
Can you post the `.merlin` file generated in the directory where this source file lives?

**Comment by etanter** [comment]
```
» more .merlin                                                                   [15:49:04]
EXCLUDE_QUERY_DIR
B /Users/etanter/.opam/4.11.0/lib/alcotest
B /Users/etanter/.opam/4.11.0/lib/alcotest/engine
B /Users/etanter/.opam/4.11.0/lib/astring
B /Users/etanter/.opam/4.11.0/lib/bytes
B /Users/etanter/.opam/4.11.0/lib/cmdliner
B /Users/etanter/.opam/4.11.0/lib/containers
B /Users/etanter/.opam/4.11.0/lib/containers/monomorphic
B /Users/etanter/.opam/4.11.0/lib/containers/unix
B /Users/etanter/.opam/4.11.0/lib/fmt
B /Users/etanter/.opam/4.11.0/lib/ocaml
B /Users/etanter/.opam/4.11.0/lib/re
B /Users/etanter/.opam/4.11.0/lib/seq
B /Users/etanter/.opam/4.11.0/lib/stdlib-shims
B /Users/etanter/.opam/4.11.0/lib/uchar
B /Users/etanter/.opam/4.11.0/lib/uuidm
B /Users/etanter/.opam/4.11.0/lib/uutf
B ../_build/default/TestLib/.testLib.objs/byte
B ../_build/default/gc/.main_compile.eobjs/byte
S /Users/etanter/.opam/4.11.0/lib/alcotest
S /Users/etanter/.opam/4.11.0/lib/alcotest/engine
S /Users/etanter/.opam/4.11.0/lib/astring
S /Users/etanter/.opam/4.11.0/lib/bytes
S /Users/etanter/.opam/4.11.0/lib/cmdliner
S /Users/etanter/.opam/4.11.0/lib/containers
S /Users/etanter/.opam/4.11.0/lib/containers/monomorphic
S /Users/etanter/.opam/4.11.0/lib/containers/unix
S /Users/etanter/.opam/4.11.0/lib/fmt
S /Users/etanter/.opam/4.11.0/lib/ocaml
S /Users/etanter/.opam/4.11.0/lib/re
S /Users/etanter/.opam/4.11.0/lib/seq
S /Users/etanter/.opam/4.11.0/lib/stdlib-shims
S /Users/etanter/.opam/4.11.0/lib/uchar
S /Users/etanter/.opam/4.11.0/lib/uuidm
S /Users/etanter/.opam/4.11.0/lib/uutf
S ../TestLib
S .
FLG -open Dune__exe -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -warn-error -A
```

**Comment by rgrinberg** [comment]
No clue why the prefixes remain. The `FLG -open Dune__exe` and `-short-paths` is supposed to take care of this. Perhaps @voodoos knows?

**Comment by etanter** [comment]
meanwhile, is there a setting to hide these inferred annotations?

**Comment by rgrinberg** [comment]
You can disable code lenses for OCaml sources I suppose.

**Comment by etanter** [comment]
I couldn't find the ocaml-specific setting for that, only the global `editor.codeLens`. When turning it off, type annotations indeed disappear and the rest (type info when hovering, peeking defs, etc.) still works fine.
Not ideal, but ok meanwhile. Thanks!

**Comment by rgrinberg** [comment]
Perhaps this should work:
```
"[ocaml]": {
          "editor.codeLens": false
}
```
in your `settings.json`.

**Comment by etanter** [comment]
one more bit of info: the problem manifests for types that are brought in scope of the file through an `open Abc` directive (where `abc.ml` defines the corresponding types, and there's no `abc.mli` file). 

FYI I've tried deleting the build files and the `.merlin` file, no change

**Comment by etanter** [comment]
the problem also manifests in the "outline":
<img width="297" alt="Screen Shot 2020-08-28 at 7 50 47 PM" src="https://user-images.githubusercontent.com/1315554/91623030-c5f08900-e967-11ea-8681-6a1a5599acdc.png">

**Comment by voodoos** [comment]
I do not encounter this problem with OCaml 4.11.0, dune 2.7.0, latest vscodium and latest ocaml-lsp-server.

Dit you check that the OCaml Platform extension use the correct switch ?
<img width="397" alt="image" src="https://user-images.githubusercontent.com/5031221/91634951-c7b45e00-e9f4-11ea-8b76-d51a7db52626.png">

**Comment by etanter** [comment]
yes:
<img width="364" alt="Screen Shot 2020-08-29 at 6 42 09 AM" src="https://user-images.githubusercontent.com/1315554/91634998-c4a07a00-e9c2-11ea-81c3-5e36b8955aab.png">
dune version is `2.7.0`, vscode is just updated, and ocamllsp is `1.0.0-7-g0d8bd3b`.
In case it may matter, I'm on macOS (10.15)

**Comment by etanter** [comment]
Ok, here's a minimal setup that manifests the problem:
- `dune`:
```
(executable
 (name main)
 (modules lib main))
```
- `lib.ml`:
```
type test = A of int | B of string
```
- `main.ml`:
```
open Lib

let f (t : test) = 
  match t with 
  | A n -> string_of_int n
  | B s -> s

let () =
  print_endline (f @@ A 1)
```

see the type annotation for `f`:
<img width="217" alt="Screen Shot 2020-08-29 at 7 36 35 AM" src="https://user-images.githubusercontent.com/1315554/91635913-6081b400-e9ca-11ea-9988-5ed51095ff9a.png">

files: [Archive.zip](https://github.com/ocamllabs/vscode-ocaml-platform/files/5145151/Archive.zip)

**Comment by voodoos** [comment]
I was able to reproduce, thanks.
Code lens is indeed showing `Dune__exe` prefixes while hovering on `f` does not.
And merlin also gives the right answer:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/5031221/91636268-8c6b5c80-e9ff-11ea-87bd-808f22c2e6ca.png">

I don't know how CodeLens is implemented in OCaml LSP ?

**Comment by etanter** [comment]
I tried another organization of the code to see if that was happening as well:
- subfolder `tool`, with `lib.ml` as above, and `f.ml` which only has the function `f` defined. The `dune file` makes `tool` a library
- `main.ml` in the root, being the executable, using the `Tool` library. In `main.ml` I create an alias `let g = f`. 

Interestingly, the codelens in `main.ml` shows the proper type for `g` (`Tool.Lib.test → string`), while in the `f.ml` file, it shows up `Dune__exe.Lib.test → string` instead of `test → string`:

<img width="667" alt="Screen Shot 2020-08-29 at 8 23 22 AM" src="https://user-images.githubusercontent.com/1315554/91636735-e86abc80-e9d0-11ea-90f9-bfaa298b0aab.png">

note sure if that helps in any way to track the problem...

**Comment by rgrinberg** [comment]
> I don't know how CodeLens is implemented in OCaml LSP ?

It's just merlin's `Outline` query.

**Comment by etanter** [comment]
in the example above, do we agree that in `main.ml` it should display `test → string` for `g`, considering the prior `open Tool.Lib`?

**Comment by voodoos** [comment]
It is in fact an already known issue of Merlin: https://github.com/ocaml/merlin/issues/971

**Comment by etanter** [comment]
thanks for tracking down the problem to a Merlin bug. Hopefully it gets addressed there soon!

**Comment by etanter** [comment]
FYI, there's an approved PR that fixes the problem in Merlin https://github.com/ocaml/merlin/pull/1166

**Comment by rgrinberg** [comment]
Indeed. I will cherry pick it ocamllsp as soon as it is merged.
