### ISSUE TITLE
Unhelpful error on missing ocaml-lsp

### ISSUE THREAD

**Issue by ulugbekna** [ocamllabs/vscode-ocaml-platform#351]
Failing `opam exec` (because ocaml-lsp is missing in the opam switch) results in a message: "Toolchain initialisation failed: Command failed with . See output channel for more details".

Output:

```javascript
external command {
  "bin": "/usr/local/bin/opam",
  "args": [
    "exec",
    "--switch=/Users/ulugbekna/code/ocaml/ocaml-git",
    "--",
    "ocamllsp",
    "--version"
  ],
  "result": {
    "exitCode": 127,
    "stdout": "",
    "stderr": ""
  }
}
```

Somewhat related [opam/4131](https://github.com/ocaml/opam/issues/4131)

**Comment by mnxn** [comment]
Are you using an outdated version of opam? On 2.0.7, it tells me 
> Toolchain initialisation failed:  Command failed with [ERROR] Command not found 'ocamllsp'
. See output channel for more details

**Comment by ulugbekna** [comment]
Yes, you're right; I needed to upgrade opam. Either way, we could maybe offer the user to install ocaml-lsp, say, using a dialog box with an install button?

**Comment by smorimoto** [comment]
I think it's possible, but I've never had a good experience with such a dialog and I'm not very positive about it.

**Comment by tmattio** [comment]
Closing this in favor of #294 which tracks this exact feature
