### ISSUE TITLE
Handling missing ocamlformat

### ISSUE THREAD

**Issue by ulugbekna** [ocamllabs/vscode-ocaml-platform#353]
If ocamlformat is missing, the extension displays an error on every file save. What do you think of making this not an error but a box with, say, two buttons: [Install ocamlformat] [Don't show again].

![image](https://user-images.githubusercontent.com/16353531/92010682-60771080-ed4a-11ea-8c36-c4c97af91cbc.png)

Install ocamlformat in case of an opam switch should just `opam install ocamlformat`. Don't know about esy.

**Comment by mnxn** [comment]
The error message is sent from the language server:
https://github.com/ocaml/ocaml-lsp/blob/eabbc8a439ba30507292dd74e39d052a581a1cb8/ocaml-lsp-server/src/fmt.ml#L52
I don't think vscode-languageclient lets us change how the message is displayed.

If https://github.com/ocamllabs/vscode-ocaml-platform/issues/294 is implemented, it could also check for ocamlformat and let the user install it.
