### ISSUE TITLE
Installation on Windows works, but can't find language server

### ISSUE THREAD

**Issue by johnwhitington** [ocamllabs/vscode-ocaml-platform#357]
I installed OCaml and OPAM via the recommended https://fdopen.github.io/opam-repository-mingw/installation/

I installed ocaml-lsp using OPAM, which worked fine.

I installed the plugin in vscode, which appeared to work. However, when the plugin prompts and gives options for which OCaml installation to use "Select package manager", the OCaml versions don't show (unlike on OS X, where it shows "4.11.1" and you just pick it). 

How can I tell the ocaml-platform plugin where to find what it needs? Has anyone successfully used the ocaml-platform plugin on Windows?

I see there is an option "Input a custom command template", but I have no idea what to put in it.

Also, I get the additional error "setting sandbox is invalid, expected object, got null" upon first loading a .ml file.

**Comment by mnxn** [comment]
There are two ways you can use this extension on Windows right now:

1. Launch VSCode from cygwin. This will let you choose a global or opam sandbox.

2. Use a custom sandbox with [https://fdopen.github.io/opam-repository-mingw/ocaml-env/](https://fdopen.github.io/opam-repository-mingw/ocaml-env/). If it is on your path you can input `ocaml-env exec -- $prog $args` for the custom command template, or manually edit the `ocaml.sandbox` settings so it is
```json
"ocaml.sandbox": {
  "kind": "custom",
  "template": "ocaml-env exec -- $prog $args"
}
``` 

I have personally tried both options on Windows and the first seems to be more reliable.

**Comment by ulugbekna** [comment]
@mnxn seems like something worth documenting? I could submit a PR that directly quotes your response above.

**Comment by mnxn** [comment]
> @mnxn seems like something worth documenting? I could submit a PR that directly quotes your response above.

Sure, go ahead.

**Comment by johnwhitington** [comment]
> 1. Launch VSCode from cygwin. This will let you choose a global or opam sandbox.

Perfect. I still get the null sandbox error, but it doesn't seem to cause a problem.

**Comment by johnwhitington** [comment]
I get the sandbox error on OS X too, for reference.
