### ISSUE TITLE
global esy ocaml-lsp-server

### ISSUE THREAD

**Issue by EduardoRFS** [ocamllabs/vscode-ocaml-platform#361]
## Feature Request

It's a problem to need to add ocaml-lsp-server to every package that you will develop as it's a not ideal solution, that is not a problem when using opam, as you use a global switch and things works, but for esy that's not true as we have no global sandbox, ideally after installing the extension the user would receive a progress bar and in a couple of minutes the environment would be working for any project, maybe that could even be cached on a CI using something like pesy.

If the ocaml-lsp-server is already available on esy or opam then we skip it.

## How

When esy is installed, the extension itself would create a hidden json file with ocaml-lsp-server added

Read the esy lock, get the ocaml version and install it + ocaml-lsp-server on a internal esy package, that could also be used with opam switches and global installations but we need to look on details

## Why not a override?

esy allow us to extend a `package.json` with a json like, that would use a different lock version which would need to reinstall everything with the most recent version, using only the ocaml package prevents that

**Comment by mnxn** [comment]
I'm really not sure about creating a hidden project to get around the lack of a global sandbox for Esy. I feel that this is more of a limitation with Esy than it is with the extension.

Wouldn't having an automatic install with `esy add` be sufficient? There's an open issue for that with https://github.com/ocamllabs/vscode-ocaml-platform/issues/294.

**Comment by EduardoRFS** [comment]
@mnxn there is a couple advantages on this approach. But yeah `esy add` is an improvement it's still not a single click experience. While most of the other's language server just works after you installed the extension.

The actual problem is that we rely on global available binaries by default, calling it a limitation on esy is weird, since this isn't a desired feature.

And with opam is even worse because then you need to change your global environment just to use the extension, this proposed solution using esy "just works" after you installed the extension without any trade-off. You shouldn't need to change your global environment just to get the editor support

**Comment by rgrinberg** [comment]
If you want to work on this, feel free to go ahead. Given that it's a package manager specific feature I'm not very keen to spend time on this myself.

**Comment by smorimoto** [comment]
I think adding something like `esy global add` to esy side is more ideal than doing this on our side.

**Comment by rgrinberg** [comment]
I agree. If there's a simple solution on the esy side, we'd be glad to adopt it. Moreover, such a solution will be useful for non vscode users as well.
