### ISSUE TITLE
[Question] Where to install the latest version?

### ISSUE THREAD

**Issue by Kakadu** [ocamllabs/vscode-ocaml-platform#369]
I use version `0.2.0` from marketplace and got a few issues with highlighting. It would be great to test with the latest version but I can't find any guidlines how to do that. Can you either release a new version, or (even better) add instructions how to try a developer version of this plugin?

*** 

If it does matter, an issue with highlighting looks like that 
![image](https://user-images.githubusercontent.com/438226/93508531-26e7fd00-f927-11ea-8179-fefab4f77fb9.png)

https://gist.github.com/Kakadu/63ade50a6028d7ff115a335cb0b7946a

**Comment by mnxn** [comment]
The highlighting issues have been fixed a long time ago.

The current version of the extension is v1.1.2 and it is published on the VSCode marketplace.

For some reason it hasn't auto-updated for you. You should go to the extension page inside of VSCode and click the button to update

**Comment by rgrinberg** [comment]
Indeed, this is not a bug. This extension is updated like every other extension in vscode.
