### ISSUE TITLE
how does one specify the compiler version for the sandbox?

### ISSUE THREAD

**Issue by cdaringe** [ocamllabs/vscode-ocaml-platform#373]
# Problem

It's unclear how to manage the sandbox. Can i configure in my `settings.json` to use a global switch? How can I pin my sandbox to a specific version?

Thanks all :) Great work on the extension.

**Comment by mnxn** [comment]
If you want a specific version of the OCaml compiler or ocaml-lsp, that should be handled by the package manager you're using - either esy or opam.

If you have multiple opam switches, clicking on the status bar item or running the "Select a Sandbox" command will let you choose between them. The `global` sandbox will just use whatever `ocaml-lsp` binary is accessible on your PATH.

**Comment by cdaringe** [comment]
Thanks for writing back @mnxn. Example, I have `"ocaml": "~4.10.1"` in my esy `package.json`. Yet, even such, I find that the extension periodically launches `4.11.0`

```
❯ ps aux | grep lsp
cdaringe         86180   0.0  0.3  4333388  26540   ??  S    12:17AM   0:00.08 /Users/cdaringe/.config/yarn/global/node_modules/.bin/esy -P /Users/cdaringe/src/freshawair ocamllsp
cdaringe         65925   0.0  0.0  4450688   2940   ??  S    Thu12AM   0:27.65 ocamllsp
cdaringe         86876   0.0  0.0  4277496    672 s001  S+   12:25AM   0:00.00 grep lsp
cdaringe         86185   0.0  1.9  4473808 156688   ??  S    12:17AM   0:03.44 /Users/cdaringe/.opam/4.11.0/bin/ocamllsp
```

So I'm trying to figure out if i can _teach it_ somehow to never launch anything _but_ the esy sandbox.

**Comment by cdaringe** [comment]
I'm not sure the conditions of which it happens, because in my most recent launch--great, ya, it's running my esy sandbox--but something i'm doing in my workflow is fubaring it time and again

**Comment by rgrinberg** [comment]
>  it's running my esy sandbox--but something i'm doing in my workflow is fubaring it time and again

This could only happen if you haven't saved your sandbox settings. I'm closing this as I don't think there's a bug on our side.
