### ISSUE TITLE
settings.json::ocaml.sandbox.root written with absolute path vs relative path breaks project portability

### ISSUE THREAD

**Issue by cdaringe** [ocamllabs/vscode-ocaml-platform#374]
# Problem

Absolute paths in settings.json did not work with project on a different computer.

E.g.

```
{
  "ocaml.sandbox": {
    "kind": "esy",
    "root": "/Users/cdaringe/src/freshawair"
  }
}
```

# Context

The only difference between my two computers  is `/Users` and `/home`--pretty similar!--so it took me a few to figure out what was up :). I'm _pretty sure_ I didn't enter in the `root` field in settings.json, but I can't quite pin down where it gets written in this extension.

# Discussion

Perhahps the `"${workspaceFolder}"` placeholder var should be used instead when creating the sandbox path?

**Comment by cdaringe** [comment]
I could get into sending a patch if someone can help point me to the `root` field writer

**Comment by mnxn** [comment]
Esy project roots are walked and collected around here: https://github.com/ocamllabs/vscode-ocaml-platform/blob/e2cbe19a625467218c177a06e8879b95cd764994/src/esy.ml#L23

Related issue for opam: #296

**Comment by cdaringe** [comment]
I am AFK at the moment, but on my phone I found this little guy. I think he might be the culprit! https://github.com/ocamllabs/vscode-ocaml-platform/blob/e2cbe19a625467218c177a06e8879b95cd764994/src/Toolchain.ml#L102

**Comment by mnxn** [comment]
> 
> 
> I am AFK at the moment, but on my phone I found this little guy. I think he might be the culprit!
> 
> https://github.com/ocamllabs/vscode-ocaml-platform/blob/e2cbe19a625467218c177a06e8879b95cd764994/src/Toolchain.ml#L102

That's just where the path is serialized to JSON. You shouldn't do any extra logic there.

**Comment by ulugbekna** [comment]
Hi! If you can wait, I'm working on sandbox discovery already; I hope to to fix this issue as well

**Comment by cdaringe** [comment]
@ulugbekna, no sweat! Thanks a bunch

**Comment by rgrinberg** [comment]
@ulugbekna any updates on this?

**Comment by ulugbekna** [comment]
Not yet :(

**Comment by rgrinberg** [comment]
I think we should just fix this issue in the way proposed then. It's quite a simple fix and you should have no problem rebasing your work on top of it.
