### ISSUE TITLE
"Switch implementation/interface" button takes up obnoxiously much space in the tab bar

### ISSUE THREAD

**Issue by sim642** [ocamllabs/vscode-ocaml-platform#379]
Every other extension that I have, which puts buttons there, uses icons, which don't take up too much space. Currently, without an icon the "Switch implementation/interface" takes up the space of 5 such icons and two tabs, which is extremely inconvenient.

**Comment by ulugbekna** [comment]
Hope to fix soon. The problem is with finding an icon that is understandable to the user.

**Comment by ulugbekna** [comment]
Built-in VS code icon
![image](https://user-images.githubusercontent.com/16353531/94611860-9ef8e000-02a2-11eb-9c2f-593498cda96b.png)
![image](https://user-images.githubusercontent.com/16353531/94611866-a0c2a380-02a2-11eb-8eaa-0cc30e7cf40b.png)

More vs code icons [here](https://code.visualstudio.com/api/references/icons-in-labels)

More custom icon :-)
![image](https://user-images.githubusercontent.com/16353531/94612346-45dd7c00-02a3-11eb-81b7-629d641f7e91.png)
![image](https://user-images.githubusercontent.com/16353531/94612351-470ea900-02a3-11eb-9fc1-69b8b85ac508.png)

![image](https://user-images.githubusercontent.com/16353531/94612660-b6849880-02a3-11eb-93f9-2d2bdbd44604.png)

what do people think? :-)

**Comment by mnxn** [comment]
I like the custom icon. It conveys the feature pretty clearly.

**Comment by sim642** [comment]
The built-in VSCode icon you showed is for "replace all", so that would be super confusing. Doesn't any other language extension (like C/C++) already have such feature and existing icon?

**Comment by ulugbekna** [comment]
@sim642 checked switching ext for cpp, they don't have an icon 

I can go with ml/mli, which may not be intuitive for reason people or remove the icon at all 🤷‍♂️

**Comment by ulugbekna** [comment]
It'd be cool if every file would have the opposite file's extension as an icon, but that's not possible with current vacode afaict

Ml file having "mli" button, etc

**Comment by sim642** [comment]
GitLens's blame button changes icon dynamically, or does that use some mechanism in VSCode which isn't suitable for this? I'm not familiar with the extension APIs.

From the built-in icons `symbol-null` looked to me the most suitable.

Your custom icon would work fine as well, it'd save space and could be improved later if any better ideas come up. Although looking at the screenshots your provided, it seems to me like the pure black or white (depending on theme) doesn't exactly match the other icons there, which look slightly more gray-ish.

**Comment by ulugbekna** [comment]
Vote with 🚀 for:

![image](https://user-images.githubusercontent.com/16353531/94732580-bbf6e700-0366-11eb-87f7-663a832801d8.png)
![image](https://user-images.githubusercontent.com/16353531/94732587-bdc0aa80-0366-11eb-9ac2-b282035f1039.png)

Vote 🎉 for:

![image](https://user-images.githubusercontent.com/16353531/94732595-c0bb9b00-0366-11eb-8587-a656ef8d889b.png)
![image](https://user-images.githubusercontent.com/16353531/94732598-c2855e80-0366-11eb-8d01-24b948b8750c.png)

**Comment by Lupus** [comment]
Reason people typically know enough OCaml to figure the `ml/mli` :stuck_out_tongue:

**Comment by smorimoto** [comment]
I was a bit late to the discussion of this change. The experience may be bad with low-res displays, but I think putting it in the status bar like the "Formatting Toggle" extension is not bad.

**Comment by mnxn** [comment]
> I was a bit late to the discussion of this change. The experience may be bad with low-res displays, but I think putting it in the status bar like the "Formatting Toggle" extension is not bad.

I'm not sure if that would be the best solution since status bar items are usually file-independent commands. Whereas a tab bar button can be created from a command that works on a single file from [menu contributions](https://code.visualstudio.com/api/references/contribution-points#contributes.menus).

**Comment by smorimoto** [comment]
Oh, I think that makes sense.
