### ISSUE TITLE
Add command to create interface file

### ISSUE THREAD

**Issue by Lupus** [ocamllabs/vscode-ocaml-platform#381]
This feature seems to be missing. I got really used to it in reason-language-server, when I could create a .rei for my .re with one command, and redact it as needed. Would be great to have similar feature for ocaml platform extension!

**Comment by mnxn** [comment]
There have been a few talks about this before. Now that we have implementation/interface switching, generating the interface file can be integrated with it. I imagine a workflow in which switching to a non-existent interface file would open a file with the inferred signature. Would that be sufficient for your use-case?

**Comment by Lupus** [comment]
This was actually what I tried after I realized there is no command to create it - "maybe switching to non-existent interface will generate it? :thinking: ", but I ended up with empty file opened. So yeah, this sounds good.

**Comment by rgrinberg** [comment]
I started working on this here: https://github.com/ocaml/ocaml-lsp/pull/257

It's not functional ye, but hopefully we'll have something ready soon.

**Comment by tmattio** [comment]
This has been fixed:
- There is now a command `Alt+P` to insert the inferred interface
- When switching to a new interface, it will be initialized with the inferred one (depends on the next release of ocaml-lsp)
