### ISSUE TITLE
Switching implementation/interface for unsaved file fails silently.

### ISSUE THREAD

**Issue by mnxn** [ocamllabs/vscode-ocaml-platform#382]
Currently if you have a folder with a single `.ml` file and you switch to `.mli`, the extension creates an new unsaved document. However when you try to switch back to the `.ml` file (without saving the `.mli`), nothing happens. The extension logs something like

> [Trace - 1:44:34 PM] Received response 'ocamllsp/switchImplIntf - (9)' in 0ms. Request failed: no document found with uri: untitled:/Users/max/main.mli (-32600).

I think there can be two solutions to this:

1. Allow the switching implementation to work on unsaved ("untitled") files. 

2. Don't show the switching button for untitled files. A button that does nothing is worse than no button at all. This can be done by using [`resourceScheme`](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts) in the menu contribution when clauses: https://github.com/ocamllabs/vscode-ocaml-platform/blob/c85714711424022d5949f7bbb3c9b768c340f73d/package.json#L77

**Comment by rgrinberg** [comment]
I think the main issue here is that we don't take into account the document store when looking for existing modules. If we fix this, then switching for unsaved files is going to work transparently. @ulugbekna can we assign this to you?

**Comment by ulugbekna** [comment]
Absolutely
