### ISSUE TITLE
Consider switching to Lwt or Async

### ISSUE THREAD

**Issue by rgrinberg** [ocamllabs/vscode-ocaml-platform#395]
Both async and lwt offer us a better concurrency toolkit than what's available in JS. The only question is how to remain compatible with native JS promises.

**Comment by rbjorklin** [comment]
I'm not sure it makes sense but if it's sound maybe Lwt should be made compatible with: https://promisesaplus.com/ ?

**Comment by mnxn** [comment]
> I'm not sure it makes sense but if it's sound maybe Lwt should be made compatible with: https://promisesaplus.com/ ?

I don't think it's necessary to be API-compatible with JS promises since it's not going to be used directly on the JS side. We just need _safe_ conversion functions between async/lwt types and JS promises.

**Comment by tmattio** [comment]
We didn't hit any limitation with the Promise monad. If we do let's consider re-opening this, but in the meantime, I don't think we'll want to work on this.
