### ISSUE TITLE
[Question] OCamlformat is not working

### ISSUE THREAD

**Issue by Kakadu** [ocamllabs/vscode-ocaml-platform#407]
Some weeks ago the plugin was able to auto apply `ocamlformat` on my code but from some time it has stopped doing that. Maybe I updated a plugin, maybe I updated VsCode too... It's unlikely that I have broke somewhere in opam switch

I checked:
1) `ocamlformat` is present in the switch being used
2) I can run it manually from terminal
3) `.ocamlformat` file is present
4) Output window doesn't mention ocamlformat, only calls to `opam` to run `ocaml-lsp`
5) I haven't found any hotkey to enable/disable ocamlformat in a plugin or apply `ocamlformat` manually. Do they exist?

Please, help me debug this. It would be great to have troubleshooting guidelines in README or something.

**Comment by ulugbekna** [comment]
Have you checked if `format on save` in your IDE is on? 

![image](https://user-images.githubusercontent.com/16353531/96016853-8ca5a700-0e49-11eb-92d0-675d5a9df8b9.png)

If it's on, in output view for `ocaml-lsp`, you should see `textDocument/formatting` requests and responses.

**Comment by Kakadu** [comment]
Oh, man, thanks. 
By some reason I was looking for the right option only in a plugin-specific settings tab, not in the global `Text Editor` tab

**Comment by ulugbekna** [comment]
no problem :)
