### ISSUE TITLE
Where can I find the documentation?

### ISSUE THREAD

**Issue by rdavison** [ocamllabs/vscode-ocaml-platform#412]
I've clicked around this repo for a few minutes and couldn't find documentation on the configuration.  For example, the readme shows the following minimal documentation for the `ocaml.sandbox` configuration parameter:

![Screen Shot 2020-10-19 at 1 17 09 PM](https://user-images.githubusercontent.com/630055/96489491-84fd4e00-120d-11eb-8e6d-eb9be4ed561a.png)

While it's great to know that the default value is `null`, I wasn't able to find examples of other possible values that I could put in there. Is the schema documented anywhere?

**Comment by mnxn** [comment]
We can add some documentation, but the recommended way to switch sandboxes is by using the select sandbox command or by clicking the status bar item.

**Comment by rdavison** [comment]
Ok, I opened a workspace, and then I used the "select sandbox" command.  I set the command to `esy $prog $args` and now I'm getting an error that no esy sandbox was found. Is this the correct way to select a sandbox?

**Comment by mnxn** [comment]
If your project is using Esy, you should have the option to select an Esy sandbox:

![image](https://user-images.githubusercontent.com/25037249/96494908-de5c8180-11fb-11eb-9679-a52d6d641dc8.png)

**Comment by rdavison** [comment]
I just installed the sandbox from the Extension browser.  Perhaps my extension is out of date?
![Screen Shot 2020-10-19 at 2 34 14 PM](https://user-images.githubusercontent.com/630055/96497151-3e612100-1218-11eb-8a84-79d5caddec4c.png)

**Comment by mnxn** [comment]
Your extension should be up-to-date if you installed from the extension browser.

After you select `OCaml: Select a Sandbox for this Workspace`, you should get the menu to select the Esy package manager.

**Comment by rdavison** [comment]
Oh, I found it!  Ok great, thank you so much. For some reason that simultaneously felt easier and harder than it should have been?  Easier, because in the end, I didn't need to touch any configuration files.  Harder, because even after I clicked on the menu, I didn't see it.  I took a screenshot and was blurring out the project names for posting on this thread, and that's when I saw the words Esy.  Perhaps, it would be more intuitive to make the drop-down item text be `Esy - /path/to/project` instead of `/path/to/project Esy` ?

**Comment by mnxn** [comment]
Glad you got it working!

You're right that is a bit hard to spot. I'll leave this issue open until we improve the startup experience.

Would something like this be easier to parse visually?

![image](https://user-images.githubusercontent.com/25037249/96498723-4a8db400-1201-11eb-99ec-a24272087439.png)

**Comment by ulugbekna** [comment]
I think we could just document the feature in README? 

Not to bikeshed but: using Esy instead of project name would hinder filtering by project name:
![image](https://user-images.githubusercontent.com/16353531/96501384-974cab80-1250-11eb-85e3-0594b734e817.png)

(can't wait to fix esy sandbox discovery)

**Comment by rdavison** [comment]
@ulugbekna : I don't mind if it's documented in the README, but, just looking at your screenshot, it seems there's something else going on as well.  The first four lines are identical... and it's not clear why.  Perhaps is there some additional information that isn't being printed?

**Comment by mnxn** [comment]
> @ulugbekna : I don't mind if it's documented in the README, but, just looking at your screenshot, it seems there's something else going on as well. The first four lines are identical... and it's not clear why. Perhaps is there some additional information that isn't being printed?

The different Esy lines are because it's picking all of the `opam`, `esy.json` and `package.json` files in a folder individually. I'm actually in [the process of fixing it](https://github.com/ocamllabs/vscode-ocaml-platform/pull/413) so it doesn't have duplicates, which should come to the next release.

**Comment by mnxn** [comment]
@rdavison The UI is changing a bit in #415.

Would this make more sense?
<img width="601" alt="image" src="https://user-images.githubusercontent.com/25037249/96532343-8dbb4780-1240-11eb-9929-909621e90fdf.png">

**Comment by rdavison** [comment]
@mnxn Yeah that looks better, but I'm confused about the three packages at the bottom.  Is it the case that you're detecting that they belong to an Esy project, so you're labelling them as Esy projects, even though one is an npm package, and the other is an opam package?  Like, why do all 3 show esy?

**Comment by mnxn** [comment]
> @mnxn Yeah that looks better, but I'm confused about the three packages at the bottom. Is it the case that you're detecting that they belong to an Esy project, so you're labelling them as Esy projects, even though one is an npm package, and the other is an opam package? Like, why do all 3 show esy?

Esy supports using `esy.json`, `package.json` with an `esy` field, or `.opam` files for its configuration. Choosing one of those would change what file is passed to  `esy -P`.

@ulugbekna is describing [a different workflow](https://github.com/ocamllabs/vscode-ocaml-platform/pull/415#issuecomment-712830964) in #415 if you'd like to make some suggestions.

**Comment by tmattio** [comment]
I believe all the configurations are documented in the README now (thanks to @ulugbekna), don't hesitate to reopen if there's something missing.
