### ISSUE TITLE
Format Document does not work.

### ISSUE THREAD

**Issue by pveber** [ocamllabs/vscode-ocaml-platform#419]
I'm pretty sure this is a configuration issue but I don't know how to troubleshoot it. The code is not formatted when I type Ctrl-Shift-I or call F1 + Format Document. I followed the instructions for installation and I run vscode from the terminal:
```sh
$eval $(opam env)
$opam switch
#  switch                     compiler                    description
   4.07.1+BER                 ocaml-variants.4.07.1+BER   4.07.1+BER
→  4.11.1                     ocaml-base-compiler.4.11.1  4.11.1
   default                    ocaml-base-compiler.4.07.1  default
[...]
$opam search ocaml-lsp-server
# Packages matching: match(*ocaml-lsp-server*)
# Name           # Installed # Synopsis
ocaml-lsp-server ~dev        pinned to version ~dev at git+https://github.com/ocaml/ocaml-lsp.git
$which ocamllsp 
/home/pveber/.opam/4.11.1/bin/ocamllsp
$which ocamlformat 
/home/pveber/.opam/4.11.1/bin/ocamlformat
```
What should I check now?

**Comment by mnxn** [comment]
Do you have a `.ocamlformat` file in your workspace folder? That's a requirement of ocamlformat.

We might add ocamlformat defaults in the future (https://github.com/ocamllabs/vscode-ocaml-platform/issues/332), but right now the `.ocamlformat` file is necessary.

**Comment by pveber** [comment]
That was it! Thanks a lot!
