### ISSUE TITLE
Semantic highlighting

### ISSUE THREAD

**Issue by ALANVF** [ocamllabs/vscode-ocaml-platform#432]
Would it be possible to add semantic highlighting for OCaml? I've never tried messing with it myself, but I'd assume that it'd be fairly easy to implement since LSP is already supported.

**Comment by mnxn** [comment]
Semantic highlighting is not supported in the current LSP specification. It is only listed in the upcoming [3.16 spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_semanticTokens). Reading through that section, I'm not sure I would call implementing the feature very easy either. 

It would definitely be helpful though, as the highlighting of types and format strings could be improved.

When 3.16 releases, this is something that would be implemented in [ocaml/ocaml-lsp](https://github.com/ocaml/ocaml-lsp)

**Comment by smorimoto** [comment]
I think we can work on this already.

**Comment by rgrinberg** [comment]
Already done in ocamllsp
