### ISSUE TITLE
How to disable problem highlighting in expressions?

### ISSUE THREAD

**Issue by MdeLv** [ocamllabs/vscode-ocaml-platform#435]
Uninterpreted (extension-specific) expressions are made difficult to read because they are marked with wavy red lines.  
How can I disable the two following kinds of messages?
```
Uninterpreted extension 'foo'.
Unbound module Bar
```
Bar is a module of my program. Maybe should I declare it but where ?
 
Can you give some hints about how to make specific extensions interpreted, and to more understand ocamllsp&vscode-ocaml-platform?

btw, 
I also get the following
```
Unbound module Stdlib
Warning 49: no cmi file was found in path for module Arg
```
I never got that message anywhere else before.
Here is the detailed message:
```
{
	"resource": "/home/test/.opam/4.10.0/lib/ocaml/stdlib.mli",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "Warning 49: no cmi file was found in path for module Arg",
	"source": "ocamllsp",
	"startLineNumber": 1329,
	"startColumn": 23,
	"endLineNumber": 1329,
	"endColumn": 26
}
```
That doesn't look related to ocamllsp and vscodeèocaml-platform, but how can i "fix" that?

**Comment by mnxn** [comment]
PPX extension should not be highlighted as a problem.

ocaml-lsp uses Merlin internally, so my guess is that your `.merlin` file is incorrectly configured/generated.

If you can provide a small example project that reproduces these errors, it would be helpful for figuring out what's going on.

**Comment by MdeLv** [comment]
I just need to disable wavy lines under uninterpreted  expressions. 
That may also be useful when .merlin is not yet defined.

**Comment by mnxn** [comment]
There is currently no way to disable individual language server features. This might be added as a configuration option in the future.

> I just need to disable wavy red lines under uninterpreted expressions, without using merlin.

Why can't you use merlin? The type-based editor features all interact with merlin internally, so projects without proper `.merlin` files are going to be severely limited. If you're using Dune, merlin files will be generated automatically, even for projects with PPX preprocessing.

**Comment by MdeLv** [comment]
> There is currently no way to disable individual language server features. This might be added as a configuration option in the future.

Can you guide me to the part of vscode-ocaml-platform (and/or ocamllsp) that I can fine-tune in order to disable wavy red lines under uninterpreted expressions?

I don't need merlin. Simple syntax highlighting is enough.

**Comment by rgrinberg** [comment]
I think the simplest way for you is to just uninstall ocamllsp.

**Comment by MdeLv** [comment]
Are you suggesting that vscode-ocaml-platform alone would keep on providing useful syntax highlighting, while disabling wavy red lines ?

**Comment by mnxn** [comment]
That is correct.

All syntax highlighting is independent of the language server. The syntax highlighting for each file type is described in JSON files here: https://github.com/ocamllabs/vscode-ocaml-platform/tree/master/syntaxes

If you uninstall the language server, there will be a warning that `ocamllsp` isn't available, but the syntax will continue to be highlighted.

**Comment by MdeLv** [comment]
`opam remove ocaml-lsp-server` disables that behavior while keeping useful vscode-ocampl-platform syntax highlighting.
Thanks.

> I think the simplest way for you is to just uninstall ocamllsp.

Is removing this package the only way to get that, or is it possible to just disable ocamllsp?

I would like to know more about OCaml language tooling and why it's not as easy as pie. What is the recommended documentation? 
What are the key parts of vscode-ocaml-platform and ocamllsp to first look at? 
Thanks.

**Comment by rgrinberg** [comment]
> I would like to know more about OCaml language tooling and why it's not as easy as pie.

It's fairly easy, but it's not something that we can spend time on. It's too specialized of a request that is scarcely useful to everyone else who finds the diagnostics useful. The root of the problem is likely to be in your setup (missing .merlin files).

I would recommend that you look for a way to disable diagnostics in vscode. That should accomplish what you want without uninstalling anything.
