### ISSUE TITLE
Publish to open-vsx in CI

### ISSUE THREAD

**Issue by mnxn** [ocamllabs/vscode-ocaml-platform#438]
open-vsx is used by editors like VSCodium instead of the VSCode extension marketplace.

The process is similar to using the `vsce` tool, but requires another token:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by smorimoto** [comment]
I can publish it with my account, but it's probably better to create a namespace with @rgrinberg's account and use the account's token just like we did for VSCode.

**Comment by smorimoto** [comment]
Oh, no, I misunderstood that a little.

**Comment by mnxn** [comment]
Currently, ocamllabs on open-vsx is a "public" repository and anyone with a token can publish to it. It's possible to [claim ownership](https://github.com/eclipse/openvsx/wiki/Namespace-Access) to restrict who can publish to the namespace.

Either way, we would need to upload a token to this repository's secrets so we can reference it from the `ovsx publish` command.

**Comment by smorimoto** [comment]
I  just made a claim.
