### ISSUE TITLE
[RFC] Integration with Opam and UI

### ISSUE THREAD

**Issue by ulugbekna** [ocamllabs/vscode-ocaml-platform#443]
It would be nice to have better Opam support in the extension, preferably with rich UI experience. In this issue we track possibilities for features and UI elements that could be added to the extension. 

_Note:_ It would be nice if proposals could be prefixed by `*uid` to be able to more easily discuss specific proposals, e.g., `*0` show a list of switches available in the system.

A source of inspiration: Scala Metals extension [here](https://scalameta.org/metals/docs/editors/vscode.html). See how the vscode metals extension looks like below:
![image](https://user-images.githubusercontent.com/16353531/100059347-2f7b1900-2e2b-11eb-9bf3-eb554c61236c.png)

**Comment by rgrinberg** [comment]
As discussed in the meeting, the initial functionality that we're looking for is to display a hierarchy of Switch > Packages > Libraries.

The metadata can be obtained as follows:

* Switches - obtained from `$ opam switch list`, as we do today.
* Packages - obtained from `$OPAMROOT/<switch>/.opam-switch/switch-state in the opap format
* Libraries - obtained from `ocamlfind list` (and later dune).

We'll also need some bindings to display the side panel and the tree view.

**Comment by ulugbekna** [comment]
`*1` I feel like dependency management of a project is quite annoying. I wish we could make it an interactive UI that would make that easier. To do so, some things that would be nice to have displayed:

- which packages could be updated
- which packages are pinned (but maybe could be unpinned)

In displaying those, we should take care that we have separate sections for packages used by the project and all installed packages. 

We could get some inspiration for this by the new git interactive rebase UI for vscode, which offers quite intuitive interface. 

`*2` Evaluating how much complexity and integration between tools this entails, it may make sense to do those things on the ocaml-lsp side.

`*3` Not opam only per se, but we could have a special side-bar section (screenshot below) for managing tools and their versions, e..g, ocaml-lsp, ocamlformat, dune, opam. While it doesn't seem vital, two things should be noted:

- users can stay "on top" of their tools, meaning at any time a new tool is released, they would know and take action if necessary, AND those packages wouldn't pollute the general project-related "packages" window perhaps
- that section can always be folded and stay discreet, so there is little price to pay except for taking care that section exists and properly implemented

![image](https://user-images.githubusercontent.com/16353531/100060307-a7960e80-2e2c-11eb-8479-bd0f40271722.png)

**Comment by tmattio** [comment]
I'm closing this, as we've merged the UI. Feel free to open new issues with specific feature requests related to the UI.
