### ISSUE TITLE
ocamllsp initialisation failed

### ISSUE THREAD

**Issue by dinosaur-lin** [ocamllabs/vscode-ocaml-platform#449]
I have ocamllsp installed with version 1.2.0.  But this extension complains:

Toolchain initialisation failed: Command failed with ocamllsp: unknown option `--version'. Usage: ocamllsp [OPTION]... Try `ocamllsp --help' for more information. See output channel for more details

Do you know why? what can I do to provide more information for diagnose? thanks.

**Comment by mnxn** [comment]
Are you certain you have version `1.2.0` of ocaml-lsp installed? The only reason I can think of that would result in that error is if you have an earlier version installed that doesn't have the `--version` flag.

**Comment by dinosaur-lin** [comment]
@mnxn  thanks for the quick reply. 

I think you are right. I installed the latest ocaml-lsp in 4.11.1, not the "opam(default)", which vscode is using by default.
Once I switch to "opam(4.11.1)", everything works. thanks!
