### ISSUE TITLE
let-operators breaks syntax highlighting

### ISSUE THREAD

**Issue by hcarty** [ocamllabs/vscode-ocaml-platform#45]
Only for a little while, from what I can tell.

**Comment by hcarty** [comment]
<img width="457" alt="image" src="https://user-images.githubusercontent.com/199147/75300914-8bf6cc80-57f6-11ea-9efd-f03018a3b9c9.png">
As an example

**Comment by mnxn** [comment]
Now that the extension has been updated with the revised grammar in #92, this should be fixed.

**Comment by hcarty** [comment]
Thank you @mnxn!
