### ISSUE TITLE
rfc: ocamldebug integration

### ISSUE THREAD

**Issue by cdaringe** [ocamllabs/vscode-ocaml-platform#454]
# problem

Platform currently does not offer program launch configs or IDE debugging

# solution

Implement https://microsoft.github.io/debug-adapter-protocol/

I have no experience doing this, but I am interested in learning more about it and possibly trying to independently create a skeleton implementation.

If such work were to take place, how would it play nicely inside of this project?

**Comment by Khady** [comment]
experimentations around DAP seem to happen in https://github.com/hackwaly/ocamlearlybird for now. But it would be nice to have it here too on the long term.

**Comment by mnxn** [comment]
From the VSCode side, it's a few lines of JS and some JSON configuration: https://github.com/hackwaly/vscode-ocaml-debugger

I don't think there's much discussion that can happen here, at least until there is a more stable debug-adapter-protocol implementation.

ocamlearlybird got [support from the OCaml Software Foundation recently](https://discuss.ocaml.org/t/ann-ocamlearlybird-now-an-ocaml-software-foundation-supported-project/6834), so it's likely we'll see some progress there.

**Comment by cdaringe** [comment]
Will follow that thread. Thx
