### ISSUE TITLE
Improve odoc syntax highlighting

### ISSUE THREAD

**Issue by smorimoto** [ocamllabs/vscode-ocaml-platform#470]
https://ocaml.github.io/odoc/odoc/using-odoc.html

**Comment by mnxn** [comment]
MLD files are already recognized: 
https://github.com/ocamllabs/vscode-ocaml-platform/blob/80523d5654091cd7c317b5de6ab1c5fc334ebc48/package.json#L365

The syntax just needs to be improved to support more ocamldoc/odoc syntax.

**Comment by smorimoto** [comment]
Oops... Indeed. I completely missed that.

**Comment by dlesbre** [comment]
Odoc and ocamlformat highlighting was added in 1.17.0 by #1365

**Comment by tmattio** [comment]
Thanks a lot for the fantastic contribution @dlesbre! Closing the issue now. As a follow-up on your PR, would you be interested in adding support for the odoc syntax in mld files as well? That's a frequently requested feature, and as we're trying to incentivise package authors to write more docs, having syntax support for standalone documentation pages would be immensely helpful.

**Comment by tmattio** [comment]
Seems that I wrongly assumed that your PR only improved syntax highlighting for comments inside ml files, but it also works in mld files. Again thanks a lot for all your work on this, this is a huge improvement!
