### ISSUE TITLE
Extract ocaml-platform to its own package

### ISSUE THREAD

**Issue by tmattio** [ocamllabs/vscode-ocaml-platform#472]
A lot of logic in `vscode-ocaml-platform` could be re-used in other editors. To achieve this, we could identify the subset of `vscode-ocaml-platform` that is independent of VSCode, and extract it in its own package `ocaml-platform`.

For instance, the sandbox and toolchain management is something that could be re-used, regardless of the editor used.

@rgrinberg Is it something that could help provide the same feature set in Emacs?

**Comment by rgrinberg** [comment]
It’s worth considering, but right it’s premature. Not to mention that there’s the annoying hurdle of vscode preferring to use jsoo over standard binaries.

If we have a reliable flow for fetching and installing ocamllsp, that would probably be the best candidate for reuse. I’m not sure about sandbox management as its already somewhat done in Emacs.

**Comment by tmattio** [comment]
Closing, this is just adding noise for now.
