### ISSUE TITLE
Confusing type reported vs e.g. utop's #typeof when module names are shadowed locally

### ISSUE THREAD

**Issue by cemerick** [ocamllabs/vscode-ocaml-platform#475]
For example, the plugin is reporting this for a value `Schedule.inits`:

![image](https://user-images.githubusercontent.com/47489/101954832-c802ee80-3bca-11eb-98a0-ac8ffb5dcd5d.png)
```ocaml
Fsm/1.Phase.t list Stdlib__map.Make(Fsm/2.State.TY).t
```

But utop provides a very clear type:

```ocaml
utop # #typeof "Schedule.inits";;
val ( Schedule.inits ) :
  Schedule.Fsm.Phase.t Containers.List.t Fsm.State.Map.t
```

In this example, there are two modules named `Fsm`, one providing a functor that is used to define a local specialization that is also named `Fsm` (shadowing the global one). If I rename the latter to something else, then the plugin reports an even cleaner type than utop IMO:

![image](https://user-images.githubusercontent.com/47489/101955410-bc63f780-3bcb-11eb-8da3-203a49e28dfb.png)
```ocaml
Foo.Phase.t list Fsm.State.Map.t
```

As you might imagine, the types involved get very hairy very quickly when working with non-toy examples, but I'd obviously prefer to not make code changes to accommodate the tooling's ideosyncracies here.

**Comment by ulugbekna** [comment]
As you can see in the example with `#typeof`, first `Fsm` is prefixed with `Schedule`, i.e., `Schedule.Fsm`, but the second one is not. In other words, there are two modules with the same name `Fsm`, but utop has a clear way to distinguish between those. In the editor version, you probably have `open`ed `Schedule`, hence the editor needs to differentiate between to `Fsm`s by putting an integer next to them `Fsm/1` and `Fsm/2`. 

I have a feeling that working on this issue without a minimal reproducible case or the exact code that you have reported is difficult.  

---

I agree that `Stdlib__map.Make(...` is bad, but I wonder whether that has been fixed already.

**Comment by tmattio** [comment]
I believe this has been fixed, let's reopen if it's not the case.
