### ISSUE TITLE
How do you hide the type preview over a definition?

### ISSUE THREAD

**Issue by ghulette** [ocamllabs/vscode-ocaml-platform#480]
Is there a secret JSON setting to turn this off? For example, when I have `let x = 5` in a file it puts small grey text `int` above it.

Maybe this is a feature request. I'd like a setting and even a keybinding to turn the type labels on and off.

**Comment by mnxn** [comment]
This feature is called "code lens". There is a VSCode setting to disable it (from settings.json):
```json
"editor.codeLens": false
```

Or if you only want to disable it for OCaml:
```json
"[ocaml]": {
	"editor.codeLens": false
}
```

You can also search for "code lens" in the VSCode settings tab and there will be a checkbox you can untick to disable it:
![image](https://user-images.githubusercontent.com/25037249/102419410-88664900-3fb4-11eb-9770-a2efc73c4a00.png)


I am not aware of a built-in way to toggle code lens with a keyboard shortcut, but there are ways to accomplish it with an additional extension:

https://medium.com/hack-visual-studio-code/toggle-any-setting-in-vs-code-using-keyboard-shortcut-arguments-cdb5ddc56955

**Comment by ghulette** [comment]
Perfect. Thank you!
