### ISSUE TITLE
Running the toplevel phrase surrounding the text cursor (à la tuareg C-c C-e)

### ISSUE THREAD

**Issue by ysalmon** [ocamllabs/vscode-ocaml-platform#490]
I am just discovering VSCode/VSCodium with the OCaml extension. It has many nice features compared to the rather austere Emacs+Tuareg I am used to.

I miss one thing however : the ability to run the toplevel phrase surrounding the text cursor with utop (or the standard OCaml REPL).
This would be especially useful in my context, which is teaching introductory OCaml to students with extremely scarce lab sessions : we do not write complete programs but rather a small bunch of functions to implement (part of) an algorithm.

Currently, I can use the Run selected text from the Terminal menu, after having run utop. But this is rather crude as it does not add the ``;;`` that utop toplevel requires at the end. Also, one has to manually select the whole phrase.

Is it possible to use the OCaml extension to do so ?
I think the required procedures already exist :

- in a .ml file without any ``;;``, I get correct type annotations for each function and
- the breadcrumbs display the name of the function or type definition in which the text cursor currently is, so it has a way to associate a cursor position to the surrounding phrase.

**Comment by tmattio** [comment]
Hey @ysalmon,

Thanks for the issue. Sending top-level expressions to Utop is in our list and the feature is described here https://github.com/ocamllabs/vscode-ocaml-platform/issues/451.

We're currently working on the UI and Dune integration, but interactivity will probably come soon after these.

**Comment by FayardProf** [comment]
Hi @tmattio,

I think that what would be useful to us is the "Terminal oriented" version of #451.

Thanks for your work and bonnes fêtes de fin d'année,
François

**Comment by ulugbekna** [comment]
#452 considers integration with `utop` - a feature, which I also miss dearly.

**Comment by tmattio** [comment]
Closing in favor of #452, the PR linked here should be merged soon anyways.
