### ISSUE TITLE
Help from a newbie

### ISSUE THREAD

**Issue by FayardProf** [ocamllabs/vscode-ocaml-platform#491]
Hi,

I am very new to OCaml and I don't know too much the eocsystem. So far, I have only used it as a REPL. And I am completely lost on the installation of Ocaml Platform on VS Code and macOS. I have installed ocaml and opam from homebrew,

I would like to have some documentation to run a single "hello world" program in OCaml. 

So far I am stuck with a message saying "OCaml Platform is using the package manager and sandbox... ". And each time I launch VS Code, I end up choosing the global sandbox. I can't find any way to configure that in the "Settings" of VS Code.

Could you please give some help and give "basic" options for the package so I can work from that?

Best regards,
François

**Comment by tmattio** [comment]
Hey @FayardProf!

We're working on providing a better first-time experience (e.g. https://github.com/ocamllabs/vscode-ocaml-platform/pull/463). In the meantime, I would recommend first getting up and running without VSCode, and then open your project with the editor.

To create a project quickly, I would recommend using [spin](https://github.com/tmattio/spin):
```
opam install spin
spin new bin my-app
```

This will generate a new project and install the dependencies in a local opam switch. You can run the binary with `dune exec bin/main.exe`

Once that's done, you can install the platform tools in your switch:
```
opam install ocaml-lsp-server ocamlformat
```
And open your project with VSCode, it should detect your local switch and use it as a sandbox, with the platform tools installed in it.

**Comment by FayardProf** [comment]
Hi. Thanks for your help. I have tried to use spin but I ended up with a lot of questions, asking for a github account and so many things I forgot. I ended with a process that failed.

Is there a way to create something very minimal, as I just want to run a Hello World?

Those "sandbox" and "environement" are really a pain to use for a newbie. It's a bit like starting a "Hello World" program in Python and finishing up with conda, pip and all that mess.

Thanks anyway, as I understand that for the time being must be used by power users and not by newbies.

**Comment by tmattio** [comment]
Alternatively, you can install everything in your global switch:
```
opam install ocaml-lsp-server ocamlformat
```

And generate your project with:
```
dune init project my_app .
cd my_app
dune exec main.exe
```

Then open VSCode and select the `Global` sandbox.

> Those "sandbox" and "environement" are really a pain to use for a newbie

They are, that's why we're trying to automate things as much as possible in VSCode, but it's a process 🙂

**Comment by FayardProf** [comment]
Thanks very much for your help. It is much better with Dune.

I have launched "code ." from the project directory and I have opened the main.ml file. Now, if I may ask, how do I compile and run the program from VS Code ?

**Comment by tmattio** [comment]
It's not possible at the moment, unfortunately. What I usually do is open a terminal and run the binary from there. The command to run the binary after `dune init` should be `dune exec bin/main.exe`

**Comment by FayardProf** [comment]
Ok. Thanks for your help.

**Comment by tmattio** [comment]
Closing now, don't hesitate if I can help any further.

You can also check out the Discuss: https://discuss.ocaml.org/ if you have general OCaml questions
