### ISSUE TITLE
Question: commenting selection

### ISSUE THREAD

**Issue by Kakadu** [ocamllabs/vscode-ocaml-platform#494]
At the moment if I select some text and press `Ctrl+/` the whole string is being commented out. 
Is this a feature of VsCode in general or it should be configurable somwhere in vscode-ocaml-platform?

**Comment by rgrinberg** [comment]
It's a feature of vscode. There's not much we can do in the extension unfortunately.

**Comment by Kakadu** [comment]
I managed to configure that. 
I needed to add the following to my `~/.config/Code/User/keybindings.json` and remove default keybindings

```
  {
    "key": "ctrl+/",
    "command": "-editor.action.commentLine",
    "when": "editorTextFocus && !editorReadonly"
  },
  {
    "key": "ctrl+/",
    "command": "-toggleExplainMode",
    "when": "suggestWidgetVisible"
  },
```
