### ISSUE TITLE
Hover doesn't include odoc content for definitions in the same file

### ISSUE THREAD

**Issue by cemerick** [ocamllabs/vscode-ocaml-platform#519]
More explicitly, if a documented function is defined in `foo.ml`, hovers on references to it in `bar.ml` will show that documentation, but hovers on references to it later in `foo.ml` will not.

**Comment by ulugbekna** [comment]
It is more like only the last type/value definition's documentation is available when we hover over type/value in the same file.

![image](https://user-images.githubusercontent.com/16353531/106905372-0c6bc000-671e-11eb-858e-fbdcdf179e3e.png)

![image](https://user-images.githubusercontent.com/16353531/106905384-0ece1a00-671e-11eb-9ff0-af84ad1b6ab3.png)

But that's an issue with merlin:

For constructor `A`: 

```
 ❯ ocamlmerlin single document -position 13:17 -verbosity 0 < src/t0.ml | jq
{
  "class": "return",
  "value": "No documentation available",
  "notifications": [],
  "timing": {
    "clock": 5,
    "cpu": 5,
    "query": 0,
    "pp": 0,
    "reader": 2,
    "ppx": 0,
    "typer": 3,
    "error": 0
  }
}
```

For function `f`: 

```
❯ ocamlmerlin single document -position 13:40 -verbosity 0 < src/t0.ml | jq
{
  "class": "return",
  "value": "identity fn",
  "notifications": [],
  "timing": {
    "clock": 5,
    "cpu": 5,
    "query": 0,
    "pp": 0,
    "reader": 2,
    "ppx": 0,
    "typer": 3,
    "error": 0
  }
}

```

**Comment by cemerick** [comment]
@ulugbekna the documentation content you're seeing in hovers is exactly what I would expect (modulo the relatively minor lack of separation between the type and ctor documentation). Likewise with your claim re: #520.

Now it seems I have either a misconfiguration or something similar.

Anyone have any ideas as to what to look for?

**Comment by ulugbekna** [comment]
I meant that the current "doc on hover" implementation seems buggy: only
the documentation for the last defined type/value is shown on hover.

On the screenshots where both `mid` and `f` defined and have doc comments
with `f` being the last definition with doc comment, `f` has documentation
on hover but not `mid`.

If I understand correctly, that's a merlin bug and ideally should be
reported in the merlin repo.

**Comment by cemerick** [comment]
Thank you very much @ulugbekna, I didn't grok what you were showing in your screenshots at first!

As you can see, I've filed an issue in the merlin project. I'll leave it up to the team here as to whether this issue should be left open to track the effect of the merlin issue's eventual resolution or not.

**Comment by ulugbekna** [comment]
Fixed in https://github.com/ocaml/merlin/pull/1265
