### ISSUE TITLE
Hover on constructor does not show constructor's documentation

### ISSUE THREAD

**Issue by cemerick** [ocamllabs/vscode-ocaml-platform#520]
If I have this in `foo.ml`:

```ocaml
(** documentation for the type *)
type mid = A (** documentation for the [A] ctor *) | B of int
```

and this in `bar.ml`:

```ocaml
let j = A
```

Triggering the hover on the reference to `A` in `bar.ml` pops this up:

```
type mid = A | B of int
documentation for the type
```

i.e. the documentation for actual constructor under the point is not shown.

**Comment by ulugbekna** [comment]
Interestingly, this happens only if the variant constructors are in another file, i.e., this shows correct documentation: 

```
module T0 = struct
  (** documentation for the type *)
  type mid = A  (** documentation for the [A] ctor *) | B of int
end

let f = function T0.A -> () | B _ -> ()
```

**Comment by rgrinberg** [comment]
@voodoos are you aware of this one? If yes, I'll close it here.

**Comment by voodoos** [comment]
I am not able to reprodue on with merlin 4.11-501.

<img width="482" alt="Screenshot 2023-09-26 at 14 34 09" src="https://github.com/ocamllabs/vscode-ocaml-platform/assets/5031221/4b535059-6da3-4f28-b2de-3ca0d4a22091">
