### ISSUE TITLE
"Format Document" fails silently if you don't have an ".ocamlformat" file

### ISSUE THREAD

**Issue by TyOverby** [ocamllabs/vscode-ocaml-platform#525]
Like the title suggests, if you ask vscode to format an ocaml file, but you don't have an ".ocamlformat" file in the tree, nothing happens.

I would expect some default formatting to occur, or at least see an error message telling me how to set it up.

**Comment by rgrinberg** [comment]
I agree, but this seems like an issue with ocamlformat. It refuses to work without a config file and it seems wrong for us to override that behavior.

**Comment by TyOverby** [comment]
I agree that this is an issue with ocamlformat, but I'd argue that editor-integration is a good place to add more guiderails for users.

**Comment by mnxn** [comment]
There was a little bit of discussion in https://github.com/ocamllabs/vscode-ocaml-platform/issues/332 about this. I think supporting a default formatting profile like the C++ extension does would be useful.

**Comment by tmattio** [comment]
At the very least, we should notify the user that no `.ocamlformat` file could be found.

**Comment by tmattio** [comment]
Closing in favor of #322, feel free to continue the discussion there :)
