### ISSUE TITLE
Integrate ocamlearlybird

### ISSUE THREAD

**Issue by hackwaly** [ocamllabs/vscode-ocaml-platform#534]
https://github.com/ocaml/opam-repository/pull/18198

As ocamlearlybird beta2 will soon be released. I think it's the right time to start considering integrating ocamlearlybird with ocaml-platform.

If we decide to integrate it. We have two choices:

1. Make a vscode extension pack that simply includes hackwaly/ocamlearlybird extension.
2. Add debugger contribution in ocaml-platform extension that directly using cli version of ocamlearlybird.

**Comment by rgrinberg** [comment]
> Make a vscode extension pack that simply includes hackwaly/ocamlearlybird extension.

That seems good to me.

> Add debugger contribution in ocaml-platform extension that directly using cli version of ocamlearlybird.

Could you explain this point a bit more?

**Comment by hackwaly** [comment]
It meant to move debugger extension maintainance responsibility to ocaml-platform side. You decide if implement debugger in ocaml-platform or make it a standalone extension. And I just develop cli version of ocamlearlybird since that.

**Comment by rgrinberg** [comment]
I see. I think you have a better idea on how the integration should look like than me, so how about I'll just invite you to the maintenance team of this extension, and you can proceed with 1. or 2. or whatever plan you think is right.

**Comment by tmattio** [comment]
I'm very much in favor of a tight integration with `ocamlearlybird` 🙂 

The work on Dune RPC can help with the debugging experience (e.g. by building in bytecodes when trying to debug, or by providing the output file in the `_build` dir from the source file), and we will most likely be able to provide support more easily if the debugger contributions (and other custom logic) are in the `vscode-ocaml-platform` directly.

It will probably make sense to make `ocamlearlybird` part of the tools we install automatically (cf #463) too, so the users will be able to use the debugger without any additional configuration.
