### ISSUE TITLE
Include VSIX in releases

### ISSUE THREAD

**Issue by crackcomm** [ocamllabs/vscode-ocaml-platform#536]
Hey, could you include VSIX files in next releases so it can get [included](https://github.com/cdr/code-server/issues/2010#issuecomment-745450704) in code-server marketplace?

**Comment by mnxn** [comment]
I created a PR to do this automatically: https://github.com/ocamllabs/vscode-ocaml-platform/pull/537

In the meantime, I manually uploaded the VSIX for the 1.6.0 release:
https://github.com/ocamllabs/vscode-ocaml-platform/releases/tag/v1.6.0

**Comment by crackcomm** [comment]
Thank you :heart:
