### ISSUE TITLE
Keep highlighting the Cinaps-style comments

### ISSUE THREAD

**Issue by smorimoto** [ocamllabs/vscode-ocaml-platform#546]
I wrote "keep" in the title, but I have no strong opinion on this. But if there is a valid OCaml source, I think it's not a bad idea to keep highlighting it.
https://github.com/ocaml-ppx/cinaps

**Comment by rgrinberg** [comment]
Yeah this would be quite useful. @mnxn is it possible to highlight code inside comments?

**Comment by mnxn** [comment]
Yes it is. It should be fairly straight forward to add a new comment type to the existing comment highlighting.

**Comment by smorimoto** [comment]
Thanks @mnxn
