### ISSUE TITLE
v.1.7.0 seems unable to find switches

### ISSUE THREAD

**Issue by clarksmr** [ocamllabs/vscode-ocaml-platform#549]
**The problem:** after updating from 1.6.0 to 1.7.0, VS Code no longer shows any feedback on OCaml code. No problems, warnings, etc. Further investigation shows that it shows no OPAM switches. Putting a `.vscode/settings.json` with the right switch in place does not solve the problem.

Reverting to 1.6.0 does suffice as a workaround.

I teach an OCaml class with 425 students, and they started yelling an hour ago, so it's not just me. :)

**Screenshots:**

v1.6.0:
<img width="1713" alt="Screen Shot 2021-03-07 at 4 54 05 PM" src="https://user-images.githubusercontent.com/6808228/110256236-ca74aa80-7f65-11eb-843f-6a46cdf91454.png">

v1.7.0:
<img width="1713" alt="Screen Shot 2021-03-07 at 4 53 23 PM" src="https://user-images.githubusercontent.com/6808228/110256237-cba5d780-7f65-11eb-9b87-2c0e73a9b607.png">

**Comment by mnxn** [comment]
Thank you for the report. I believe I have found the problem.

Terribly sorry for the inconvenience.

**Comment by mnxn** [comment]
Hi, version 1.8.0 has now been published with a fix.

**Comment by clarksmr** [comment]
Out of curiosity, why does 1.8.0 take several minutes to initialize and install?

**Comment by mnxn** [comment]
The extension now uses a single private switch (under `~/.vscode-ocaml`) for ocamllsp and ocamlformat binaries (PR https://github.com/ocamllabs/vscode-ocaml-platform/pull/463). Installing `ocaml-lsp-server` or `ocamlformat` manually is no longer necessary.

The benefit is that the tools are automatically updated and do not interfere with development opam switches.
