### ISSUE TITLE
Automatic toolchain setup fails when bwrap is unavailable

### ISSUE THREAD

**Issue by tominated** [ocamllabs/vscode-ocaml-platform#554]
Hey folks. While the automatic toolchain installation is a really cool feature, I've found that it's broken the plugin for me using WSL due to `bwrap` not being available in that environment. I had to install opam with the `--disable-sandboxing` flag for it to run in this environment, but it seems the plugin doesn't use that instance of opam and tries to create the switch with sandboxing resulting in this error:

> The creation of the toolchain Opam switch failed: Command failed with [NOTE] Will configure from built-in defaults.
> [ERROR] Missing dependencies -- the following commands are required for opam to operate: - bwrap: Sandboxing tool bwrap was not found. You should install 'bubblewrap'. See https://opam.ocaml.org/doc/FAQ.html#Why-does-opam-require-bwrap. See output channel for more details

Is there a way to disable the automatic toolchain installation and revert to using the lsp server installed in the current switch?

**Comment by tmattio** [comment]
> Is there a way to disable the automatic toolchain installation and revert to using the lsp server installed in the current switch?

Yes, it was an oversight not to provide an escape hatch. We'll release a new version soon that will make the new workflow optional. Sorry about that!

**Comment by tominated** [comment]
awesome, thanks for the super quick response @tmattio!
