### ISSUE TITLE
Automatic toolchain setup delays the sandbox selection

### ISSUE THREAD

**Issue by Khady** [ocamllabs/vscode-ocaml-platform#556]
I've two gobal opam switches, 4.09 and 4.11. The 4.09 one is selected by default as that's what I configured in the passed. The automatic toolchain setups correctly creates a hidden 4.09 switch with ocamllsp and ocamlformat. Later I decide to switch to a different sandbox. I pick the 4.11 opam switch. The automatic toolchain setup is triggered again. It works correctly. But until the whole setup is finished, the sandbox is not moved from 4.09 to 4.11. I've to wait until 4.11+ocamllsp+ocamlformat are all compiled. I'd prefer if the 4.11 sandbox was immediately selected and the setup would happen after.

**Comment by yannl35133** [comment]
This seems irrelevant now that the automatic toolchain setup was removed

**Comment by tmattio** [comment]
Closing this since the automatic toolchain was reverted.
