### ISSUE TITLE
Issues related to automatic toolchain setup

### ISSUE THREAD

**Issue by peter-jerry-ye** [ocamllabs/vscode-ocaml-platform#557]
Hello, I have several issues related to the recently introduced automatic toolchain setup.

First of all, the ml/mli switch does not work anymore. There's a notification showing 'ocamllsp is not running'. Reverting back to 1.6.0 will fix the problem.

Secondly, there's no configuration inside vscode for declaring the repository, which is essential as I'm using a mirror service to accelerate the download speed. I think it should either copy from/link to the global reposconfig or add an option for the extension. (I know how to modify the config file, but it could be annoying for new users who are learning with old materials and who are unaware of the existence of this hidden root).

Also, despite the fact that I've chosen to use the default switch and I have everything installed (it worked perfectly with v1.6.0), the extension still proceeded to update the toolchain, which makes it slower to start. Is there any better solutions?

Thanks.

**Comment by peter-jerry-ye** [comment]
And I had same issue with #553

**Comment by peter-jerry-ye** [comment]
> Did you manage to resolve it?

No, but after having modified some files, it somehow refreshed and worked.

**Comment by tmattio** [comment]
Thanks for the issue @peter-jerry-ye 

> There's a notification showing 'ocamllsp is not running'.

Can you provide the logs? Are you using the ocamllsp in your sandbox or the one installed for you in the toolchain?

> Secondly, there's no configuration inside vscode for declaring the repository, which is essential as I'm using a mirror service to accelerate the download speed. I think it should either copy from/link to the global reposconfig or add an option for the extension.

A setting seems fine to me, new users will probably just use the default, so it's fine if it's not exposed when onboarding.

> the extension still proceeded to update the toolchain

We'll push a release that makes the toolchain optional in the next days

**Comment by peter-jerry-ye** [comment]
> Are you using the ocamllsp in your sandbox or the one installed for you in the toolchain?
Could you tell me how to distinguish it?

I checked again and it seems that the notification showing 'ocamllsp is not running' will appear if and only if I press mi/mli button before the log says

>  "Everything as up-to-date as possible (run with --verbose to show unavailable upgrades).\nHowever, you may \"opam upgrade\" these packages explicitly, which will ask permission to downgrade or uninstall the conflicting packages.\nNothing to do.\n# Run eval $(opam env --root=/home/zihang/.vscode-ocaml/opam) to update the current shell environment\n"

So it seems that the notification has nothing to do with the mi/mli button. The button simply doesn't work. I didn't find any relevant log in the output channels.

**Comment by tmattio** [comment]
The automatic toolchain setup has been reverted and the next version will have a very different workflow, so closing for now.
