### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by dalev** [ocamllabs/vscode-ocaml-platform#569]
The ocaml.switch-impl-intf command appears not to do anything.  The below was generated from the 'Report Issue' link in VS Code's 'Running Extensions' window.

- Issue Type: `Bug`
- Extension Name: `ocaml-platform`
- Extension Version: `1.8.1`
- OS Version: `Linux x64 5.8.0-7642-generic`
- VSCode version: `1.54.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 106,
		"activateCallTime": 3,
		"activateResolvedTime": 7,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ocamllabs.ocaml-platform",
				"_lower": "ocamllabs.ocaml-platform"
			},
			"activationEvent": "onLanguage:ocaml"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "The input parameter for ocamllsp/switchImplIntf is invalid"
		},
		{
			"name": "Error",
			"message": "The input parameter for ocamllsp/switchImplIntf is invalid"
		}
	]
}
```

**Comment by mnxn** [comment]
Already reported in https://github.com/ocamllabs/vscode-ocaml-platform/issues/559 and was fixed in https://github.com/ocamllabs/vscode-ocaml-platform/pull/561.

The fix will be part of the next release.

**Comment by dalev** [comment]
Thanks!
