### ISSUE TITLE
syntax hightlight of let expressions with patterns

### ISSUE THREAD

**Issue by arbipher** [ocamllabs/vscode-ocaml-platform#571]
For example, in this piece of code

```ocaml
let a = foo in
let b1,b2 = bar in
let c = baz in
let d1,d2 = goo in
blabla
```

`b1` and `b2` don't share the same color with `a` and `c`.
I am thinking a uniform color of binders in let expressions helps readability.

**Comment by mnxn** [comment]
The syntax highlighting of bindings is intentionally simple right now. Highlighting all types of pattern bindings is too complex and fragile for the regex-based grammar.

Complete binding highlighting could be possible with semantic highlighting if it gets implemented: https://github.com/ocaml/ocaml-lsp/issues/326

**Comment by arbipher** [comment]
I see.
I saw the other issue on highlighting and I thought it's on syntax so I created a new issue.
It's understandable it's complex for the regex-based grammar.
however, it's still fresh to me that it's the vscode extention rather than the language server doing the parsing (based on the little knowledge I know about them)
let's wait for the semantics highlighting.

**Comment by rgrinberg** [comment]
@mnxn can we close this now since we have semantic highlighting?

**Comment by mnxn** [comment]
Yes, you can close the issue.

All of the binding names in the example now have the `variable` semantic token type and are highlighted the same.
