### ISSUE TITLE
Is it possible to set where the `.vscode-ocaml` is located?

### ISSUE THREAD

**Issue by idkjs** [ocamllabs/vscode-ocaml-platform#572]
The `.vscode-ocaml` folder on this machine is 5.67GB. I can't seem to find in this code where that directory is being set. Is it a vscode setting?

![Screen Shot 2021-03-26 at 10 23 10 AM](https://user-images.githubusercontent.com/2370391/112610842-6edb6580-8e1d-11eb-88cd-a2230965eb81.png)

Thanks for any guidance.

In the meantime,I'm trying to move it to the external SSD then symlinking it to home, `ln -s /Volumes/SSD/.vscode-ocaml $HOME/`.

**Comment by tmattio** [comment]
The directory should be located in your home directory `~/.vscode-ocaml`.

However, if you're on version `1.8.1` or `1.8.2` of the extension, it should not be used anymore and can be deleted safely.

**Comment by idkjs** [comment]
Great. Thank you, @tmattio.
