### ISSUE TITLE
The extension Bracket Pair Colorizer 2 doesn't work on a *.ml file in remote-wsl

### ISSUE THREAD

**Issue by arbipher** [ocamllabs/vscode-ocaml-platform#580]
I am not confident whether here is the correct place to submit this issue.

I have OCaml Platform extension working for both the projects
1. in windows with OCaml for Window(ocaml-env)
2. in remote-WSL with OCaml installed inside wsl

I have [Bracket Pair Colorizer 2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2) extension working for both files in projects
1. all files e.g `*.md` `*.json` `*.ml` in windows
2. all files e.g `*.md` `*.json` **except for `*.ml`** in remote-WSL  (with this [fix](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues/163))

The only combination of conditions is remote-WSL and `*.ml` file, so I am guessing is it possible that some setting is overridden in this mode so other extensions shadowed.
I wish I could pinpoint the exact reason for this. It also looks a bit odd to me to say another extension doesn't work well here.

**Comment by mnxn** [comment]
I've seen this too.

I don't think this is an issue with our extension. We use a standard VSCode language specification and we don't have any WSL-specific code.

My guess why it's not working for `*.ml` files is that Bracket Pair Colorizer always gets loaded either before or after OCaml platform (based on extension ID). I've seen some warning messages in the VSCode log about Bracket Pair Colorizer's use of WASM, so it's possible that extension is doing something incorrectly.
