### ISSUE TITLE
Operator type tool-tip appears after hitting space anywhere in editor

### ISSUE THREAD

**Issue by carljohnesan** [ocamllabs/vscode-ocaml-platform#582]
Bug reproduction:
Just open vscode, with this extension enabled of course, create `.ml` file and paste the following content:
```ml
let four = 2 + 2


```
Hit space at last line and you'll see operator type hover like below:
![bug-screen](https://user-images.githubusercontent.com/47556468/114379661-bdb12b00-9b91-11eb-882a-b0e284349676.png)

It happens not only with addition `+` operator, but with all built-in operators.
Hope this will be fixed. First noticed it when was writing comment, really annoying to hit escape every time after space to hide this type tool-tip.
Thank you in advance.

**Comment by tmattio** [comment]
@mnxn I think this should be fixed on LSP right? (since the signature help does not have any custom logic in the extension)

**Comment by mnxn** [comment]
@tmattio: That's right. I'm not sure if Merlin allows us to determine if we're on a new line though.

@carljohnesan: If you'd like, you can disable the feature completely for OCaml files by adding this to your `settings.json`:

```ocaml
"[ocaml]":{
	"editor.parameterHints.enabled": true
}
```

**Comment by carljohnesan** [comment]
@mnxn Oh, thanks! It works and I'm fine with that solution, so I guess I should close the issue
