### ISSUE TITLE
LSP wishlist

### ISSUE THREAD

**Issue by d4hines** [ocamllabs/vscode-ocaml-platform#584]
The following would make for a much nicer experience:

- Automatically installing ocaml-lsp-server and ocamlformat (but especially the lsp server) when it's not detected.
- Allowing multiple projects. A monorepo might have many ocaml projects, some with Rescript, some with opam, some with esy, etc. I currently have to open each folder in a new VS Code window for things to work correctly. It would be nice of the extension could figure out the right thing to do.

**Comment by mnxn** [comment]
For your first point, we had automatic installation functionality but it was reverted because it needed some tweaking. It'll come back eventually.

For the second, we have an open issue (https://github.com/ocamllabs/vscode-ocaml-platform/issues/581) you can track.

**Comment by d4hines** [comment]
Cool. Will close this issue then. Thanks
