### ISSUE TITLE
Auto-indentation rules

### ISSUE THREAD

**Issue by scen** [ocamllabs/vscode-ocaml-platform#60]
When I write the following, the line with ```type t``` doesn't auto indent when I hit enter after ```struct```.

```ocaml
module X = struct
type t
end
```
Below is what I would expect - is it possible to get this feature? Or is it a problem with my environment?

```ocaml
module X = struct
  type t
end
```

**Comment by imbsky** [comment]
I don't think it's a problem with your environment.

**Comment by imbsky** [comment]
@scen You mean you want it to work like this?
![Screen Recording 2020-03-17 at 11 34 38](https://user-images.githubusercontent.com/38746192/76816557-e3131e80-6843-11ea-81fe-c99a584035c3.gif)

**Comment by scen** [comment]
Yeah, that looks great.

**Comment by imbsky** [comment]
I already opened a PR to fix this so it should be fixed in master soon.

**Comment by scen** [comment]
Hmm, I took a look at #63. I think that it's a good change to make, but I don't think this fixes the underlying issue I was talking about. In general (and not just for some snippets), editors I've used always auto-indent the next line based on context, e.g., in the example below, after hitting `enter` after the `=` sign, currently I get
```ocaml
let f x =
(* not automatically indented *)
```
But I would expect
```ocaml
let f x =
    (* automatically indented *)
```
I would expect the same with anything, e.g. an if/else block, etc

I suspect a fix would be non-trivial; I took a look at the vscode-ocaml extension, which although deprecated, manages to auto-indent by invoking ocp-ident (https://github.com/hackwaly/vscode-ocaml/blob/85483d4311846285e30e71cf18cb2f5a1eaf9371/src/extension.ts#L23) Maybe this plugin can use ocamlformat instead, though.

**Comment by scen** [comment]
An alternative solution could be to use indentation rules in the syntax definition, e.g: https://code.visualstudio.com/api/language-extensions/language-configuration-guide#indentation-rules

**Comment by imbsky** [comment]
I didn't know if which solution is the best so I made minimal and necessary changes. Perhaps we should ask @rgrinberg. What do you think?

**Comment by imbsky** [comment]
> An alternative solution could be to use indentation rules in the syntax definition, e.g: > https://code.visualstudio.com/api/language-extensions/language-configuration-guide#indentation-rules

I think this solution is good.

**Comment by scen** [comment]
Could try stealing this: https://github.com/whitequark/sublime-better-ocaml/blob/master/Indent%20rules.tmPreferences

**Comment by imbsky** [comment]
Sure, I will try it later.

**Comment by rgrinberg** [comment]
@imbsky the solution sounds fine to me as well.

**Comment by imbsky** [comment]
@rgrinberg Just opened a PR!

**Comment by liweijian** [comment]
![fun_with_fun](https://user-images.githubusercontent.com/19320783/89008204-d8fa4400-d33c-11ea-8ed8-ca275ae15b6f.gif)

I wrote a function after another function as follows:

```
let f1 x =
  x + 1


  let f2 y =
    y + 2
```

@smorimoto  Just wondering if maybe we could let the second function `f2` indent automatically?

**Comment by CraigFe** [comment]
In addition to the lack of automatic outdenting described by @liweijian above, I'm also seeing an issue with a failure to indent after certain patterns.

![image](https://user-images.githubusercontent.com/26125912/103481030-6fdd9780-4dd8-11eb-995b-38f0849791d1.png)

Looks like `Ppat_any` and `Ppat_var` work fine, but other pattern types are not supported. Perhaps we should open issues for these?

I'm happy to work on a fix for this if someone can point me to the right area of the code.

**Comment by rgrinberg** [comment]
The indentation rules in vscode are regex based, and are too simple to support more complex indentation patterns. We need is to support the `textDocument/onTypeFormatting` query in lsp in this case. Unfortunately, ocamlformat is not able to give us information to support this query at the moment. We could consider using ocp-indent, but it would only be a temporary solution.
