### ISSUE TITLE
Concurrency issue: cannot read switch list

### ISSUE THREAD

**Issue by yannl35133** [ocamllabs/vscode-ocaml-platform#607]
Problem: "Unable to read the list of switches."
Reason: `/usr/local/bin/opam switch list -s --root "Another process has locked /home/common/yann/.opam/common/.opam-switch/packages/cache, waiting (C-c to abort)... lock acquired.
/home/common/yann/.opam"`

Problem: Root is `"Another process has locked /home/common/yann/.opam/common/.opam-switch/packages/cache, waiting (C-c to abort)... lock acquired.
/home/common/yann/.opam"`
Reason: `opam var root` is called to early (this directly follows an integrated "upgrade packages" call)

My primitive search tends to lead to https://github.com/ocamllabs/vscode-ocaml-platform/blob/2d413e5d3033d4b33c442667082f84ee3a4ca625/src/opam.ml#L22-L29

Things to note: `opam 2.1.0~beta4`

**Comment by tmattio** [comment]
Thanks for the report!

I doubt `opam var root` is the culprit here, I don't think it even acquires the lock.

I'm not sure how you can have two concurrent opam runs with the current version (unless you installed/upgraded a package from the UI?). Can you confirm you're using `1.8.4` and you weren't running opam outside of VSCode?

**Comment by tmattio** [comment]
Additionally, the logs would be very useful to investigate the issue 🙂

**Comment by yannl35133** [comment]
I can assure you, running `opam update` and then `opam var root` in another console concurrently, it does acquire the lock.
I am using OCaml Platform 1.8.4
If caching is involved, I can't assert that opam wasn't running when VSCode was launched, but I can assert that I refreshed the switch list without opam running to no avail.

I don't know which logs you are talking about, happy to give them if you tell me which

**Comment by tmattio** [comment]
> running opam update and then opam var root in another console concurrently, it does acquire the lock.

Ugh.. Ok

> I don't know which logs you are talking about, happy to give them if you tell me which

They are under the `OCaml Platform Extension` tab in the `Output` console:

![image](https://user-images.githubusercontent.com/6162008/117338588-09a87480-ae9f-11eb-9bf4-d7e69667f454.png)

**Comment by yannl35133** [comment]
I closed VSCode, and to recreate the bug I had to launch `opam update` concurrently (before opening VSCode).
So this is probably the bug.

Here, the launch + me spamming "refresh switch list"
```external command {
  "bin": "which",
  "args": [
    "ocamllsp"
  ]
}

external command (finished) {
  "bin": "which",
  "args": [
    "ocamllsp"
  ],
  "result": {
    "exitCode": 0,
    "stdout": "/home/common/yann/.opam/common/bin/ocamllsp\n",
    "stderr": ""
  }
}

external command {
  "bin": "ocamllsp",
  "args": []
}

external command {
  "bin": "/usr/local/bin/opam",
  "args": [
    "var",
    "root"
  ]
}

external command {
  "bin": "/usr/local/bin/opam",
  "args": [
    "var",
    "root"
  ]
}

external command (finished) {
  "bin": "/usr/local/bin/opam",
  "args": [
    "var",
    "root"
  ],
  "result": {
    "exitCode": 0,
    "stdout": "Another process has locked /home/common/yann/.opam/lock, waiting (C-c to abort)... lock acquired.\n/home/common/yann/.opam\n",
    "stderr": ""
  }
}

external command (finished) {
  "bin": "/usr/local/bin/opam",
  "args": [
    "var",
    "root"
  ],
  "result": {
    "exitCode": 0,
    "stdout": "Another process has locked /home/common/yann/.opam/lock, waiting (C-c to abort)... lock acquired.\n/home/common/yann/.opam\n",
    "stderr": ""
  }
}

external command {
  "bin": "/usr/local/bin/opam",
  "args": [
    "switch",
    "list",
    "-s",
    "--root",
    "Another process has locked /home/common/yann/.opam/lock, waiting (C-c to abort)... lock acquired.\n/home/common/yann/.opam"
  ]
}

external command (finished) {
  "bin": "/usr/local/bin/opam",
  "args": [
    "switch",
    "list",
    "-s",
    "--root",
    "Another process has locked /home/common/yann/.opam/lock, waiting (C-c to abort)... lock acquired.\n/home/common/yann/.opam"
  ],
  "result": {
    "exitCode": 50,
    "stdout": "",
    "stderr": "[ERROR] Opam has not been initialised, please run `opam init'\n"
  }
}

external command {
  "bin": "/usr/local/bin/opam",
  "args": [
    "switch",
    "list",
    "-s",
    "--root",
    "Another process has locked /home/common/yann/.opam/lock, waiting (C-c to abort)... lock acquired.\n/home/common/yann/.opam"
  ]
}

external command (finished) {
  "bin": "/usr/local/bin/opam",
  "args": [
    "switch",
    "list",
    "-s",
    "--root",
    "Another process has locked /home/common/yann/.opam/lock, waiting (C-c to abort)... lock acquired.\n/home/common/yann/.opam"
  ],
  "result": {
    "exitCode": 50,
    "stdout": "",
    "stderr": "[ERROR] Opam has not been initialised, please run `opam init'\n"
  }
}

external command {
  "bin": "/usr/local/bin/opam",
  "args": [
    "switch",
    "list",
    "-s",
    "--root",
    "Another process has locked /home/common/yann/.opam/lock, waiting (C-c to abort)... lock acquired.\n/home/common/yann/.opam"
  ]
}

external command (finished) {
  "bin": "/usr/local/bin/opam",
  "args": [
    "switch",
    "list",
    "-s",
    "--root",
    "Another process has locked /home/common/yann/.opam/lock, waiting (C-c to abort)... lock acquired.\n/home/common/yann/.opam"
  ],
  "result": {
    "exitCode": 50,
    "stdout": "",
    "stderr": "[ERROR] Opam has not been initialised, please run `opam init'\n"
  }
}
```

**Comment by tmattio** [comment]
Ok, that makes more sense, thanks for the repro and the logs!

I see we take all of the output of `opam var root` (and probably other commands for which we are only interested in a single line output), when we should only take the last one.

```
  "args": [
    "switch",
    "list",
    "-s",
    "--root",
    "Another process has locked /home/common/yann/.opam/lock, waiting (C-c to abort)... lock acquired.\n/home/common/yann/.opam"
  ],
```

Doing this should solve the issue, the calls seem to be blocking, which is what is expected.

**Comment by yannl35133** [comment]
Seeing it first hand, I can confirm that (at least `opam var root`) is blocking

**Comment by tmattio** [comment]
I think this is the expected behavior: opam locks the global state, so if there is another process running, VSCode will fail to execute opam commands that need access to the global state.
