### ISSUE TITLE
esy sandbox doesn't show if there is no opam file

### ISSUE THREAD

**Issue by EduardoRFS** [ocamllabs/vscode-ocaml-platform#635]
Currently the esy sandbox will not appear on the list if there is no `.opam` on the folder, while the `.opam` file is needed for generating the `.install` on dune it's not needed for local projects. So this endsup being a hard problem to debug.

**Comment by mnxn** [comment]
Based on the code, it should detect an esy sandbox if there is an `_esy` folder and an `esy.json`/`package.json` file. Is this not the case?

https://github.com/ocamllabs/vscode-ocaml-platform/blob/f5337ddbc7c9f54b682f72d1616ebb471f8ee3c7/src/sandbox.ml#L246-L252

https://github.com/ocamllabs/vscode-ocaml-platform/blob/f5337ddbc7c9f54b682f72d1616ebb471f8ee3c7/src/esy.ml#L128-L133

**Comment by tmattio** [comment]
I think @mnxn solution should work. If you have an `_esy` directory, the Esy sandbox should be detected. Closing for now, but reopen if it doesn't work.
