### ISSUE TITLE
Script for automatically generate vscode api bindings

### ISSUE THREAD

**Issue by hackwaly** [ocamllabs/vscode-ocaml-platform#647]
I'm working on integrating ocamlearlybird into vscode-ocaml-platform. I found it's boring to handcraft the vscode api bindings. Is there any script to automatically done this?

**Comment by smorimoto** [comment]
We already have a tool called ts2ocaml, which is not publicly released yet, but we have a plan to use it. I can invite you to the repository if you are interested.

**Comment by ulugbekna** [comment]
If the bindings you need are present in #618, that'd be quite an incentive for that PR to be merged

**Comment by hackwaly** [comment]
@ulugbekna Yes. The bindings I need are present in #618. So I can update my MR to based on #618.
