### ISSUE TITLE
Intellisenses doesn't update after dune built

### ISSUE THREAD

**Issue by vincentdchan** [ocamllabs/vscode-ocaml-platform#658]
Intellisenses doesn't update after dune built. I have to edit the source files, the intellisenses update. Reloading the VSCode window can update intellisenses.

**Comment by ulugbekna** [comment]
Which version of ocamllsp do you use? If you're on the latest version, try
saving your source file to see to get latest diagnostics.

**Comment by vincentdchan** [comment]
I am using the latest version `1.8.4`.
Saving the file can trigger update, but not a very good experience. For example, I add a function in `a.ml`, and call this function in `b.ml`. But the diagnostics give errors. I have to
1. rebuild the project with dune
2. do some editing, and the diagnostics updates.

I don't want the step2

**Comment by ulugbekna** [comment]
If you use Dune, run `dune build --watch` to run the build in polling mode.
This solves your problem.

**Comment by vincentdchan** [comment]
Well, that would be a solution. Thanks.

**Comment by ulugbekna** [comment]
We're working on a tighter integration with dune in OCaml-lsp, so this
process should become easier in the future.

**Comment by vincentdchan** [comment]
Wow, can't waiting to use it!
