### ISSUE TITLE
go to definition not working

### ISSUE THREAD

**Issue by mimoo** [ocamllabs/vscode-ocaml-platform#663]
Hello,

I often have this problem, where "go to definition" and other features don't work. Often, it's because I haven't built the relevant files, but sometimes even building them doesn't seem to unlock these features in vscode. In comparison, Rust with vscode works out-of-the-box with rust-analyzer and I don't have to manually build anything. Other times, only some parts are accessible because of compiler flags (for example if using https://github.com/janestreet/ppx_optcomp then only some parts will be available). It also looks like when an executable test doesn't pass, no feature is available.

Am I doing something wrong or is this a limitation of OCaml?

**Comment by ulugbekna** [comment]
> I often have this problem, where "go to definition" and other features don't work. Often, it's because I haven't built the relevant files, ...

Currently, [Merlin](https://github.com/ocaml/merlin), the backend of ocaml-lsp & vscode-ocaml-platform, responsible for completion, go-to-definition, etc. features, needs the project built with dune to work correctly.

>  Other times, only some parts are accessible because of compiler flags (for example if using https://github.com/janestreet/ppx_optcomp then only some parts will be available). It also looks like when an executable test doesn't pass, no feature is available.

If you can give us a reproducible case, we can have a look. It would also be helpful, whenever, you see something "not working" in ocaml-lsp, go to the `Output` pane (next to `Terminal`) in vscode, pick `OCaml Language Server` and see if there are any requests failing, exceptions thrown, and report back.

At this point I'm not sure how to act on this ticket.

**Comment by mimoo** [comment]
I figured these were known limitations :o
