### ISSUE TITLE
lsp not working on menhir files anymore

### ISSUE THREAD

**Issue by EduardoRFS** [ocamllabs/vscode-ocaml-platform#691]
## Problem

I may be wrong but I have the impression that it did work previously, but since some version .mly files currently have only syntax highlighting, but not LSP features like auto complete.

**Comment by mnxn** [comment]
> I have the impression that it did work previously

It didn't.

The [supported file extensions](https://github.com/ocaml/ocaml-lsp/blob/c39565edc47684d48c7f4ce1eec4039402a706e4/ocaml-lsp-server/src/document.ml#L10-L17) for LSP features are `.ml`, `.eliom`, `.re`, `.mli`, `.eliomi`, and `.rei`.

OCamllex and Menhir can switch to/infer interfaces, but they do not have formatting or auto-completion.

**Comment by rgrinberg** [comment]
Moreover, lsp needs support in merlin before we can even start supporting it properly.
