### ISSUE TITLE
Local switches not detected on opam 2.1

### ISSUE THREAD

**Issue by debugnik** [ocamllabs/vscode-ocaml-platform#701]
I just upgraded to opam 2.1, created a new local switch at the root of the project, installed `ocaml-lsp-server` and realised that I can't select the local switch for use with the extension. Non-local switches seem to work as usual.

I first tried to work around it using a custom sandbox `eval $(opam env) && $prog $args`. This allowed me to create terminals on the local switch, and `which ocamllsp` shows the correct path to the LSP server, but the extension still fails to start it, notifying me that "ocaml-lsp-server is not installed".

For reference, I'm using `ocamllabs.ocaml-platform` v1.8.4 on VS Code 1.60.0 and `ocaml-lsp-server` 1.7.0.

**Comment by tatchi** [comment]
Hi @debugnik,

I experienced something similar when I upgraded to opam 2.1. Re-installing opam fixed it for me.

Out of curiosity, what's the result of `opam var` ?

**Comment by tmattio** [comment]
I'll close this for now. @debugnik feel free to re-open if @tatchi's solution does not work for you.

**Comment by debugnik** [comment]
I didn't actually have the issue again, even without reinstalling opam, until today that I've accidentally figured out the repro: It happens only when there aren't any global switches in opam. I can reproduce it with the following session:

```sh
# Start out without any global switches.
opam switch create . 4.13.1
# Open Code, can't select local switch at '.',
# it's missing on both the select command and tree view.
opam switch create 4.13.1
# Reload Code, can select either '.' or 4.13.1.
opam switch remove 4.13.1
# Reload Code, can't select '.' anymore.
```

This is on `ocamllabs.ocaml-platform` v1.8.4, opam 2.1.2 and `ocaml-lsp-server` 1.9.1 running on WSL 2. I'd re-open the issue, but I can't because I didn't close it myself.

@tatchi, [here's my output for `opam var` on the local switch](https://gist.github.com/debugnik/7331606e2534da6b0dcdee60076fecbd), both without any global switches and the diff after adding one.

**Comment by Khady** [comment]
```external command {
  "bin": "/home/louis.roche/bin/opam",
  "args": [
    "var",
    "root"
  ]
}

external command (finished) {
  "bin": "/home/louis.roche/bin/opam",
  "args": [
    "var",
    "root"
  ],
  "result": {
    "exitCode": 50,
    "stdout": "",
    "stderr": "[ERROR] No switch is currently set. Please use 'opam switch' to set or install a switch\n"
  }
}
```
