### ISSUE TITLE
Formatting doesn't work even with ocamlformat installed and `.ocamlformat` present

### ISSUE THREAD

**Issue by Jules-Bertholet** [ocamllabs/vscode-ocaml-platform#709]
# Expected behavior
Running "Format Document" on an OCaml `.ml` file formats it with `ocamlformat`

# Actual behavior
Running "Format Document" on an OCaml `.ml` file does nothing

# Notes
`.ocamlformat` is present and `ocamlformat` is installed. Running `ocamlformat -i source_file` manually works just fine
OS: Fedora 34

**Comment by rgrinberg** [comment]
Did you enable formatting in your dune project?

**Comment by tmattio** [comment]
@Jules-Bertholet Could you confirm that you're running ocamlformat in the same switch as the selected sandbox in VSCode?

**Comment by Jules-Bertholet** [comment]
I've since figured out the cause of this; my `ocamlformat` version was too old (caused by having Ocaml 3.11 installed, which only supported an older version). Switching to an OCaml 3.12 opam switch allowed me to install a newer `ocamlformat` and resolve the issue.

Maybe there should be a warning if the version of dependencies installed is too low, or at the very least the minimum supported versions should be documented somewhere?

**Comment by tmattio** [comment]
Thanks for the follow up @Jules-Bertholet 🙂 A note on the README that don't support < 3.12 sounds enough. A PR for this would be welcome - closing the issue for now
