### ISSUE TITLE
"open ast explorer" doesn't work

### ISSUE THREAD

**Issue by EduardoRFS** [ocamllabs/vscode-ocaml-platform#729]
It may be that I build it wrong or some interaction with esy. But when I try `open ast explorer` it fails with the error

> Unable to open 'x.ml': Assertion Failed: argument is undefined or null.

**Comment by tmattio** [comment]
Thanks for the report @EduardoRFS - could you give the steps to reproduce the issues (e.g. a repo with a minimal project that reproduces)?

**Comment by EduardoRFS** [comment]
@tmattio https://github.com/EduardoRFS/open-ast-explorer-repro-bug just try to trigger the `open ast explorer` menu

**Comment by ulugbekna** [comment]
okay, the problem is that the `index.html` for the ast explorer is hardcoded in `astexplorer/dist/`, but the directory doesn't exist unless one calls `npm run build` from `astexplorer/`, which fixes the problem.

We now need to figure out how to make sure we do that for an extension release
