### ISSUE TITLE
Outreachy Winter 2021 Information

### ISSUE THREAD

**Issue by tmattio** [ocamllabs/vscode-ocaml-platform#735]
This issue gives some information about the Outreachy application period.

If you're an Outreachy applicant who would like to contribute to the project: welcome! 🥳 

# For applicants

### Where to find issues

The good first issues should be good candidates for the application period: https://github.com/ocamllabs/vscode-ocaml-platform/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

### First Steps

First of all, to contribute to the project you'll need to get OCaml up and running. If you haven't already done that, you can have a look at the [Up and Running With OCaml](https://v3.ocaml.org/tutorials/up-and-running-with-ocaml) page on the ocaml.org site.

### How to Contribute

Once you got OCaml up and running, you can start working on an issue on one of those repos mentioned above. For that, just have a look at the conversation of the issue to see if there's already someone currently working on it. If not, you can write a quick comment stating that you'll start working on the issue and do so.

### Where to ask

The documentation might not always be straightforward. That's even more of a reason to never hesitate to ask questions! If you have a question concerning one concrete issue, you can just ask on the issue. For general questions, you can ask on Discord, which you can access via [this invitation link](https://discord.gg/fMEeySfdQd). Once you've joined Discord, if you have a question about VSCode or a general question that's not related to some issue, you can ask on the [Outreachy channel](https://discord.com/channels/436568060288172042/826460290367357008).

## Mentors

You have two mentors for the application period and for the internship: @tmattio and @gs0510. We're both very excited about having Outreachy applicants and later an Outreachy intern contributing to VSCode! On weekends we tend to be non- or less available.

## For Non-applicants

Outreachy is an initiative to give folks from under-represented groups in open-source the opportunity to do a remote internship in an open-source project. So for open-source communities, Outreachy is a great opportunity to work together with folks from lots of different backgrounds and maybe even grow the community and become more diverse! Outreachy provides the infrastructure for the internships and application process, and the open-source communities need to provide projects and mentoring. One of the projects we -i.e. the OCaml community- is participating with in this Outreachy round consists in adding syntax support for `.eml` files in VSCode. So we might get some Outreachy applicants contributing on this repository from Oct. 8 till Nov. 5. as part of the application process to that project :)

**Credits:** This introductory issue is taken from Ppxlib, which also has an Outreachy project. Thanks @pitag-ha for the work on writing this guide!

**Comment by kirisky** [comment]
Hi, @tmattio ! How to join this program? I've joined the Discord channel.

**Comment by tmattio** [comment]
The Outreachy application period has ended, so I'm closing this. Thank you to all the Outreachy applicant who contributed to the project 🎉
