### ISSUE TITLE
Highlight unreachable element in Cram files

### ISSUE THREAD

**Issue by mlantas** [ocamllabs/vscode-ocaml-platform#748]
Highlight `***** UNREACHABLE *****` in Cram `.t` files.

https://github.com/ocaml/dune/pull/4981#issuecomment-940216656

**Comment by mnxn** [comment]
Making the syntax `name` start with `invalid` (for example `invalid.unreachable.cram`)  will make most vscode themes highlight it in red.

I think that would be the best option if I'm correctly interpreting `***** UNREACHABLE *****` as an error.
