### ISSUE TITLE
inline tests show up with red squigglies

### ISSUE THREAD

**Issue by yminsky** [ocamllabs/vscode-ocaml-platform#782]
Something appears to be broken in support for inline test expressions. The dune file is as it should be, and dune runtest works, and it sometimes does the right thing.

But sometimes, in the midst of editing, I get red-squigglies. And when hovering over it says:

    Uninterpreted extension 'expect_test'.ocamllsp

Any ideas what might be going on here?

![Screenshot from 2021-11-26 14-08-55](https://user-images.githubusercontent.com/715302/143622414-44856f19-942b-4794-9350-a69c8eccec21.png)

The same thing seems to happen with the let%test extension, so I suspect this is a problem for the whole inline-test toolchain.

**Comment by ulugbekna** [comment]
Hi, there was a bug in how we handle ppxes in ocaml-lsp. Could you upgrade your ocaml-lsp (to 1.9.0)?

**Comment by yminsky** [comment]
I'm already running 1.9.1. Anything else I can do to help?

**Comment by yminsky** [comment]
Oh, actually, I upgraded the lsp-server while using vscode, but I hadn't bounced the editor. Having done that, it seems like it all works now. So, never mind...

**Comment by ulugbekna** [comment]
There is also a vscode command "OCaml: Restart Language Server" that you can trigger from vscode command palette (cmd + shift + p) to restart your language server (if you upgraded it or it's acting up somehow)
