### ISSUE TITLE
ocaml-lsp-server cannot be found when installed through esy on Windows

### ISSUE THREAD

**Issue by Faholan** [ocamllabs/vscode-ocaml-platform#785]
I would like to use this extension on Windows.

However, I saw on the `Ocaml for Windows` main page that it is discontinued, and that they recommended using esy, so I installed esy, after installing npm.

My issue is that, even tho I installed esy, and have a package.json like this :
```json
{
  "dependencies": {
    "@opam/ocaml-lsp-server": "1.4.1",
    "ocaml": "4.10.x"
  }
}
```
Every time I start the extension it just fails, saying that it cannot find the server.

The ideal outcome for me would be to be able to use it while having more than one folder open, one of them being the one with the esy sandbox.

However, currently, even if I only have this one folder open, the extension still doesn't pick up the sandbox.

When I try to switch the sandbox, I only have the `Global` option (which doesn't work), and the `Custom` option (but I don't know how I should use that one to make it work).
From what I understood, the extension should be able to pick up the esy sandbox, but it doesn't.

I tried opening only the sandboxed folder, running VSCode from the terminal, but none of these work.

What should I do to make it work ?

**Comment by tmattio** [comment]
> However, I saw on the Ocaml for Windows main page that it is discontinued, and that they recommended using esy, so I installed esy, after installing npm.

Not sure which page you saw, but OCaml on Windows is not discontinued 🙂 And as a matter of fact, there's a lot of improvements for Windows being worked on in the opam repository (https://github.com/ocaml/opam/pulls?q=is%3Apr+is%3Aopen+windows)

That being said, the extension should be able to detect your sandbox if esy is in your PATH and you built the project.

Not sure what's going on. Could you provide some logs (you can read the debugging section of the README here: https://github.com/ocamllabs/vscode-ocaml-platform#problems-with-this-extension-or-opam-support-in-the-extension), and some reproduction steps (a link to a project, set of commands, etc.) that would help us debug the issue.

**Comment by Faholan** [comment]
I saw that "The repository will be discontinued as of August 2021" there : https://fdopen.github.io/opam-repository-mingw/

OS version: Windows 10.0.19043 21H1 Build 19043.1348
VSCode Version: 1.62.3
Ocaml Platform Version: 1.8.4
npm version: 8.1.4
esy version: 0.6.12
ocamllsp version: 1.4.1
Repo for which I'm trying to enable the extension : https://github.com/Faholan/Option-info
`OCaml: Show OCaml Platform Extension Output`: I couldn't find the command
`OCaml: Show OCaml Commands Output`: I couldn't find the command
All the Ocaml comands I have:
![Ocaml commands](https://cdn.discordapp.com/attachments/636974179475914763/914505781095858237/unknown.png)

**Comment by Faholan** [comment]
I'd really like to provide logs, but the commands simply *don't exist*, so I don't know what to do about it

**Comment by Faholan** [comment]
Okay, somebody told me the solution on Discord :
Putting a file named `something.opam` in the project allowed the extension to detect the sandbox, and now it uses it flawlessly.
It even works in multy-folder workspace context.
Thank you for your support !
