### ISSUE TITLE
bug: LSP highlight annotations fail on edit

### ISSUE THREAD

**Issue by cdaringe** [ocamllabs/vscode-ocaml-platform#797]
# Problem

LSP integration halts working full well for some expressions on edit

1. LSP integration works perfectly, on boot
2. VSCode edit is made
3. LSP debug output can no longer find symbol in environment

As noted in the debugging sections of the readme, this could be plainly an LSP issue. In the spirit of completeness and assurance that the issue is filed in the correct place, I will start here, then migrate to the LSP tracker as needed.

# Demonstration

Starting conditions:

- ocaml 4.12
- ocaml-lsp, ocaml-platform, ocamlformat, ocamlformat-rpc, etc are all installed and in the active switch/sandbox
- `dune build --watch --terminal-persistence=clear-on-rebuild` is executing successfully
- the project is using `ppx_deriving` to produce a `show` fn attached to the `Fishies` module
- platform extension is configured LSP for verbose mode
- The editor was closed, relaunched, and the following steps were replayed with minimal other user interactions just to capture the visual failure and associated logs

https://user-images.githubusercontent.com/1003261/145692950-d53c94a6-04ca-444d-9175-ba3a04c80a76.mov

- time 1s: `Fishies.show x` hovered, LSP responds back successfully with signature
- time 4s: a space was added, `Fishies.show  x`, and document was saved
- time 5s: content hovered again
- time 6s `ocamllsp` responds back successfully with signature
- time 7s `ocamllsp` responds back with `Unbound value Fishies.show` 
- VSCode renders _both_ the correct signature, and the latent "unbound value" simultaneously

Debug logs:

```json5
// short version, for improved readability
[Trace - 1:52:55 PM] Sending notification 'textDocument/didSave'.
[Trace - 1:52:56 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 1:52:56 PM] Received response 'textDocument/hover - (25)' in 3ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```ocaml\nint array -> string\n```"
    },
   // ..snip
}
[Trace - 1:52:57 PM] Sending request 'textDocument/codeAction - (26)'.
Params: {
    "context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 28,
                        "character": 21
                    },
                    "end": {
                        "line": 28,
                        "character": 33
                    }
                },
                "message": "Unbound value Fishies.show",
                "severity": 1,
                "source": "ocamllsp"
            }
        ],

```

<details>
<summary>Full Platform LSP logs</summary>
<pre>
[Trace - 1:52:51 PM] Sending request 'textDocument/hover - (15)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml"
    },
    "position": {
        "line": 28,
        "character": 29
    }
}

[Trace - 1:52:51 PM] Received response 'textDocument/hover - (15)' in 2ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```ocaml\nFishies.t -> string\n```"
    },
    "range": {
        "start": {
            "line": 28,
            "character": 21
        },
        "end": {
            "line": 28,
            "character": 33
        }
    }
}

[Trace - 1:52:52 PM] Sending request 'textDocument/hover - (16)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml"
    },
    "position": {
        "line": 28,
        "character": 30
    }
}

[Trace - 1:52:52 PM] Received response 'textDocument/hover - (16)' in 2ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```ocaml\nFishies.t -> string\n```"
    },
    "range": {
        "start": {
            "line": 28,
            "character": 21
        },
        "end": {
            "line": 28,
            "character": 33
        }
    }
}

[Trace - 1:52:52 PM] Sending request 'textDocument/hover - (17)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml"
    },
    "position": {
        "line": 28,
        "character": 33
    }
}

[Trace - 1:52:52 PM] Received response 'textDocument/hover - (17)' in 6ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```ocaml\nFishies.t -> string\n```"
    },
    "range": {
        "start": {
            "line": 28,
            "character": 21
        },
        "end": {
            "line": 28,
            "character": 33
        }
    }
}

[Trace - 1:52:52 PM] Sending request 'textDocument/documentHighlight - (18)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml"
    },
    "position": {
        "line": 28,
        "character": 33
    }
}

[Trace - 1:52:52 PM] Received response 'textDocument/documentHighlight - (18)' in 1ms.
Result: [
    {
        "range": {
            "start": {
                "line": 28,
                "character": 21
            },
            "end": {
                "line": 28,
                "character": 33
            }
        },
        "kind": 1
    }
]

[Trace - 1:52:53 PM] Sending request 'textDocument/codeAction - (19)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml"
    },
    "range": {
        "start": {
            "line": 28,
            "character": 33
        },
        "end": {
            "line": 28,
            "character": 33
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 1:52:53 PM] Received response 'textDocument/codeAction - (19)' in 77ms.
Result: [
    {
        "title": "Type-annotate",
        "kind": "type-annotate",
        "isPreferred": false,
        "edit": {
            "documentChanges": [
                {
                    "textDocument": {
                        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml",
                        "version": 17
                    },
                    "edits": [
                        {
                            "range": {
                                "start": {
                                    "line": 28,
                                    "character": 21
                                },
                                "end": {
                                    "line": 28,
                                    "character": 33
                                }
                            },
                            "newText": "(Fishies.show : Fishies.t -> string)"
                        }
                    ]
                }
            ]
        }
    }
]

##### THIS IS WHERE A SINGLE SPACE WAS ADDED ####

[Trace - 1:52:53 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml",
        "version": 18
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 28,
                    "character": 33
                },
                "end": {
                    "line": 28,
                    "character": 33
                }
            },
            "rangeLength": 0,
            "text": " "
        }
    ]
}

[Trace - 1:52:53 PM] Sending request 'textDocument/signatureHelp - (20)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml"
    },
    "position": {
        "line": 28,
        "character": 34
    },
    "context": {
        "isRetrigger": false,
        "triggerCharacter": " ",
        "triggerKind": 2
    }
}

[Trace - 1:52:53 PM] Received response 'textDocument/signatureHelp - (20)' in 44ms.
Result: {
    "signatures": [
        {
            "label": "Fishies.show : Fishies.t -> string",
            "parameters": [
                {
                    "label": [
                        15,
                        24
                    ]
                }
            ]
        }
    ],
    "activeSignature": 0,
    "activeParameter": 0
}

[Trace - 1:52:53 PM] Sending request 'textDocument/foldingRange - (21)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml"
    }
}

[Trace - 1:52:53 PM] Received response 'textDocument/foldingRange - (21)' in 0ms.
Result: [
    {
        "startLine": 0,
        "startCharacter": 0,
        "endLine": 12,
        "endCharacter": 3,
        "kind": "region"
    },
    {
        "startLine": 3,
        "startCharacter": 2,
        "endLine": 11,
        "endCharacter": 6,
        "kind": "region"
    },
    {
        "startLine": 14,
        "startCharacter": 0,
        "endLine": 29,
        "endCharacter": 3,
        "kind": "region"
    },
    {
        "startLine": 15,
        "startCharacter": 2,
        "endLine": 24,
        "endCharacter": 69,
        "kind": "region"
    },
    {
        "startLine": 26,
        "startCharacter": 2,
        "endLine": 28,
        "endCharacter": 36,
        "kind": "region"
    }
]

[Trace - 1:52:53 PM] Sending request 'textDocument/codeLens - (22)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml"
    }
}

[Trace - 1:52:53 PM] Received response 'textDocument/codeLens - (22)' in 0ms.
Result: [
    {
        "range": {
            "start": {
                "line": 26,
                "character": 2
            },
            "end": {
                "line": 28,
                "character": 36
            }
        },
        "command": {
            "title": "string -> unit",
            "command": ""
        }
    },
    {
        "range": {
            "start": {
                "line": 15,
                "character": 2
            },
            "end": {
                "line": 24,
                "character": 69
            }
        },
        "command": {
            "title": "string list -> int array",
            "command": ""
        }
    },
    {
        "range": {
            "start": {
                "line": 3,
                "character": 2
            },
            "end": {
                "line": 11,
                "character": 6
            }
        },
        "command": {
            "title": "int list -> t",
            "command": ""
        }
    },
    {
        "range": {
            "start": {
                "line": 1,
                "character": 2
            },
            "end": {
                "line": 1,
                "character": 47
            }
        },
        "command": {
            "title": "t -> t -> int",
            "command": ""
        }
    },
    {
        "range": {
            "start": {
                "line": 1,
                "character": 2
            },
            "end": {
                "line": 1,
                "character": 47
            }
        },
        "command": {
            "title": "t -> t -> bool",
            "command": ""
        }
    },
    {
        "range": {
            "start": {
                "line": 1,
                "character": 2
            },
            "end": {
                "line": 1,
                "character": 47
            }
        },
        "command": {
            "title": "t -> string",
            "command": ""
        }
    },
    {
        "range": {
            "start": {
                "line": 1,
                "character": 2
            },
            "end": {
                "line": 1,
                "character": 47
            }
        },
        "command": {
            "title": "Format.formatter -> t -> unit",
            "command": ""
        }
    }
]

[Trace - 1:52:53 PM] Sending request 'textDocument/codeLens - (23)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml"
    }
}

[Trace - 1:52:53 PM] Received response 'textDocument/codeLens - (23)' in 0ms.
Result: [
    {
        "range": {
            "start": {
                "line": 26,
                "character": 2
            },
            "end": {
                "line": 28,
                "character": 36
            }
        },
        "command": {
            "title": "string -> unit",
            "command": ""
        }
    },
    {
        "range": {
            "start": {
                "line": 15,
                "character": 2
            },
            "end": {
                "line": 24,
                "character": 69
            }
        },
        "command": {
            "title": "string list -> int array",
            "command": ""
        }
    },
    {
        "range": {
            "start": {
                "line": 3,
                "character": 2
            },
            "end": {
                "line": 11,
                "character": 6
            }
        },
        "command": {
            "title": "int list -> t",
            "command": ""
        }
    },
    {
        "range": {
            "start": {
                "line": 1,
                "character": 2
            },
            "end": {
                "line": 1,
                "character": 47
            }
        },
        "command": {
            "title": "t -> t -> int",
            "command": ""
        }
    },
    {
        "range": {
            "start": {
                "line": 1,
                "character": 2
            },
            "end": {
                "line": 1,
                "character": 47
            }
        },
        "command": {
            "title": "t -> t -> bool",
            "command": ""
        }
    },
    {
        "range": {
            "start": {
                "line": 1,
                "character": 2
            },
            "end": {
                "line": 1,
                "character": 47
            }
        },
        "command": {
            "title": "t -> string",
            "command": ""
        }
    },
    {
        "range": {
            "start": {
                "line": 1,
                "character": 2
            },
            "end": {
                "line": 1,
                "character": 47
            }
        },
        "command": {
            "title": "Format.formatter -> t -> unit",
            "command": ""
        }
    }
]

[Trace - 1:52:53 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml",
    "diagnostics": []
}

[Trace - 1:52:53 PM] Sending request 'textDocument/documentSymbol - (24)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml"
    }
}

[Trace - 1:52:53 PM] Received response 'textDocument/documentSymbol - (24)' in 0ms.
Result: [
    {
        "name": "Solver",
        "kind": 2,
        "deprecated": false,
        "range": {
            "start": {
                "line": 14,
                "character": 0
            },
            "end": {
                "line": 29,
                "character": 3
            }
        },
        "selectionRange": {
            "start": {
                "line": 14,
                "character": 0
            },
            "end": {
                "line": 29,
                "character": 3
            }
        },
        "children": [
            {
                "name": "solve",
                "detail": "string -> unit",
                "kind": 12,
                "deprecated": false,
                "range": {
                    "start": {
                        "line": 26,
                        "character": 2
                    },
                    "end": {
                        "line": 28,
                        "character": 36
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 26,
                        "character": 2
                    },
                    "end": {
                        "line": 28,
                        "character": 36
                    }
                },
                "children": []
            },
            {
                "name": "parse",
                "detail": "string list -> int array",
                "kind": 12,
                "deprecated": false,
                "range": {
                    "start": {
                        "line": 15,
                        "character": 2
                    },
                    "end": {
                        "line": 24,
                        "character": 69
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 15,
                        "character": 2
                    },
                    "end": {
                        "line": 24,
                        "character": 69
                    }
                },
                "children": []
            }
        ]
    },
    {
        "name": "Fishies",
        "kind": 2,
        "deprecated": false,
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 12,
                "character": 3
            }
        },
        "selectionRange": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 12,
                "character": 3
            }
        },
        "children": [
            {
                "name": "make",
                "detail": "int list -> t",
                "kind": 12,
                "deprecated": false,
                "range": {
                    "start": {
                        "line": 3,
                        "character": 2
                    },
                    "end": {
                        "line": 11,
                        "character": 6
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 3,
                        "character": 2
                    },
                    "end": {
                        "line": 11,
                        "character": 6
                    }
                },
                "children": []
            },
            {
                "name": "compare",
                "detail": "t -> t -> int",
                "kind": 12,
                "deprecated": false,
                "range": {
                    "start": {
                        "line": 1,
                        "character": 2
                    },
                    "end": {
                        "line": 1,
                        "character": 47
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 1,
                        "character": 2
                    },
                    "end": {
                        "line": 1,
                        "character": 47
                    }
                },
                "children": []
            },
            {
                "name": "equal",
                "detail": "t -> t -> bool",
                "kind": 12,
                "deprecated": false,
                "range": {
                    "start": {
                        "line": 1,
                        "character": 2
                    },
                    "end": {
                        "line": 1,
                        "character": 47
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 1,
                        "character": 2
                    },
                    "end": {
                        "line": 1,
                        "character": 47
                    }
                },
                "children": []
            },
            {
                "name": "show",
                "detail": "t -> string",
                "kind": 12,
                "deprecated": false,
                "range": {
                    "start": {
                        "line": 1,
                        "character": 2
                    },
                    "end": {
                        "line": 1,
                        "character": 47
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 1,
                        "character": 2
                    },
                    "end": {
                        "line": 1,
                        "character": 47
                    }
                },
                "children": []
            },
            {
                "name": "pp",
                "detail": "Format.formatter -> t -> unit",
                "kind": 12,
                "deprecated": false,
                "range": {
                    "start": {
                        "line": 1,
                        "character": 2
                    },
                    "end": {
                        "line": 1,
                        "character": 47
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 1,
                        "character": 2
                    },
                    "end": {
                        "line": 1,
                        "character": 47
                    }
                },
                "children": []
            },
            {
                "name": "t",
                "kind": 15,
                "deprecated": false,
                "range": {
                    "start": {
                        "line": 1,
                        "character": 2
                    },
                    "end": {
                        "line": 1,
                        "character": 47
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 1,
                        "character": 2
                    },
                    "end": {
                        "line": 1,
                        "character": 47
                    }
                },
                "children": []
            }
        ]
    }
]

[Trace - 1:52:55 PM] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml"
    }
}

[Trace - 1:52:56 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 28,
                    "character": 21
                },
                "end": {
                    "line": 28,
                    "character": 33
                }
            },
            "severity": 1,
            "source": "ocamllsp",
            "message": "Unbound value Fishies.show"
        }
    ]
}

[Trace - 1:52:56 PM] Sending request 'textDocument/hover - (25)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml"
    },
    "position": {
        "line": 28,
        "character": 31
    }
}

[Trace - 1:52:56 PM] Received response 'textDocument/hover - (25)' in 3ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```ocaml\nint array -> string\n```"
    },
    "range": {
        "start": {
            "line": 28,
            "character": 21
        },
        "end": {
            "line": 28,
            "character": 33
        }
    }
}

[Trace - 1:52:57 PM] Sending request 'textDocument/codeAction - (26)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/cdaringe/src/aoc21/day6/lib/day6.ml"
    },
    "range": {
        "start": {
            "line": 28,
            "character": 21
        },
        "end": {
            "line": 28,
            "character": 33
        }
    },
    "context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 28,
                        "character": 21
                    },
                    "end": {
                        "line": 28,
                        "character": 33
                    }
                },
                "message": "Unbound value Fishies.show",
                "severity": 1,
                "source": "ocamllsp"
            }
        ],
        "only": [
            "quickfix"
        ]
    }
}

[Trace - 1:52:57 PM] Received response 'textDocument/codeAction - (26)' in 1ms.
No result returned.

</pre>
</details>

## Expected

This experienced deviated from expectations two fold:

1. Expected: no `Unbound value Fishies.show`. Clearly, the LSP can resolve my function successfully, as demonstrated on first boot. It's unclear why editing content around the codeblock makes it fail. I'm suspect of the `ppx` usage, in a nested project.

2. Expected: Single state of symbol. It seems incorrect to show a type signature, then also show "unbound value".

## references

- [commit](https://github.com/cdaringe/aoc-2021/commit/bccc9b03a90cb3208c1be51c1bdf1db7ec2d060d) where these symptoms can be observed
- [deriving show usage](https://github.com/cdaringe/aoc-2021/blob/bccc9b03a90cb3208c1be51c1bdf1db7ec2d060d/day6/lib/day6.ml#L2)
- `opam install --with-test --deps-only`, etc etc

**Comment by rgrinberg** [comment]
Can you try this with lsp#master?

**Comment by cdaringe** [comment]
```
ocamllsp --version
1.9.1-67-g0817d468
```

It now seems to get annotations, they're just incorrect. that is,

- `dune build`, compiles ok 👍 
- lsp annotations: `Unbound value Fishies.show ocamllsp`

platform is configured to use the same switch from which `dune build` is executed (running on a box with just a 4.12.1 switch)

**Comment by rgrinberg** [comment]
Thanks. To make progress, I will need to reproduce this locally. Could you try and turn your project into a test case?

**Comment by cdaringe** [comment]
On next visit, I will try and create a more MVP setup. I'm in OCaml so infrequent ATM that i'm not motivated at the moment to set it up, but I will certainly do so when I'm back in the rhythm! I can re-open at that point, or file a new issue
