### ISSUE TITLE
Code actions fail in mli files without corresponding ml file

### ISSUE THREAD

**Issue by ulugbekna** [ocamllabs/vscode-ocaml-platform#816]
Code actions are failing in .mli files that do not have a corresponding .ml file. Examples: `parsetree.mli` in this repo, or a gen_js_api bindings that use only mli files. 

The error: 

```
[Trace - 8:32:13 PM] Received response 'textDocument/codeAction - (77)' in 2ms. Request failed: uncaught exception (-32603).
Error data: {
    "exn": "Sys_error(\"/Users/ulugbekna/code/vscode-ocaml-platform/src-bindings/vscode/vscode_generated.ml: No such file or directory\")",
    "backtrace": "Raised by primitive operation at Stdlib.open_in_gen in file \"stdlib.ml\", line 405, characters 28-54\nCalled from Stdune__Io.Make.with_file_in in file \"submodules/dune/otherlibs/stdune/io.ml\", line 106, characters 17-37\nCalled from Ocaml_lsp_server__Inference.force_open_document in file \"ocaml-lsp-server/src/inference.ml\", line 42, characters 13-46\nCalled from Ocaml_lsp_server__Inference.infer_intf in file \"ocaml-lsp-server/src/inference.ml\", line 66, characters 22-56\nCalled from Ocaml_lsp_server__Action_inferred_intf.code_action in file \"ocaml-lsp-server/src/code_actions/action_inferred_intf.ml\", line 27, characters 16-68\nCalled from Fiber.Execution_context.apply in file \"submodules/dune/src/fiber/fiber.ml\", line 196, characters 9-14\n"
}


[Error - 8:32:13 PM] Request textDocument/codeAction failed.
  Message: uncaught exception
  Code: -32603 
[object Object]
```

Actions to take: 

1. The error shouldn't occur: either we're having a wrong assumption in one of the functions or we're not handling an error that doesn't violate any of the assumptions that we have
2. Failure of a single code action creation shouldn't result in all code actions failing. It'd be nice if an error notification is sent to the client when a code action creation happens, however.

**Comment by rgrinberg** [comment]
Fixed by https://github.com/ocaml/ocaml-lsp/pull/597

> Failure of a single code action creation shouldn't result in all code actions failing. It'd be nice if an error notification is sent to the client when a code action creation happens, however.

Or we can just fix the bug and move on. There's no need to complicate our code to recover from bugs.
