### ISSUE TITLE
laggy formatter

### ISSUE THREAD

**Issue by mimoo** [ocamllabs/vscode-ocaml-platform#834]
<img width="386" alt="Screen Shot 2022-01-28 at 3 04 51 PM" src="https://user-images.githubusercontent.com/1316043/151633636-3e442c86-6b83-4391-94c0-238193030e75.png">

When I save files I get these pop ups that queue up and slow everything down. Any idea how to get rid of this?

**Comment by ulugbekna** [comment]
You could turn off formatting. Either
1. Turn off formatting on save from vscode settings
2. Save without formatting (cmd +k +s on Mac)
3. Turn off formatting for ocaml files 

If you provide a reproducible case with more info we could maybe get to the root of why formatting on those files runs so long. Formatting is quite snappy unless the file is thousands of lines long.

**Comment by rgrinberg** [comment]
This should be fixed by the ocamlformat rpc protocol.

**Comment by rgrinberg** [comment]
Let's track this at https://github.com/ocamllabs/vscode-ocaml-platform/issues/834

**Comment by mimoo** [comment]
(you linked to the same issue)

**Comment by rgrinberg** [comment]
My bad. This is the correct ticket https://github.com/ocaml/ocaml-lsp/issues/495
