### ISSUE TITLE
Installation problem: A request has failed

### ISSUE THREAD

**Issue by yminsky** [ocamllabs/vscode-ocaml-platform#84]
And this shows up in the input:

```
[Error - 4:25:32 PM] Request textDocument/codeAction failed.
  Message: Magic_numbers.Cmi.Error(_)
  Code: -32603 
[Error - 4:25:32 PM] [lsp] Magic_numbers.Cmi.Error(_)
```

I'm on vscode 1.43.2, with a fully updated opam install of 4.09.0, with ocaml-lsp-server installed as per the opam-pinning instructions in that repo.

**Comment by imbsky** [comment]
I think this is probably a problem on the LSP side. CC: @rgrinberg @cannorin

**Comment by rgrinberg** [comment]
This usually happens when the ocaml-lsp does not match the version of OCaml being used.

In vscode, open a new terminal (from the terminal menu) and paste the result of:
```
$ which ocamllsp
$ which ocamlc
```

Those should come from the same switch.

Make sure to do a clean build as well. It's possible that you have stale artifacts in your _build directory.

**Comment by yminsky** [comment]
Hmm.  I just did a clean and build, which worked fine, and I don't think the `which` showed anything unusual:

```
[yminsky@viserion z]$ which ocamllsp
~/.opam/4.09.0/bin/ocamllsp
[yminsky@viserion z]$ which ocamlc
~/.opam/4.09.0/bin/ocamlc
```

showed anything too interesting.

**Comment by yminsky** [comment]
Oh, I responded too soon.  It does seem to be working now -- maybe it took a bit for the plugin to pick up on the changes.

So, maybe the only thing to improve is a clearer error message for this case.

Thanks!

**Comment by imbsky** [comment]
The error message improvement task was opened as #112, so can we close this problem?

**Comment by imbsky** [comment]
You can now explicitly specify toolchains with master version, so maybe this problem is unlikely to happen. I would like to open another issue to improve the error message if we need, so I will close this.
