### ISSUE TITLE
Extension crashes extension host

### ISSUE THREAD

**Issue by ulugbekna** [ocamllabs/vscode-ocaml-platform#849]
Lately, the extension is crashing the VS Code extension host. Wanted to ask if anyone else is experiencing this and if someone has any idea why this may be happening. 

Developer tools: 

![image](https://user-images.githubusercontent.com/16353531/152981718-e89d6d00-c853-4876-8a8e-40bc34a195fa.png)

vscode version: 
```
1.64.0
5554b12acf27056905806867f251c859323ff7e9
x64
```

os version:
macos big sure 11.6 (20G165)

vscode ocaml platform version: 
current master dc2575e98c99a359d21276d3098ab36789dde7b8

I don't notice crashes happening with VS Code Insiders, but I'm sure the extension crashed with vscode January and now vscode February, ie even if the problem is with vscode and there's a fix in insiders, it's not getting into mainstream vscode.

**Comment by ulugbekna** [comment]
Hmm, since I removed GitLens extension from vscode, the crashes seem gone

**Comment by ulugbekna** [comment]
Indeed, gitlens crashing the extension seems possible according to gitlens author:

> GitLens uses built-in vscode commands that call out to the appropriate language servers to get the symbols for the current document, and there have been issues in other languages (python), where the language server had bugs where concurrent requests would cause failures. And the Outline view in vscode calls out to the language servers similarly to GitLens, and so both can do them at the same time.

**Comment by brendanzab** [comment]
Ran into this as well. Can confirm that GitLens seemed to be the culprit, and that disabling it worked for me. Does seem a bit of a shame to not be able to use it in OCaml projects, alas.

**Comment by ulugbekna** [comment]
@brendanzab could you confirm you have got submodules used in that project?

**Comment by brendanzab** [comment]
Nah, no submodules

**Comment by brendanzab** [comment]
Hmm, seems like [vscode-direnv](https://github.com/cab404/vscode-direnv) might also interact with vscode-ocaml-platform to produce an extension host crash?

**Comment by brendanzab** [comment]
Seems like a workaround for vscode-direnv is to:

1. disable the OCaml Platform extension for the current workspace
2. run "Developer: Restart Extension Host" from the command palette (loading the OCaml tools from the `.envrc`)
3. enable the OCaml Platform extension for the current workspace

It's a bit unfortunate as it used to work seemlessly with direnv! :(

**Comment by ulugbekna** [comment]
Can still reproduce...

**Comment by ulugbekna** [comment]
Can't reproduce anymore with latest vscode-ocaml-platform extension and ocaml-lsp

**Comment by EduardoRFS** [comment]
I can still reproduce but I'm not in the latest ocaml-lsp
