### ISSUE TITLE
Latest ocaml-lsp check does not take 4.14.0~alpha/1.9.2~4.14preview into account

### ISSUE THREAD

**Issue by yannl35133** [ocamllabs/vscode-ocaml-platform#857]
https://github.com/ocamllabs/vscode-ocaml-platform/blob/414ae859ec62dc9256944d8f6026ca47709f622c/src/ocaml_lsp.ml#L88-L89

This should include a check for 1.9.2~4.14preview (which for some reason prints as `1.1.0-724-gc5def3b700` when one asks ocamllsp)

**Comment by rgrinberg** [comment]
Yes indeed. Could you send a PR for this? It should be quite easy to fix now.

**Comment by yannl35133** [comment]
The version `ocamllsp --version` prints out is weird, are you sure it should be that way ? Considering this is the input it would check against, it would commit this oddity

**Comment by rgrinberg** [comment]
Sure, it would be odd. But at least users of the preview release will not see the warning. @kit-ty-kate any idea what happened to that version number?

**Comment by yannl35133** [comment]
https://github.com/ocamllabs/vscode-ocaml-platform/pull/878 (hacked it together in a few minutes, I didn't even verify it still compiled (it should, still))

**Comment by yannl35133** [comment]
I just noticed the new version check now ignores versions it doesn't know, including 4.14 so my PR, although valid, is a bit useless for an experimentally supported version

**Comment by rgrinberg** [comment]
Yes, but your PR will be useful once we publish a stable version for 4.14. Our plugin will suggest users to upgrade from the experimental version.

Rudi.

**Comment by yannl35133** [comment]
So much for a single line. Maybe I/you/we should add the 4.13 preview as supported, if I/you/we want to be exhaustive; I doubt it would change much, but the one user stuck at that version would get the warning

**Comment by yannl35133** [comment]
I think the issue can be closed now, can it not ?
