### ISSUE TITLE
Wrong warning "The installed version of `ocamllsp` is out of date"

### ISSUE THREAD

**Issue by Kakadu** [ocamllabs/vscode-ocaml-platform#861]
New v1.9.0 complaing about my fresh ocaml-lsp-server, saying that it is too old?
> The installed version of `ocamllsp` is out of date. You may be missing out on cool features or important bug fixes. Consider upgrading the package `ocaml-lsp-server`.

Log output -- you can observe that my lsp-server is fresh
```
external command {
  "bin": "/home/kakadu/bin/opam",
  "args": [
    "exec",
    "--switch=4.13.1+flambda",
    "--set-switch",
    "--root",
    "/media/work/.opam",
    "--",
    "ocamllsp",
    "--version"
  ]
}

external command (finished) {
  "bin": "/home/kakadu/bin/opam",
  "args": [
    "exec",
    "--switch=4.13.1+flambda",
    "--set-switch",
    "--root",
    "/media/work/.opam",
    "--",
    "ocamllsp",
    "--version"
  ],
  "result": {
    "exitCode": 0,
    "stdout": "1.10.1\n",
    "stderr": ""
  }
}

external command {
  "bin": "/home/kakadu/bin/opam",
  "args": [
    "exec",
    "--switch=4.13.1+flambda",
    "--set-switch",
    "--root",
    "/media/work/.opam",
    "--",
    "ocamllsp"
  ]
}
````

1) Could you double-check comparison on current and minimal versions of lsp-server?
2) Could this warning message show also expected and gotten versions?

**Comment by yannl35133** [comment]
1. should be solved
2. is still a good idea

**Comment by rgrinberg** [comment]
2. is also done.
