### ISSUE TITLE
Dune's `rule` stanza in `subdir` is not highlighted properly

### ISSUE THREAD

**Issue by tmattio** [ocamllabs/vscode-ocaml-platform#864]
The following dune code doesn't seem to be highlighted properly with VSCode 1.9.0:

```
(subdir
 asset/
 (rule
  (target main.css)
  (deps
   (:data ../tailwind.config.js ../postcss.config.js)
   (source_tree ../node_modules)
   (source_tree ../src/ocamlorg_frontend))
  (action
   (chdir
    %{workspace_root}
    (run
     node
     node_modules/postcss-cli/index.js
     src/ocamlorg_frontend/css/styles.css
     -o
     %{target})))))
```

![image](https://user-images.githubusercontent.com/6162008/153873320-9fc77a02-c4d3-4f23-8c0b-e1a2f2a6f949.png)

cc @SaySayo

**Comment by SaySayo** [comment]
I'll look into it now

**Comment by SaySayo** [comment]
<img width="719" alt="Screenshot 2022-02-14 at 20 06 28" src="https://user-images.githubusercontent.com/75541866/153929667-6675aebb-0e29-4db6-9772-98b8a660bbd1.png">
@tmattio I just made these changes. Are these good now?
