### ISSUE TITLE
Regression: The file 'Changes' is closed automatically in >= 1.9

### ISSUE THREAD

**Issue by Kakadu** [ocamllabs/vscode-ocaml-platform#869]
When ocaml-platform extension is enabled file 'Changes' is opened in the editor and closed immediately. 
If I disable our extension, the file ones fine and I can edit it. 
It appeared only recently, I suspect in the last update. Could you double-check?

For me version 1.8.4 is fine, bad things started in 1.9

**Comment by Khady** [comment]
I have the same problem. It can happen on any file that doesn't have an extension. Another example is a `_build/log` file generated by dune. In this case vscode is trying to be smart and to detect which language mode would fit the best. I suppose that it is iterating through all the language modes. And when it reaches the ocaml mode there's a bug that forces the editor to be closed.

The bug doesn't appear if I renamed `_build/log` into `_build/log.ml`.

**Comment by rgrinberg** [comment]
If you have the time, bisecting this issue would be quite useful

**Comment by mnxn** [comment]
I can reproduce this on both Windows and macOS since 1.9.0

I didn't find any relevant logs on macOS, but on Windows I get `[Extension Host] No active editor found.` in the developer console with a source location of `workbench.desktop.main.js:75`. I haven't found a root cause yet.

Also I think this is the same issue as #874.

**Comment by mnxn** [comment]
Looks like the bug was introduced in the AST explorer commit (https://github.com/ocamllabs/vscode-ocaml-platform/commit/37493b82ba9eea77abc0ee2c9c25df9eee6ab75f).

**Comment by mnxn** [comment]
The files are closed here by the `closeActiveEditor` VSCode command:

https://github.com/ocamllabs/vscode-ocaml-platform/blob/571213ef5a039f280508751302dc7e5ccfa8ee28/src/ast_editor.ml#L559-L580

For some reason extensionless files raise an onDidClose event within VSCode when they are opened. Our extension subscribes to that event and calls `close_visible_editors_by_uri` with the file path.

Honestly I'm not really sure what the point of `close_visible_editors_by_uri` is in the first place. I removed that function call and I couldn't notice any difference in the AST explorer feature. Removing it fixes the bug in this issue.

@arozovyk: do you happen to remember what this function is for? If it is necessary, is there another way it could be implemented to avoid this bug?

**Comment by rgrinberg** [comment]
> Honestly I'm not really sure what the point of close_visible_editors_by_uri is in the first place. I removed that function call and I couldn't notice any difference in the AST explorer feature. Removing it fixes the bug in this issue.

Since this is a serious bug that affects everyone, while removing this function may possibly affect only the subset of users using the AST explorer, I say let's remove it now and ask @arozovyk questions later. Do you think you could send a patch and release 1.9.5  with this fix?
