### ISSUE TITLE
Auto closing pairs too aggressive

### ISSUE THREAD

**Issue by debugnik** [ocamllabs/vscode-ocaml-platform#87]
Commit 892c854e1dcc572034b7b8c52c902079e2c8df38 recently added auto closing support for `'` and `<`. This is annoying because it interferes with type parameters and the less-than operator, which don't "close". I'm guessing this is not the desired behaviour.

P.S. Version 0.3.0 is live on the VS Marketplace but there's no tag/release.

**Comment by rgrinberg** [comment]
Thanks. I got rid of the auto-closing and published 0.3.1 (all the tags should be present)

**Comment by debugnik** [comment]
Wow, that was quick! Thanks!
