### ISSUE TITLE
VSCode select langauge OCaml closes new tab

### ISSUE THREAD

**Issue by Alizter** [ocamllabs/vscode-ocaml-platform#874]
If I open a new window, VSCode asks me to choose a language. When I click this and select OCaml it just closes the new tab.

**Comment by ulugbekna** [comment]
Could you show us a screen recording because we can't reproduce what you're describing?

**Comment by Alizter** [comment]
@ulugbekna Here is a recording, it seems there is no redirection but only the new tab failing to exist after changing the language mode.

![Peek 2022-02-19 12-14](https://user-images.githubusercontent.com/8614547/154800381-27db0eb2-a9b7-4c07-8c10-47fbf6330536.gif)

**Comment by ulugbekna** [comment]
Thanks, that I can reproduce. 

This is what the vscode trace looks like: 

```
[2022-02-19 13:50:02.464] [renderer1] [trace] CommandService#executeCommand workbench.action.editor.changeLanguageMode
[2022-02-19 13:50:09.164] [renderer1] [trace] CommandService#executeCommand workbench.action.closeActiveEditor
```

Interestingly, when OCaml Platform extension is activated, changing language for a new unsaved file to _any_ language closes the file
