### ISSUE TITLE
Polish opam syntax highlighting

### ISSUE THREAD

**Issue by imbsky** [ocamllabs/vscode-ocaml-platform#97]
The current syntax highlighting is quite awkward.
<img alt="Screen Shot 2020-04-03 at 17 03 13" src="https://user-images.githubusercontent.com/38746192/78338087-189e6280-75cd-11ea-8490-c75afd79f49c.png">

**Comment by mnxn** [comment]
I can take a look tomorrow.

**Comment by imbsky** [comment]
Thanks @mnxn!
