### ISSUE TITLE
Switch impl/intf problems in ml files

### ISSUE THREAD

**Issue by ulugbekna** [ocamllabs/vscode-ocaml-platform#976]
The icon on the top right isn't shown for ml files. The shortcut also doesn't work for ml files. The command from the command palette works though.

Both icon and shortcut are fine on mli files. 

If anyone wants to work on this: if you can't right away find what the problem is, perhaps it's worth bisecting because those things worked fine some time ago.

**Comment by ulugbekna** [comment]
The problematic commit is 536b5290de66166c24316421c60c5eba018ebc03 because of https://github.com/microsoft/vscode/issues/91473

**Comment by ulugbekna** [comment]
@TheLortex Hi Lucas, would you mind taking a look at this? To avoid huge "or"s, I think we could set dynamic context and use [`in`](https://code.visualstudio.com/api/references/when-clause-contexts#in-conditional-operator) construct in `when` clauses?  Certain language IDs should be possible to put under one context name such as "ocamlSourceLike" being `ocaml`, `ocaml.interface`, `reason`, etc.

**Comment by TheLortex** [comment]
Oh I'm sorry for introducing these regressions. 
I see that the commit has been reverted. I'll be working on a better version of https://github.com/ocamllabs/vscode-ocaml-platform/pull/962 using the `in` construct, thanks for the suggestion.
