### ISSUE TITLE
how to use this extension with direnv/nix?

### ISSUE THREAD

**Issue by mimoo** [ocamllabs/vscode-ocaml-platform#984]
Hello!

I have an `.envrc` file in my repo, and my vscode is supposedly picking it up with the direnv extension. But it seems like OCaml platform is still not aware of the switch I'm supposedly on (it's still using the system switch). Is there a known way to make this work?

**Comment by ulugbekna** [comment]
I’m not sure I know the answer to this question, but can’t you specify your sandbox to be a particular switch of desire? See the readme on what a sandbox is and how to set it

**Comment by mimoo** [comment]
yeah it seems to work!

**Comment by acorrenson** [comment]
Hi there,
I ran into the exact same problem, and it took me a while to figure how to do it.
For future reference and for the complete nix newbies like me, a nice trick is to setup ocaml platform to use the custom sandbox `nix develop --command $prog $args`.

**Comment by ulugbekna** [comment]
@acorrenson I’m sorry it took you a while to figure this out

do you have any feedback on what we could do better? Also, what was your first point of reference when you faced this problem?

**Comment by brendanzab** [comment]
> For future reference and for the complete nix newbies like me, a nice trick is to setup ocaml platform to use the custom sandbox `nix develop --command $prog $args`.

Oh wow! It would be nice if this was documented in the README. I have been struggling for over a year with the the OCaml extension looking for the OCaml tooling _before_ the [direnv extension](https://marketplace.visualstudio.com/items?itemName=mkhl.direnv) has loaded the environment variables. The extension ends up in an unrecoverable state, so even restarting it from the command palette makes no difference, claiming it can’t find the OCaml tools in the environment. Hence when I update my shell environment I’ve been doing the following workaround:

1. close all my OCaml files in my editor
2. make sure I’ve selected a non-OCaml file in the file browser
3. close and reopen my project again

Which obviously makes the experience of using OCaml pretty painful. Somehow I don’t have the same issue with other language extensions like [rust-analyzer](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer). It would be pretty cool if it just worked out of the box with direnv + ocaml-lsp, but I’ll try the workaround @acorrenson suggests.

**Comment by brendanzab** [comment]
Wait no, it seems I spoke too soon. Seems like I’m getting this again when I re-open my editor with the custom sandbox set to use `nix develop`:

![Screenshot 2023-09-19 at 7 19 50 pm](https://github.com/ocamllabs/vscode-ocaml-platform/assets/695077/85d2f99a-5b04-4679-b855-10499224746d)

This is the same error I used to get when using the global sandbox with the direnv extension (if I had any OCaml files open, or had on selected in the file browser when I last closed the editor).

**Comment by brendanzab** [comment]
It does seem to put up the error pretty quickly when I open the editor – I dunno if it actually blocks long enough? Running commands via `nix develop --command ...` can be a little slow at times.

**Comment by han-tyumi** [comment]
I ended up having to use the following because `nix develop` was being run at `/` for me.
Wish we could use `${workspaceFolder}` here or something that's a bit more reliable.

```json
{
  "ocaml.sandbox": {
    "kind": "custom",
    "template": "nix develop \"${DIRENV_DIR#-}\" --command $prog $args"
  }
}
```

**Comment by brendanzab** [comment]
Hmm, that doesn’t deem to work for me alas. In the OCaml Language Server Output I get:

```
error: '' is not a valid URL
[Error - 21:43:47] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 21:43:47] Connection to server got closed. Server will restart.
true
[Error - 21:43:47] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
error: '' is not a valid URL
[Error - 21:43:47] Server initialization failed.
...
```

I assume this means that `DIRENV_DIR` is not set in the context of my editor for whatever reason?

**Comment by han-tyumi** [comment]
> Hmm, that doesn’t deem to work for me alas. In the OCaml Language Server output I get:
> 
> 
> 
> ```
> 
> error: '' is not a valid URL
> 
> [Error - 21:43:47] Server initialization failed.
> 
>   Message: Pending response rejected since connection got disposed
> 
>   Code: -32097 
> 
> [Info  - 21:43:47] Connection to server got closed. Server will restart.
> 
> true
> 
> [Error - 21:43:47] OCaml Platform VS Code extension client: couldn't create connection to server.
> 
>   Message: Pending response rejected since connection got disposed
> 
>   Code: -32097 
> 
> error: '' is not a valid URL
> 
> [Error - 21:43:47] Server initialization failed.
> 
> ...
> 
> ```
> 
> 
> 
> I assume this means that `DIRENV_DIR` is not set in the context of my editor for whatever reason?

See: https://github.com/ocamllabs/vscode-ocaml-platform/issues/1222#issuecomment-1732451170.

**Comment by brendanzab** [comment]
Oh cool, that worked. I was getting these errors logged in the Output of OCaml Platform Extension:

```
external command (finished) {
  "bin": "/nix/store/...-opam/bin/opam",
  "args": [
    "--version"
  ],
  "result": {
    "exitCode": 1,
    "stdout": "",
    "stderr": "/nix/store/...-set-vars.sh: line 21: NIX_BUILD_TOP: unbound variable\n"
  }
}
```

I _think_ this is a bug with [opam-nix](https://github.com/tweag/opam-nix) and nix-direnv though. Somehow `NIX_BUILD_TOP` was making its way into `set-vars.sh` (which is generated [here](https://github.com/tweag/opam-nix/blob/ff4ba8c148b2f64dbb418782be8173dfca7dc2c4/src/builder.nix#L193)). As a workaround, the final thing I used was:

```json
{
    "ocaml.sandbox": {
        "kind": "custom",
        "template": "NIX_BUILD_TOP=\"\" nix develop ${firstWorkspaceFolder} --command $prog $args",
    },
}
```

This is probably not quite right, but it seemed to silence the errors I was getting.

**Comment by brendanzab** [comment]
To be clear, I still think it’d be neat if it worked out of the box with [mkhl.direnv](https://marketplace.visualstudio.com/items?itemName=mkhl.direnv) – calling commands through `nix develop --command ...` is pretty slow, which affects how long the extension takes to load. 😔

**Comment by madidier** [comment]
@brendanzab:

I put the following in my workspace's `.vscode/settings.json` to make use of direnv-nix's cache and get a faster start up time:

```json
{
  "ocaml.sandbox": {
    "kind": "custom",
    "template": "direnv exec ${firstWorkspaceFolder} $prog $args"
  }
}
```

It's very unusual for a language extension not to be able to pick up updated environment variable after an extension reload.
