### ISSUE TITLE
Unable to open terminal file link at specific line since vscode 1.69

### ISSUE THREAD

**Issue by terencode** [ocamllabs/vscode-ocaml-platform#992]
Since vscode 1.69 there is [Shell integration](https://code.visualstudio.com/updates/v1_69#_shell-integration) and it seems to break the ability to jump to a file at the line mentioned in the terminal : 

 ![before](https://user-images.githubusercontent.com/12665563/181278317-25823482-1d89-4bc6-b81a-efbac197545d.png)

Even when it's disabled in the settings, ctrl+left clicking on an error opens the corresponding file but does not put the cursor at the mentioned line. 

Downgrading to 1.68.1 fixes the issue :
![after](https://user-images.githubusercontent.com/12665563/181278442-15a98d40-7994-4330-94d3-12fe6d2cc85e.png)

**Comment by mnxn** [comment]
Isn't this a VSCode issue? I'm not sure there's anything we can do on our side.

**Comment by terencode** [comment]
> Isn't this a VSCode issue? I'm not sure there's anything we can do on our side.

I've been told by @rgrinberg to still open one so others running into the problem can check it's a known issue

**Comment by terencode** [comment]
I think the upstream issue is tracked here : https://github.com/microsoft/vscode/issues/156236

**Comment by lukstafi** [comment]
The upstream is here [microsoft/vscode#171880](https://github.com/microsoft/vscode/issues/171880). Things worked until OCaml started outputting the `lines X-Y` format... It's also (in principle) possible to fix the links problem in the extension land: e.g. [Terminal File Link extension](https://marketplace.visualstudio.com/items?itemName=danh42.terminal-file-link) (I'm not sure if it worked for me).

**Comment by smorimoto** [comment]
The latest VSCode release fixes this: https://code.visualstudio.com/updates/v1_80#_multiline-and-range-link-formats
